### PR TITLE
add BON Network

### PR DESCRIPTION
**Pull request by toorls**
{
  "name": "BON Network",
  "chain": "BON",
  "network": "testnet",
  "rpc": ["http://rpc.boyanet.org:8545/"],
  "faucets": [],
  "nativeCurrency": {
    "name": "BOYACoin",
    "symbol": "BOY",
    "decimals": 18
  },
  "infoURL": "http://boyanet.org",
  "shortName": "boya",
  "chainId": 1898,
  "networkId": 1,
  "explorers": [{
    "name": "explorer",
    "url": "http://explorer.boyanet.org:4000",
    "standard": "EIP3091"
  }]
}

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
That does not look like an explorer to me:

image


if it is - I really cannot check for EIP3091 compatibility

**Comment by toorls** [comment]
> That does not look like an explorer to me:
> 
> image
> 
> if it is - I really cannot check for EIP3091 compatibility

The website needs to be filed. I have fixd it.

**Comment by ligi** [comment]
any chance you can add https to the server? You would be the first one without and the CI does not like that (if really needed I could change that thoug)

**Comment by toorls** [comment]
update to https

**Pull request merged**
