### PR TITLE
add brcchain mainnet

### PR DESCRIPTION
**Pull request by JackL111**

### CODE REVIEW

**Comment by JackL111** [comment]
Add brcchain mainnet

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by JackL111** [comment]
Hello, I have already formatted the JSON file and resolved the issue with the IPFS icon.

**Comment by JackL111** [comment]
hi, I have already resolved the issues, thanks for your time.

**Pull request merged**
