### PR TITLE
Add alternative explorers and RPCs to some chains

### PR DESCRIPTION
**Pull request by Kharabet**

### CODE REVIEW

**Comment by Kharabet** [comment]
@ligi I've run `npx prettier --write _data/*/*.json`. Dunno what could be wrong else..

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by Kharabet** [comment]
> image

All look good from my side
image

**Comment by Kharabet** [comment]
@ligi sir please take a look, i think it's good to go

**Pull request closed without merging**
