### PR TITLE
Add LocaChain mainnet

### PR DESCRIPTION
**Pull request by devlocago**
Add LocaChain mainnet

### CODE REVIEW

**Comment by devlocago** [comment]
i update new url of rpc and merge to master

**Comment by devlocago** [comment]
We updated format json with standard format

**Comment by devlocago** [comment]
Please check we update new json

**Review by devlocago — COMMENTED** [review]
Remove icon json file

**Review by devlocago — COMMENTED** [review]
update Json file

**Review by ligi — APPROVED** [review]

**Pull request merged**
