### PR TITLE
Add JFIN Chain

### PR DESCRIPTION
**Pull request by dome**
* add a jfin chain
* add rpc url
* add explorer url

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The size does not match:
```
✓ ~/tmp identify bafkreie4uhrsk3vxxnpjm7tidupfxgib5ahnwqopf6elykdatshuo6yb4m
bafkreie4uhrsk3vxxnpjm7tidupfxgib5ahnwqopf6elykdatshuo6yb4m SVG 781x781 781x781+0+0 8-bit sRGB 38717B 0.000u 0:00.000
```

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot reach your explorer

**Comment by dome** [comment]
> I cannot reach your explorer

fix already. please try again

**Review by dome — COMMENTED** [review]
fix already

**Pull request closed without merging**
