### PR TITLE
add TAPROOT Mainnet 

### PR DESCRIPTION
**Pull request by TaprootChain**
@ligi I have fixed the issue of chainId mismatch. Please approve the workflow again. Thank you

### CODE REVIEW

**Comment by TaprootChain** [comment]
@ligi  Hello, we are going to launch the mainnet recently and the time is urgent. Can you help me review it? ,Thank you so much.

**Comment by TaprootChain** [comment]
@pedrouid  Hello, can you help with the approval workflow? Thank you so much

**Comment by ligi** [comment]
If time is urgent pay funds to lists.eth (in your case 1kDAI as it was really rude to ping 2 people the same day as opening the PR and I personally find your project most stupid) - otherwise wait - it will be merged without sending funds - but it will take time.

**Comment by TaprootChain** [comment]
@ligi  Hello, we have donated 1000 DAI to lists.eth to support your development and maintenance. As we are a startup team, we hope you can understand. Thank you.

Transaction Hash:0x265a40dcb3eac7b94d5cf0a03a81db109d50c2e880f46e57f65455e3628a018a

**Review by Yardapestr — APPROVED** [review]

**Pull request merged**
