### PR TITLE
added pepechaint-testnet details

### PR DESCRIPTION
**Pull request by pepem00n**

### CODE REVIEW

**Comment by deep709** [comment]
Thanks

**Comment by pepem00n** [comment]
tried multiple times to upload the icons to ipfs, all the time locally we can resolve the icon but the merge checks fails, can we get more info on how to properly do this?

thanks

**Comment by ligi** [comment]
Please just do something else - it is clear you should not run a chain ..

**Comment by pepem00n** [comment]
> 

thanks for the unsolicited advice.

i'm not a technical person behind this project and for me the CID provided in the json is returning the image with the properties in the json, so if you could help me with some actual advice instead of sarcasm that would be great.

**Pull request closed without merging**
