### PR TITLE
Update cennznet

### PR DESCRIPTION
**Pull request by aidan-starke**
- update chain/network id to 21337
 - add width & height properties to cennz icon

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
You cannot just change a chainID - you need to deprecate the old chain and add a new one - otherwise this opens doors to replay attacks
Also the size of the SVG is weird - and vector assets do not need a size

**Comment by ligi** [comment]
Also:

```
✓ ~ curl -X POST -H  "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' https://cennznet.unfrastructure.io/public
{"jsonrpc":"2.0","result":"0x539","id":1}
```

**Comment by aidan-starke** [comment]
I was a bit ahead of schedult - it has been updated now

```
curl -X POST -H  "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' https://cennznet.unfrastructure.io/public
{"jsonrpc":"2.0","result":"0x5359","id":1}
```

'0x5359' === 21337

**Comment by ligi** [comment]
still - you cannot just do that as it opens the door for replay attacks. Why did you change the chainID in the first place?

**Comment by aidan-starke** [comment]
chainId 1337 is registered as one of metamask's default networks so it cannot be added to metamask via `wallet_addEthereumChain`.

**Comment by ligi** [comment]
> chainId 1337 is registered as one of metamask's default networks so it cannot be added to metamask via

interesting - do you know which chain it is there?

**Comment by aidan-starke** [comment]
pretty sure it's used by ganache for local development

**Pull request merged**
