### PR TITLE
[75512][change] GEEK chain native currency

### PR DESCRIPTION
**Pull request by greatdex**
GEEK chain native currency has been changed to OAS

### CODE REVIEW

**Comment by greatdex** [comment]
@ligi Hello, please review the change made to GEEK chain

**Review by ligi — CHANGES_REQUESTED** [review]
please provide any evidence

**Comment by degiatenish** [comment]
Hi @ligi  I am the representative of the chain. I created the first PR and I grant this change. Please approve it. Thanks.

**Comment by degiatenish** [comment]
https://explorer.geekout-pte.com/evidence.txt

This is the evidence stored on the official explorer. thanks.

**Review by ligi — APPROVED** [review]

**Pull request merged**
