### PR TITLE
Add ARC Blockchain mainnet and testnet

### PR DESCRIPTION
**Pull request by wombatlabs**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Fix CI errors

**Review by ligi — CHANGES_REQUESTED** [review]
still a lot of CI errors - re-request review only if they are fixed

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Review by ligi — CHANGES_REQUESTED** [review]
@wombatlabs please only request review if CI passes

**Review by ligi — CHANGES_REQUESTED** [review]
CI still not passing

**Review by Marvin8122 — APPROVED** [review]

**Review by ligi — APPROVED** [review]

**Pull request merged**
