### PR TITLE
Add Dymension Mainnet

### PR DESCRIPTION
**Pull request by mtsitrin**
Dymension is a layer 1, modular blockchain designed to secure and interconnect rollups using the Inter-Blockchain Communication (IBC) standard.

https://portal.dymension.xyz/

### CODE REVIEW

**Comment by ligi** [comment]
image

**Comment by mtsitrin** [comment]
it's not up yet. will be very soon
I've set `"status": "incubating"` for now

**Comment by VictorTrustyDev** [comment]
Hi there, I'm Victor, the product owner of the website.

The website URL is for Mainnet.
Currently the website haven't got started yet because the mainnet is not yet live.

For reference purpose, this is the website for Testnet https://fl.dym.fyi which is EIP-3091 compatible and it is exactly the same with the Mainnet one.

**Review by ligi — APPROVED** [review]

**Comment by VictorTrustyDev** [comment]
@mtsitrin let's finish this PR

**Pull request merged**
