### PR TITLE
add Orderly testnet

### PR DESCRIPTION
**Pull request by zlog-in**

### CODE REVIEW

**Comment by zlog-in** [comment]
@ligi Finished successful run locally

**Comment by Mikemfnb1** [comment]
Mb

**Comment by zlog-in** [comment]
Add new line to the end of json file for chain data

**Review by ligi — APPROVED** [review]

**Comment by zlog-in** [comment]
@ligi passed checks now and please merge

**Review by ligi — APPROVED** [review]

**Pull request merged**
