### PR TITLE
Add HAPchain Testnet and Mainnet configuration and icon

### PR DESCRIPTION
**Pull request by worawutboy**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by worawutboy** [comment]
Sorry for your cost a lot of time, I have resolved my CID now can get it and i put it in iconDownload

**Review by ligi — CHANGES_REQUESTED** [review]
thanks - just one more thing:

Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by worawutboy** [comment]
Thank you for taking the time to make a suggestion. Could you please kindly review it once more?

**Review by ligi — APPROVED** [review]

**Pull request merged**
