### PR TITLE
Add RPC for chain 100009

### PR DESCRIPTION
**Pull request by ifavo**
This PR adds a RPC endpoint for chainid 100009

### CODE REVIEW

**Comment by ifavo** [comment]
What do I need to do, to get it merged?

**Comment by vladevelops** [comment]
Hi @ifavo,  us a suggestion to make it go through, change to draft and then mark as ready to review.

**Comment by ifavo** [comment]
> Hi @ifavo, us a suggestion to make it go through, change to draft and then mark as ready to review.

🙏  Okay, I did convert to draft & marked as ready for review.

**Comment by vladevelops** [comment]
> > Hi @ifavo, us a suggestion to make it go through, change to draft and then mark as ready to review.
> 
> 🙏 Okay, I did convert to draft & marked as ready for review.
> 
> Isn't it just adjusting the state to what it was already?

I can suggest only from my experience with the process, and in they README the have this:

>> When making changes that fix the CI problems - please re-request a review - otherwise it is too much work to track such changes with so many PRs daily

**Review by ligi — APPROVED** [review]

**Pull request merged**
