### PR TITLE
wyzth mainnet

### PR DESCRIPTION
**Pull request by WYZTH**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The other chain is still active - you cannot change it

**Review by bitcoinfinancier — APPROVED** [review]

**Review by minimayki6232 — APPROVED** [review]

**Comment by selarun13** [comment]
0x6F99E90Dd385c23826b416528e325214671FeBf6

**Comment by selarun13** [comment]
0x6F99E90Dd385c23826b416528e325214671FeBf6

**Comment by WYZTH** [comment]
Hi @ligi 

We have the mainnet with chain Id running from January of 2022 and have 18+ Million wallets and 29+ Million transactions over 3+ Million blocks.

The explorers are 
https://wyzthscan.org/

The community explorer is https://legacy.wyzthscan.org/

We have run multiple decentralised applications on the chain.

It would be great to have an entry for Wyzth Mainnet as well.

Any resolution in this regard would be much appreciated.

Thanks,
Team Wyzth

**Comment by ligi** [comment]
I do not see a resolution - we only list one chain per id to protect users from replay attacks.
The only chance is that the other chain stops - please read: https://github.com/ethereum-lists/chains#collision-management

**Comment by WYZTH** [comment]
Hi Team,

We have the mainnet with chain Id running from January of 2022 and have 18+
Million wallets and 29+ Million transactions over 3+ Million blocks.

The explorers are
https://wyzthscan.org/

The community explorer is https://legacy.wyzthscan.org/

We have run multiple decentralised applications on the chain.

It would be great to have an entry for Wyzth Mainnet as well.

Any resolution in this regard would be much appreciated.

Thanks,
Team Wyzth

**Pull request closed without merging**
