### PR TITLE
Add ULED Testnet & Mainnet 

### PR DESCRIPTION
**Pull request by mahendraDV**

### CODE REVIEW

**Comment by ligi** [comment]
Hm - do not really want to check trademarks/copyright here - also do not think we have to here as this is just a registry. I will just not merge because CI is failing - but IANAL and do not want to take care fore copyright/trademark. But yeah - the OP should check this and close the PR if there is a violation.

**Comment by mahendraDV** [comment]
@Tdancer  and @ligi  , thank you both for your input.

To clarify, the USBC currency is not associated with the US Blockchain Coalition, and we acknowledge the potential confusion the name might create. We will escalate this to our legal team to avoid any trademark/copyright issues.

Regarding the CI failing issue, I've already fixed it, so please feel free to review the changes. 

Your feedback is valuable, and we appreciate your understanding as we work to resolve these issues. Please proceed with the review of the changes, and if you have any further comments or suggestions, don't hesitate to let us know. Thank you!

**Comment by mahendraDV** [comment]
@ligi please review & approve. Thank you!

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Pull request closed without merging**
