### PR TITLE
Update XDC Network info.

### PR DESCRIPTION
**Pull request by AnilChinchawale**
- Add extra rpcs in Mainnet
- update explorer links
- add the faucet link in XDC Apothem/TestNet

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
the size does not match:

```
identify QmeRq7pabiJE2n1xU3Y5Mb4TZSX9kQ74x7a3P2Z4PqcMRX         18:48:20
QmeRq7pabiJE2n1xU3Y5Mb4TZSX9kQ74x7a3P2Z4PqcMRX PNG 1450x1450 1450x1450+0+0 8-bit sRGB 76017B 0.000u 0:00.000

```

and the other CID I could not resolve at all

**Comment by AnilChinchawale** [comment]
@ligi kindly review again, the image size has been updated.

**Comment by ligi** [comment]
that fixes QmeRq7pabiJE2n1xU3Y5Mb4TZSX9kQ74x7a3P2Z4PqcMRX - but I am still having troubles resolving QmPzVFs16GwaD8LAcGFLCNXzEK8BHFKNXeM3nmBpnq9xy3

**Comment by AnilChinchawale** [comment]
Updated image QmPzVFs16GwaD8LAcGFLCNXzEK8BHFKNXeM3nmBpnq9xy3 size at [0ca630c](https://github.com/ethereum-lists/chains/pull/1374/commits/0ca630cbf7362466b5ed62c46f2ae0f104c18a86) commit , can you check now


Screenshot 2022-07-20 at 8 38 43 AM

**Review by AnilChinchawale — COMMENTED** [review]
Changes has been updated , kindly review again.

**Review by AnilChinchawale — COMMENTED** [review]
@ligi changes have been done, Kindly review it.

**Pull request closed without merging**
