### PR TITLE
fix: update eip155-3636 and botanix.json

### PR DESCRIPTION
**Pull request by scottmillner**
more info @ [botanix](https://botanixlabs.xyz)

updating testnet entry and icon

### CODE REVIEW

**Comment by ligi** [comment]
"We've forked Ethereum and put it on top of Bitcoin, combining the security of Bitcoin with the versatility of Ethereum." WTF - how stupid is this - can't ya let Bitcoin just die?

**Comment by ligi** [comment]
will still merge it after you fixed the CI errors like: " RPC chainId (444) does not match chainId from json (3636)" (which kinda also shows you should not run a chain)

**Comment by nnnnnnsssss** [comment]
Merge into_//_

**Comment by scottmillner** [comment]
> will still merge it after you fixed the CI errors like: " RPC chainId (444) does not match chainId from json (3636)" (which kinda also shows you should not run a chain)


CI problems fixed

**Review by ligi — APPROVED** [review]

**Comment by nnnnnnsssss** [comment]
Okay

**Pull request merged**
