### PR TITLE
CAGA Ankara testnet

### PR DESCRIPTION
**Pull request by cagacryptoAlexey**
CAGA crypto Ankara testnet

### CODE REVIEW

**Review by melissamforbs — APPROVED** [review]

**Comment by cagacryptoAlexey** [comment]
@melissamforbs @ligi hello, could you check?

**Comment by cagacryptoAlexey** [comment]
@ligi hello, what happend with job?
https://github.com/ethereum-lists/chains/actions/runs/8279786313/job/22654915656
i don't understand where i have to fix

**Comment by cagacryptoAlexey** [comment]
@melissamforbs @ligi hello, when it will be merged?

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by silverstr89** [comment]
@ligi thank you! added pretier

**Comment by cagacryptoAlexey** [comment]
@ligi thank you! added pretier

**Review by ligi — APPROVED** [review]

**Pull request merged**
