### PR TITLE
Add Taiko (Alpha-2 Testnet)

### PR DESCRIPTION
**Pull request by d1onys1us**
## checklist
- [x] verified build with `./gradlew run`
- [x] ran prettier over all files

## summary
[Taiko](https://twitter.com/taikoxyz) is a major zkRollup chain, this PR is adding the chain configuration so that users can add Taiko easily from tools like chainlist.wtf.

## question
The rpc for this chain configuration is not live *yet*, but it will be live very soon so wanted to get this PR in. Is that alright? We have another testnet chain configuration which is available now, but it will soon be deprecated.

I noticed some chain configurations had `"status": "incubating"`, I was thinking maybe this is for soon-to-launch testnets and then is later removed post-launch? Let me know if any changes need to be made.

### CODE REVIEW

**Comment by ligi** [comment]
"status": "incubating" is mainly to reserve chainIDs when the chain is not yet live. Frontends should filter this (unfortunately most do not yet do that)

**Comment by dantaik** [comment]
The rpc/was is configged Ann shall be available already.

**Comment by d1onys1us** [comment]
> "status": "incubating" is mainly to reserve chainIDs when the chain is not yet live. Frontends should filter this (unfortunately most do not yet do that)

thanks @ligi! I added the incubating status to the PR

**Comment by d1onys1us** [comment]
hey @ligi do you know what might be wrong here?
image

the first error I had was along the lines of "requested image size 512x512 but received 1001x1001, so I changed the dimensions. now it is appearing to not be able to pull the image, maybe?

**Comment by d1onys1us** [comment]
thanks for fixing it @ligi . is it possible to merge ASAP? testnet is up, and it would be nice to have this in our user guides :) no issues if not.

**Review by ligi — APPROVED** [review]

**Comment by robledo6** [comment]
P...

**Pull request merged**
