### PR TITLE
Update eip155-7001.json with the correct RPC

### PR DESCRIPTION
**Pull request by legendarykamal**
The Current RPC being used is incorrect as can be confirmed from the below ss and the discussion here https://discord.com/channels/834227967404146718/1126641259205898310

image

image

### CODE REVIEW

**Comment by legendarykamal** [comment]
@ligi can you please merge this PR ?

**Review by maddraddness — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
The other RPC still seems to work - why not just add the other one? Can't join the discord to see these messages.

**Comment by legendarykamal** [comment]
@ligi I got the new rpc from the ZetaChain Team and the other RPC doesnt work correctly , It shows Incorrect Balance amount .

To diffrentiate here are the ss 

1. with RPC - https://zetachain-athens-evm.blockpi.network/v1/rpc/public

image

2. with - https://explorer.athens.zetachain.com

image

**Comment by legendarykamal** [comment]
@ligi if everything looks good , can we merge this PR ?

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also provide me with the address in the examples of the screenshots

**Review by alokeutpal — APPROVED** [review]

**Comment by legendarykamal** [comment]
@ligi Have ran the `prettier check` in my recent commit , here's the address `0xCF8D2Da12A032b3f3EaDC686AB18551D8fD6c132` although its very general.

Another alternate method to check would be to get some test ZETA coins on Zeta network by joining the official Zeta discord.

**Pull request merged**
