### PR TITLE
Update Centrifuge

### PR DESCRIPTION
**Pull request by hieronx**
- Add icons for Centrifuge and Altair
- Adds more Centrifuge RPC endpoints
- Deprecates Algol

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Comment by ImdioR** [comment]
Hi! @ligi 
Could this PR be merged already?
Thanks!

**Comment by ImdioR** [comment]
Bumping this again 👀

**Comment by ligi** [comment]
?

image

**Comment by ImdioR** [comment]
> ?
> 
> image

Sorry, didn`t see my prev. comment. Will delete it now =)

**Review by Ramyromel — APPROVED** [review]
Thanks ❤️ 
I don't understand 😔 please help me 🙏

**Pull request merged**
