### PR TITLE
PR-EXP-1

### PR DESCRIPTION
**Pull request by royhodge**
to update Expanse Network Info

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks for the PR. But the explorer needs to adhere to a standard - ideally EIP-3091.
Also the icon currently does not point to the png data - but to a text encoded png - this will most likely break things upstream: https://gateway.ipfs.io/ipfs/Qme6iYA5Tu32hxJv6k7Ei9CyEF3a1epQPGCiSfzFwkcctq

**Comment by royhodge** [comment]
the explorer needs to adhere to a standard - ideally EIP-3091. --> https://expanscout.com/api-docs && i believe i fixed the logo issue

**Comment by ligi** [comment]
> the explorer needs to adhere to a standard - ideally EIP-3091. --> https://expanscout.com/api-docs && i believe i fixed the logo issue

unfortunately this is not a standard. Some people solve it with redirects. But really hope blockscout adheres natively to EIP-3091 soon.

**Comment by royhodge** [comment]
> > the explorer needs to adhere to a standard - ideally EIP-3091. --> https://expanscout.com/api-docs && i believe i fixed the logo issue
> 
> unfortunately this is not a standard. Some people solve it with redirects. But really hope blockscout adheres natively to EIP-3091 soon.

After I analyzed what's going on, The only difference from standard is (tokens) instead of (token) and (blocks) instead of (block). Not sure if it can be fixed easily in some configuration, the webserver is part of the application. I'll check if latest release fixed that or has some way to change or redirect paths.

**Pull request closed without merging**
