### PR TITLE
Changed ChainID from 75000 to 75001

### PR DESCRIPTION
**Pull request by 5050prop**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
sorry to protect from replay attacks you cannot do this - but u can deprecate one chain and add another.

**Comment by 5050prop** [comment]
> sorry to protect from replay attacks you cannot do this - but u can deprecate one chain and add another.

this network is mine and @SsNiPeR1, old chain was deprecated by us because we didn't have any archive nodes, so we created a new chain with a different id.

**Comment by 5050prop** [comment]
the old resincoin with chainid 75000 is no longer supported

**Comment by ligi** [comment]
you need to deprecate it in this PR and not just delete it

**Pull request closed without merging**
