### PR TITLE
Add Lisk test network

### PR DESCRIPTION
**Pull request by shuse2**
Add Lisk Sepolia Testnet

Sepolia Testnet = 4202

### CODE REVIEW

**Comment by shuse2** [comment]
Hello @ligi, we are preparing the release for Lisk. Could you run the CI?

**Comment by shuse2** [comment]
@ligi applied the formatting 🙇 now it should pass the CI

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by shuse2** [comment]
@ligi mainnet is under preparation now. I will create a separate PR for the mainnet 🙇

**Review by ligi — APPROVED** [review]

**Pull request merged**
