### PR TITLE
dev: add kakarot sepolia testnet

### PR DESCRIPTION
**Pull request by bajpai244**
Hello, I am Harsh, and I am a core developer at [kakarot](https://kakarot.org).

This PR adds Kakarot zkEVMs upcoming testnet to chain lists. Kakarot is type 2.5 zkEVM build on top of the cairo-vm using cairo language.

We will follow up later on with PRs to add RPCs, and Block explorers links, this PR is to get the initial steps going.

### CODE REVIEW

**Comment by bajpai244** [comment]
Interesting, I ran prettier on it this time, and there are still formatting issue, getting back to it and will ping u @ligi wen it works.

**Comment by bajpai244** [comment]
Hello @ligi , all tests for `./gradlew run` passes for me, is there something am I missing? I also ran prettier for formatting, not sure why we are still getting an error.

image

**Comment by bajpai244** [comment]
@ligi pushed another commit, looks like running prettier again changed some formatting, probably it should work now :0

**Comment by bajpai244** [comment]
Hello @ligi just a gentle bump for this :)

**Comment by bajpai244** [comment]
@ligi completed formatting of icon as well, I gues now the `validate_icons` should pass.

I guess we should put all tests being done on the CI in `./gradlew` run as well.

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
> I guess we should put all tests being done on the CI in ./gradlew run as well.

PRs welcome ^^^

**Pull request merged**
