### PR TITLE
Create eip155-197.json

### PR DESCRIPTION
**Pull request by NeutrinosChain**
Added Neutrinos Blockchain TestNet Information

### CODE REVIEW

**Comment by NeutrinosChain** [comment]
@ligi pls help to merge request

**Review by ligi — CHANGES_REQUESTED** [review]
The Icon neutrinos does not exist - was used in eip155-197.json

**Comment by NeutrinosChain** [comment]
Created different request for logo

**Comment by ligi** [comment]
it all needs to be in one PR

**Review by NeutrinosChain — COMMENTED** [review]
Added NeutrinosChain information

**Pull request closed without merging**
