### PR TITLE
Add FlowEVM networks

### PR DESCRIPTION
**Pull request by franklywatson**
https://developers.flow.com/evm/build/networks

```
jerome@vooter:~/repos/evm-chains$ gradle run
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :model
ksp-1.9.0-1.0.12 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0.
ksp-1.9.0-1.0.12 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0.
ksp-1.9.0-1.0.12 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0.
ksp-1.9.0-1.0.12 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0.
w: `KotlinCompilation.source(KotlinSourceSet)` method is deprecated
and will be removed in upcoming Kotlin releases.

See https://kotl.in/compilation-source-deprecation for details.

w: `KotlinCompilation.source(KotlinSourceSet)` method is deprecated
and will be removed in upcoming Kotlin releases.

See https://kotl.in/compilation-source-deprecation for details.


BUILD SUCCESSFUL in 13s
8 actionable tasks: 3 executed, 5 up-to-date
```

### CODE REVIEW

**Comment by franklywatson** [comment]
@ligi could you please approve the workflows and mrege once green? Thanks

**Comment by franklywatson** [comment]
@ligi could we please get this merged? Thanks

**Comment by franklywatson** [comment]
Thanks for triggering the workflows @ligi - i updated to master and re-ran the gradle build. Can you please re-run

**Comment by refref1991** [comment]
Hello tabikide yapabilirim sadece 5 $ istiyorum bunu yapması çok kolay
ayrıca Türkçe biliyor musunuz bana Türkçe yazın

29 Şub 2024 Per 22:08 tarihinde j pimmel ***@***.***> şunu
yazdı:

**Comment by Zipitn** [comment]
> https://developers.flow.com/evm/build/networks
> 
> ```
> jerome@vooter:~/repos/evm-chains$ gradle run
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> > Configure project :model
> ksp-1.9.0-1.0.12 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0.
> ksp-1.9.0-1.0.12 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0.
> ksp-1.9.0-1.0.12 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0.
> ksp-1.9.0-1.0.12 is too old for kotlin-1.9.22. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.9.0.
> w: `KotlinCompilation.source(KotlinSourceSet)` method is deprecated
> and will be removed in upcoming Kotlin releases.
> 
> See https://kotl.in/compilation-source-deprecation for details.
> 
> w: `KotlinCompilation.source(KotlinSourceSet)` method is deprecated
> and will be removed in upcoming Kotlin releases.
> 
> See https://kotl.in/compilation-source-deprecation for details.
> 
> 
> BUILD SUCCESSFUL in 13s
> 8 actionable tasks: 3 executed, 5 up-to-date
> ```

>wait….
>walk ETA etc



>then resume funckionára

**Comment by Zipitn** [comment]
>updated chorej

**Review by ligi — APPROVED** [review]

**Review by Zipitn — COMMENTED** [review]
Update

**Review by Zipitn — COMMENTED** [review]
#[_rep_]()

**Pull request merged**
