### PR TITLE
add qitmeer networks

### PR DESCRIPTION
**Pull request by dindinw**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
the explorer need the standar field  it can be `none`

**Comment by dindinw** [comment]
@ligi the standard field added, thanks a lot.

**Comment by dindinw** [comment]
@ligi Hi ligi, could you help to review the changes again, thanks

**Review by ligi — CHANGES_REQUESTED** [review]
Native currency symbol must have less than 7 chars

**Comment by dindinw** [comment]
@ligi  Hi, ligi, the currency symbols are now less than 7 chars, Please review again. thanks.

**Comment by dindinw** [comment]
@ligi Hi, ligi, the slash on the end of the explorer url has been removed, Please review again. thanks.

**Comment by dindinw** [comment]
@ligi could you help to review the PR again. the `slash on the end` has been removed. otherwise the PR will be closed automatically

**Comment by dindinw** [comment]
This PR has activity actually, but keep waiting for the reviewer's response.

**Comment by bCoder778** [comment]
@ligi Can you point out where else there is a problem, please

**Comment by ligi** [comment]
chains exist

**Pull request closed without merging**
