### PR TITLE
Add MO Chain

### PR DESCRIPTION
**Pull request by mochainapp**
@ligi updated with icon. Sorry for the delay

### CODE REVIEW

**Review by mochainapp — COMMENTED** [review]
@ligi file name issue, *eip155. now should be good to go.

thank you for your support

**Review by mochainapp — COMMENTED** [review]
all formats seem to be correct, icon as well accessible on ipfs. any help is appreciated @ligi

**Comment by chris6090** [comment]
kriseng83@gmail.com

**Review by mochainapp — COMMENTED** [review]
@ligi changed information on mainnet json file. now should work.

**Comment by mochainapp** [comment]
@ligi again please when you can

**Comment by mochainapp** [comment]
@ligi standard gave an issue, now its fixed. merge when you can. 💯

**Review by ligi — APPROVED** [review]

**Pull request merged**
