### PR TITLE
 old rpc stoped, commit new rpc

### PR DESCRIPTION
**Pull request by newblockgen**
old rpc stoped, commit new rpc

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
You cannot change the chainID - you need to deprecate the old one and create a new one - otherwise it opens the door to replay attacks

**Comment by newblockgen** [comment]
> You cannot change the chainID - you need to deprecate the old one and create a new one - otherwise it opens the door to replay attacks

How to deprecate the old one, Is there a step-by-step tutorial for reference?

**Review by newblockgen — COMMENTED** [review]
deprecated old chain

**Review by newblockgen — COMMENTED** [review]
deprecated old chain ,commit new chain

**Review by alokeutpal — APPROVED** [review]
Y

**Review by Samer26886 — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `ICPLAZA` more than once
	at org.ethereum.lists.chains.MainKt.parseWithMoshi(Main.kt:511)
	at org.ethereum.lists.chains.MainKt.checkChain(Main.kt:438)
	at org.ethereum.lists.chains.MainKt.doChecks(Main.kt:1[20](https://github.com/ethereum-lists/chains/actions/runs/5752987873/job/15595208994?pr=2972#step:5:21))
	at org.ethereum.lists.chains.MainKt.main(Main.kt:43)

**Comment by Samer26886** [comment]
[x] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:

**Comment by Samer26886** [comment]
Does anyone deal with the last problem?

**Pull request closed without merging**
