### PR TITLE
Deprecate Piccadilly (Thames) testnet 65100000

### PR DESCRIPTION
**Pull request by flofrie**

### CODE REVIEW

**Comment by flofrie** [comment]
@ligi , this fails because the RPC endpoints referenced in this file are by now already on a different Chain, with different ChainID; however, we should really be able to make the change to deprecate the network. We need your help please, on how to do that.

**Review by ligi — CHANGES_REQUESTED** [review]
feels kinda obvious: remove the RPC ..

**Comment by flofrie** [comment]
I tried that, _obvioulsly_ ;-) ... but the JSON check fails.

**Comment by ligi** [comment]
just make the array empty

**Pull request closed without merging**
