### PR TITLE
feat: add holesky

### PR DESCRIPTION
**Pull request by barnabasbusa**

### CODE REVIEW

**Comment by ligi** [comment]
Guess I should merge after this:
image
?

**Comment by barnabasbusa** [comment]
Do you need to have the explorer/rpc up before it gets merged? 
Got an open PR right now to set the ChainID in the eth-clients repo. 
https://github.com/eth-clients/holesky/pull/18

**Comment by ligi** [comment]
only for untrusted parties (so not you) where I need to verify the explorer is really EIP3091 compatible.
but please add the status incubating flag and remove draft state so I can merge

**Comment by pk910** [comment]
Hahaha, I love that you've guessed the URL for my faucet instance 😄
Can confirm the URL will be correct and will be up for the genesis 👍

**Pull request merged**
