### PR TITLE
update Ancient8 Testnet with new RPC

### PR DESCRIPTION
**Pull request by cjtoolseram**

### CODE REVIEW

**Comment by cjtoolseram** [comment]
@ligi changes made, marked old chain as deprecated.

**Review by cjtoolseram — COMMENTED** [review]
changed old names and shortnames and added status to deprecated

**Review by cjtoolseram — COMMENTED** [review]
@ligi are the changes okay?

**Comment by cjtoolseram** [comment]
> you cannot delete chains - only mark them deprecated

changes done

**Comment by 0xtrou** [comment]
@ligi hey can you take a look?

**Review by ligi — APPROVED** [review]

**Pull request merged**
