### PR TITLE
Add Electroneum Mainnet and Testnet

### PR DESCRIPTION
**Pull request by chrischarlesharrison**
Newly registering both the Electroneum Mainnet and Testnet chains

### CODE REVIEW

**Review by iambary44 — APPROVED** [review]

**Comment by chrischarlesharrison** [comment]
Despite the CI, I can `ipfs get` the icon fine when it's pinned on my local node and my node is up. Is it ok to merge?

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time (that it works locally for you does not mean it works for me or another node in the network) - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by chrischarlesharrison** [comment]
That's done. I meant I could `ipfs get` it from my node or others, if my local node pinned it.

**Comment by nnnnnnsssss** [comment]
Recheck

**Review by ligi — APPROVED** [review]

**Review by Aholaone360 — CHANGES_REQUESTED** [review]
Done

**Review by Aholaone360 — APPROVED** [review]
Fixed

**Pull request merged**
