### PR TITLE
Add Argochain (Chain ID: 1299) 

### PR DESCRIPTION
**Pull request by mitun567**
This PR adds Argochain (Chain ID: 1299) with RPC URLs, an EIP-3091 compliant block explorer (Argochain Scanner), and IPFS-hosted icons. The chain uses AGC as its native currency with 18 decimals.

### CODE REVIEW

**Comment by mitun567** [comment]
HI, @ligi , the file had the case sensitivity issue which has been resolved and user prettifier for formatting. Looking forward to your review.

**Review by ligi — CHANGES_REQUESTED** [review]
explorer is not EIP3091 compatible

**Comment by mitun567** [comment]
Thanks @ligi the scanner has been updated.
For Trx Hash: https://scanner.argoscan.net/tx/{transaction hash}
For Block: https://scanner.argoscan.net/block/{block number}
For Address: https://scanner.argoscan.net/address/{Account Address}
For Token: https://scanner.argoscan.net/token/{Token Address}
We are making progress with the scanner to follow the standard. Please let me know for any update.
Thanks.

**Review by ligi — APPROVED** [review]

**Review by DashaBochkar — COMMENTED** [review]
Thanks

**Pull request merged**
