### PR TITLE
Add BitkubChain mainnet and testnet

### PR DESCRIPTION
**Pull request by isman-usoh**
- https://www.bitkubchain.com/
- add BitkubChain mainnet `chainId=96`
- add BitkubChain testnet `chainId=25925`

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The explorers do not seem to be EIP3091 compatible - e.g.
https://testnet.bkcscan.com/block/2314228
fails 
and only 
https://testnet.bkcscan.com/blocks/2314228 works

**Comment by isman-usoh** [comment]
> The explorers do not seem to be EIP3091 compatible - e.g.
> https://testnet.bkcscan.com/block/2314228
> fails
> and only
> https://testnet.bkcscan.com/blocks/2314228 works

I fixed it

**Review by ligi — CHANGES_REQUESTED** [review]
You need to remove the whole explorer section - we do not accept explorers that do not adhere to any standard

**Review by ligi — CHANGES_REQUESTED** [review]
The short name must be uniq

**Pull request closed without merging**
