### PR TITLE
Create eip155-1234567.json

### PR DESCRIPTION
**Pull request by quidiligr**
Create chain for Sharcle Coin

### CODE REVIEW

**Comment by Srikarrao1** [comment]
@quidiligr Please let me know if I can help you in adding your chain in Chainlist.

**Comment by quidiligr** [comment]
Yes please

Thanks,
Rom

**Comment by Srikarrao1** [comment]
@quidiligr I might charge a bit after successful addition to Chainlist, please let me know if you're okay with this.

I see the build, icon and json formats are incorrect.

**Comment by quidiligr** [comment]
I can fix myself but I’ve been busy. How much do you charge?

**Comment by Srikarrao1** [comment]
Sure, there're some issues with the formatting, I won't charge much 50 bucks is what I am asking.

**Comment by quidiligr** [comment]
Fix it first. If it works then I’ll  pay you via zelle, cash app or Venmo.

**Comment by Srikarrao1** [comment]
Do you have Discord or any other communication channel so that we can be in touch, rather than a public forum which might effect this merge?

**Comment by quidiligr** [comment]
WhatsApp +14247812417

**Comment by Srikarrao1** [comment]
I have pinged you in the whatsapp, please delete all these messages

**Pull request closed without merging**
