### PR TITLE
Update DreyerX Icon

### PR DESCRIPTION
**Pull request by dreyerx**
I have tried to display the icon on the chainlist.org page, but to no avail. This is likely because the code to access the file is incorrect.

If this doesn't work, is there another way to display the icon on the chainlist.org page?

### CODE REVIEW

**Comment by dreyerx** [comment]
Hey @ligi, can you review this pull request?

**Comment by billalxcode** [comment]
Please accept this pull request @ligi

**Review by ligi — CHANGES_REQUESTED** [review]
The old code seems to be correct:
ipfs add 
> _data/iconsDownload/QmTGjVbiSdHYhjzpeqzY6fGwGiLQuEa2hW7irD75sUSx9e
added QmTGjVbiSdHYhjzpeqzY6fGwGiLQuEa2hW7irD75sUSx9e QmTGjVbiSdHYhjzpeqzY6fGwGiLQuEa2hW7irD75sUSx9e

also the icon is shown:

image

**Comment by billalxcode** [comment]
But it doesn't work if I check it on [chainlist.org](https://chainlist.org)

image

**Comment by ligi** [comment]
then they should fix that

**Pull request closed without merging**
