### PR TITLE
Add Ternoa zkEvm testnet network

### PR DESCRIPTION
**Pull request by hitesh-zeeve**

### CODE REVIEW

**Comment by hitesh-zeeve** [comment]
Requesting a new review of this MR.

**Comment by hitesh-zeeve** [comment]
The MR is up to date with the master branch

**Comment by hitesh-zeeve** [comment]
All builds passed

**Comment by hitesh-zeeve** [comment]
All builds passed now :grinning:

**Review by ligi — APPROVED** [review]

**Pull request merged**
