### PR TITLE
Create eip155-111.json

### PR DESCRIPTION
**Pull request by etherlite-org**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Needs to have the PR with the icon fixed and merged before this one can be merged

**Comment by etherlite-org** [comment]
Icon fixed on commit 2fab17cab36be790301b4c1b70a4e6ee371e3d31

**Comment by ligi** [comment]
Oh sorry - missed the Icon PR - merged now. Unfortunately the explorer is a blocker. It does not adhere to a standard - but it must - ideally EIP3091.

**Comment by etherlite-org** [comment]
As requested we have removed the explorer section on commit 253246c

**Review by ligi — APPROVED** [review]

**Pull request merged**
