### PR TITLE
Adding Eclipse Testnet 72172

### PR DESCRIPTION
**Pull request by connorch**

### CODE REVIEW

**Comment by connorch** [comment]
@ligi Can you please take a look at this when you have a chance?  Thank you :)

**Comment by connorch** [comment]
Also, would it be possible to approve the [@ava-labs/](https://github.com/ava-labs/chains/tree/master) repo for workflow runs?  We have and will continue to submit several PRs to this repo 😄

**Comment by connorch** [comment]
Recreating this PR in hopes that it will get better visibility
https://github.com/ethereum-lists/chains/pull/4119

**Comment by Zipitn** [comment]
[takis](nitro);_scheme+alt
Set route for concept_

**Pull request closed without merging**
