### PR TITLE
added mainnet and testnet

### PR DESCRIPTION
**Pull request by Kyoto-Blockchain**
Secure chain ids for Kyoto Blockchain

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
don't do "" - only do []

also if you chain is incubating - add `"status":"incubating"`

**Review by robledo6 — COMMENTED** [review]
Gracias es

**Comment by Kyoto-Blockchain** [comment]
@ligi Submitted the requested changes.

**Comment by ligi** [comment]
also remove the explorers with empty URLs

**Comment by ligi** [comment]
Fix CI errors

**Pull request closed without merging**
