### PR TITLE
Fix Etica Logo ipfs

### PR DESCRIPTION
**Pull request by kevin-wad**
Update etica.json

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The content of the CID is not an image but a directory

**Comment by kevin-wad** [comment]
apparently my ipfs uploader uploads only this way, can't find a way to upload just the image. If you have an ipfs uploader that uploads doesn't upload files into folders please let me know. Or if you know maybe you can upload the image and share the ipfs link, it would be very appreciated. Thank you very much for help and support

**Comment by kevin-wad** [comment]
I found a solution, thanks!

**Comment by kevin-wad** [comment]
> The content of the CID is not an image but a directory

I just realised that you had not given me a random Qm hash but the right ipfs hash of the logo png. Do you know why the logo is not showing up in the chainlist.org page although it's correct ipfs hash? Should it be set on another field than icon: to show on main page? Thanks

**Pull request closed without merging**
