### PR TITLE
Add icon information for the BTTC mainnet and BTTC 1029 testnet information.

### PR DESCRIPTION
**Pull request by falcon202110**
Update BTTC Networks:
Add icon information for 199 main network.
Add chain information for 1029 test network.
Deprecate 1028 test network.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]

**Comment by ligi** [comment]
image

**Comment by falcon202110** [comment]
> image

Hello, the scan for the BTTC testnet is https://testnet.bttcscan.com/, and it is accessible.

**Review by Missjones2 — COMMENTED** [review]
Merge

**Review by ligi — APPROVED** [review]

**Pull request merged**
