### PR TITLE
Create autobahn.json

### PR DESCRIPTION
**Pull request by defido**
add IPFS logo for autobahn

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot resolve this IPFS hash - is it pinned somewhere?

**Comment by defido** [comment]
> I cannot resolve this IPFS hash - is it pinned somewhere?

I will fix that now

**Comment by defido** [comment]
https://cloudflare-ipfs.com/ipfs/QmZP19pbqTco4vaP9siduLWP8pdYArFK3onfR55tvjr12s?__cf_chl_tk=rAq2wDZVv39pXT3K9kfFfmeOP5AMGe18yvErqx5TwO8-1648619770-0-gaNycGzNCBE

Fixed and a link to show it above

> I cannot resolve this IPFS hash - is it pinned somewhere?

**Comment by ligi** [comment]
hm - still does not load for me

**Comment by defido** [comment]
> hm - still does not load for me

https://api.ipfsbrowser.com/ipfs/get.php?hash=QmZP19pbqTco4vaP9siduLWP8pdYArFK3onfR55tvjr12s

Here's the same hash on a different online viewer.

**Comment by ligi** [comment]
I do not really care for online viewers - I cannot resolve it via `ipfs get` - that is what counts

**Comment by ligi** [comment]
and I could just `ipfs get` a CID from another PR - not sure what is special with yours - but it needs to work before merging

**Comment by defido** [comment]
> and I could just `ipfs get` a CID from another PR - not sure what is special with yours - but it needs to work before merging

Give me a moment, I'll figure out why it's special :D

**Comment by defido** [comment]
> and I could just `ipfs get` a CID from another PR - not sure what is special with yours - but it needs to work before merging

Getting resolved on everyonline viewer and the local IPFS desktop client

https://ipfs.io/ipfs/QmZP19pbqTco4vaP9siduLWP8pdYArFK3onfR55tvjr12s?filename=autobahn_network_logo_icon_circle_standard.png
Screen Shot 2022-03-30 at 4 13 56 pm
Screen Shot 2022-03-30 at 4 14 04 pm

**Comment by ligi** [comment]
now after a long time it loaded - must have been a weird IPFS peering thing - but the sizes do not match:

```
✗ ~ identify QmZP19pbqTco4vaP9siduLWP8pdYArFK3onfR55tvjr12s             08:19:55
QmZP19pbqTco4vaP9siduLWP8pdYArFK3onfR55tvjr12s PNG 489x489 489x489+0+0 8-bit sRGB 17158B 0.000u 0:00.000

```

**Comment by defido** [comment]
> 489x489

I'll clean that up to 489x489

Not sure why it took so long :D

**Comment by defido** [comment]
Size has been fixed

**Review by ligi — APPROVED** [review]

**Comment by defido** [comment]
Not sure what that build fail is about or if I need to do anything?

**Pull request merged**
