### PR TITLE
New RPCs and icon for Bitgert Chain

### PR DESCRIPTION
**Pull request by Brisepad**

### CODE REVIEW

**Review by ligi — COMMENTED** [review]
Where did you pin the CID for the icon? I cannot resolve it

**Comment by Brisepad** [comment]
> Where did you pin the CID for the icon? I cannot resolve it

The CID is QmY3vKe1rG9AyHSGH1ouP3ER3EVUZRtRrFbFZEfEpMSd4V. It is in the icons repo

**Comment by Brisepad** [comment]
> > Where did you pin the CID for the icon? I cannot resolve it
> 
> The CID is QmY3vKe1rG9AyHSGH1ouP3ER3EVUZRtRrFbFZEfEpMSd4V. It is in the icons repo

It is part of the commit

**Comment by ligi** [comment]
Seems I cannot reach your local node - can you pin it somewhere else?

**Comment by Brisepad** [comment]
> Seems I cannot reach your local node - can you pin it somewhere else?

Kindly have a look now

**Review by ligi — APPROVED** [review]

**Pull request merged**
