### PR TITLE
Add Oasys Testnet Network

### PR DESCRIPTION
**Pull request by sunil301295**
Add Oasys Testnet Network

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Comment by sunil301295** [comment]
@ligi  I noticed that the PR is merged but the chain still isn't listed on the site. Would it take some time to update?

**Comment by ligi** [comment]
Its there: 

image

**Comment by sunil301295** [comment]
Yes but it's Mainnet. My PR was for Testnet.

https://github.com/ethereum-lists/chains/pull/3939

**Comment by sunil301295** [comment]
@ligi

**Comment by ligi** [comment]
you submitted this one to the wrong folder

**Pull request merged**
