### PR TITLE
DPU chain

### PR DESCRIPTION
**Pull request by topten1222**

### CODE REVIEW

**Comment by topten1222** [comment]
@ligi no icon in json dpu chain

**Comment by topten1222** [comment]
please how to fix ? @ligi

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by topten1222** [comment]
@ligi update format json. please review and approve request merage. thank you

**Comment by topten1222** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

Update Thanks.

**Review by ligi — APPROVED** [review]

**Pull request merged**
