### PR TITLE
add: OMOCHI TESTNET & MAINNET

### PR DESCRIPTION
**Pull request by 0xwata**
add: OMOCHI TESTNET & MAINNET

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by 0xwata** [comment]
@ligi 
Omochi chain is a private chain, and its explorer is only accessible to those with the necessary permissions. If you have access, the page will look like the one below.
スクリーンショット 2024-05-20 20 49 39

**Comment by ligi** [comment]
it's not EIP3091 compatible then

**Comment by ligi** [comment]
and WTF - just use a database in this case - no need for a blockchain ^^

**Comment by 0xwata** [comment]
Okay, Then I will close this PR. Thank you for your feedback!

**Pull request closed without merging**
