### PR TITLE
Add Sorian Testnet chain details

### PR DESCRIPTION
**Pull request by sorian-coin**
This pull request adds the Sorian Testnet chain to the Chainlist repository. The details of the chain are as follows:

Network Name: Sorian Testnet Network
Chain Name: Sorian Testnet Chain
Coin Name: Sorian Testnet
Symbol: tSOR
Decimals: 18
RPC URLs:
https://testnet-rpc.sorian.io/
https://testnet.rpc.sorian.io/
Chain ID: 210209
Explorer URL: https://testnet-scan.sorian.io
Info URL: https://mint.sorian.io/
Token Logo: ipfs://QmZmrcLYFtPZb36MZ1DyQpR7Lw8CWPP7x3Bx2anCjVWfMR

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Screenshot from 2024-10-15 02-04-32

**Comment by sorian-coin** [comment]
it has updated , please check now

**Comment by sorian-coin** [comment]
https://testnet-scan.sorian.io/

check this it is  on live now with dev mode. Thank you.

**Review by ligi — CHANGES_REQUESTED** [review]
image

can't really veriy the explorer without blocks ;)

**Comment by sorian-coin** [comment]
I have removed for explorers details and will update after completed. now check all are okay or not. Please

**Comment by sorian-coin** [comment]
Ligi please check . i have removed the exploers details

**Review by ligi — APPROVED** [review]

**Pull request merged**
