### PR TITLE
Create pnet.json

### PR DESCRIPTION
**Pull request by DGSInfra**
add pnet icon

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Please stop opening new PRs until you fixed your old ones

**Comment by DGSInfra** [comment]
> Please stop opening new PRs until you fixed your old ones

sorry, Ligi can u help me with this PR please
https://ipfs.io/ipfs/QmRiAUu3xV5uiX6Nk1iXD5w6qjki5ugGFETRVavzJ2h5QF?filename=Pnetgood.png 
is this secure and can be use?
any lead for me to make this right?

best regard

**Comment by DGSInfra** [comment]
> > Please stop opening new PRs until you fixed your old ones
> 
> sorry, Ligi can u help me with this PR please https://ipfs.io/ipfs/QmRiAUu3xV5uiX6Nk1iXD5w6qjki5ugGFETRVavzJ2h5QF?filename=Pnetgood.png is this secure and can be use? any lead for me to make this right?
> 
> best regard

ps. the file have been minted already in NFT

**Review by ligi — CHANGES_REQUESTED** [review]
URL must start with ipfs:// and be a plain IPFS link / CID

**Comment by DGSInfra** [comment]
i once try but still failed ipfs://QmRiAUu3xV5uiX6Nk1iXD5w6qjki5ugGFETRVavzJ2h5QF
any clues? on my ipfs node?

**Review by ligi — CHANGES_REQUESTED** [review]
The icon is not used - please just click details on the error and do not waste my time relaying this information to you

**Comment by DGSInfra** [comment]
> The icon is not used - please just click details on the error and do not waste my time relaying this information to you

thank you very much

**Pull request closed without merging**
