### PR TITLE
Add a network green ledger 

### PR DESCRIPTION
**Pull request by ojhasujeet123**

### CODE REVIEW

**Comment by ojhasujeet123** [comment]
Please verify it as soon as possible .

**Comment by ojhasujeet123** [comment]
why its not checkk , pls explain a reason.nd how to resolve this issue.

**Comment by ojhasujeet123** [comment]
how much time it will take to approve all checks .

**Comment by ojhasujeet123** [comment]
Now pls check .

**Comment by ojhasujeet123** [comment]
verify this as soon as possible

**Comment by ojhasujeet123** [comment]
Any update regarding the last commit ?

**Comment by ojhasujeet123** [comment]
check the latest commit and verify

**Comment by Srikarrao1** [comment]
@ojhasujeet123 Please let me know if I can help you in merging this request

**Pull request closed without merging**
