### PR TITLE
Add Cascadia testnet network data + icon

### PR DESCRIPTION
**Pull request by msvstj**
Hello, I am creating this PR to add Cascadia Testnet Network (ID: 6102)

Local checks:

- **Check JSON Schema / validate_json (push) Successful in 8s** [Details](https://github.com/protofire/chains/actions/runs/5424340607/jobs/9863562770)
- **Run prettier / prettier (push) Successful in 27s** [Details](https://github.com/protofire/chains/actions/runs/5424340613/jobs/9863562771)

Gradle build result:
```
BUILD SUCCESSFUL in 1s
14 actionable tasks: 14 up-to-date
```

Thank you!

### CODE REVIEW

**Comment by Ayid7676** [comment]
Hello, I am creating this PR to add Cascadia Testnet Network (ID: 6102)

Local checks:

Check JSON Schema / validate_json (push) Successful in 8s [Details](https://github.com/protofire/chains/actions/runs/5380583848/jobs/9763504612)
Run prettier / prettier (push) Successful in 27s [Details](https://github.com/protofire/chains/actions/runs/5380583853/jobs/9763504613)
Gradle build result:

BUILD SUCCESSFUL in 1s
14 actionable tasks: 14 up-to-date
Thank you!

**Review by julioAk47 — APPROVED** [review]

**Review by 357SANDIIIP — APPROVED** [review]

**Comment by msvstj** [comment]
Icon is now accessible via cloudflare:
 https://cloudflare-ipfs.com/ipfs/QmQHv7Qgoz42sVWqS7tqiWR5X67oNkq3yFFbLBr6QLeHGr

**Comment by msvstj** [comment]
Hello, @ligi . Is it possible to support this PR once more with the check run? 
I believe the icon issue is solved and now reachable with ipfs get.
All the other checks have passed.

Thank you for your time.

**Review by ligi — APPROVED** [review]

**Review by alokeutpal — APPROVED** [review]

**Comment by Ayid7676** [comment]
Duplicate of #

**Comment by Ayid7676** [comment]
[ligi](https://github.com/ligi) . Is it possible to support this PR once more with the check run?
I believe the icon issue is solved and now reachable with ipfs get.
All the other checks have passed.

Thank you for your time.
Duplicate of #

**Pull request merged**
