### PR TITLE
update# add orange chain testnet

### PR DESCRIPTION
**Pull request by cppfuns**
add orange chain testnet

### CODE REVIEW

**Comment by cppfuns** [comment]
@ligi Please help me merge it~  
Thank you for the convenience this project brings to the Ethereum ecosystem

**Comment by ligi** [comment]
PoW based chains have minimal priority - will be merged - but can take a while. If you want to speed it up pay funds to lists.eth

**Comment by cppfuns** [comment]
> PoW based chains have minimal priority - will be merged - but can take a while. If you want to speed it up pay funds to lists.eth

It is developed based on OP-Stack, not a POW chain

**Comment by ligi** [comment]
it builds on top of a PoW chain - so it is PoW based - will be merged - but will take time

**Pull request merged**
