### PR TITLE
Update eip155-39815.json

### PR DESCRIPTION
**Pull request by ohonetwork**
Logo doesn't show up at https://chainlist.org.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
If you want to do this - remove the ohoscan icon definition also

**Comment by Oluwarichee** [comment]
Thanks you my savior let there be light forever ♾️ my creator 👏👑🫅sorry
my lord people hurt because they never believed me when I said you live and
forever with us My lord Jesus Christ

**Comment by Oluwarichee** [comment]
Where’re you living in my creation of the world and and praise your name god

**Comment by ohonetwork** [comment]
> If you want to do this - remove the ohoscan icon definition also

I have created a pull request to remove ohoscan icon. Thanks

**Review by leop6140 — APPROVED** [review]
Leop6140

**Pull request closed without merging**
