### PR TITLE
Fix status of Taiko Katla Testnet 

### PR DESCRIPTION
**Pull request by swarna1101**
Taiko Katla Testnet is no longer active, so changed the status from `active` to `deprecated`

### CODE REVIEW

**Comment by swarna1101** [comment]
@ligi can you pls take a look and approve this PR

**Comment by swarna1101** [comment]
@ligi Katla is still visible here: https://chainid.network/chain/167008/
can you pls remove it, as soon as possible. I thought this PR when closed has removed it

**Review by ligi — CHANGES_REQUESTED** [review]
remove explorers and RPCs

**Comment by swarna1101** [comment]
> remove explorers and RPCs

I have removed it in the recent commit, pls check and do the needful by removing Katla

**Review by ligi — APPROVED** [review]

**Pull request merged**
