### PR TITLE
Adds Sei Pacific-1 mainnet

### PR DESCRIPTION
**Pull request by cordt-sei**
Add Sei Mainnet and associated logo image

### CODE REVIEW

**Comment by cordt-sei** [comment]
Just realized the IPFS link is not working, will re-open when fixed soon

**Comment by cordt-sei** [comment]
Checks passed on my end, sorry for the runaround.

image

**Comment by cordt-sei** [comment]
Please review @ligi, thank you.

**Comment by abs3ntdev** [comment]
hello we are waiting on this PR to get viem updated https://github.com/wevm/viem/pull/2327 is there anything to be completed to get this merged?

**Comment by abs3ntdev** [comment]
@ligi can this be reviewed/merged we are blocked on viem and we cant merge into viem until this is merged.

**Comment by cordt-sei** [comment]
Fixed filename, please re-run checks. @ligi

**Comment by channing-magiceden** [comment]
@ligi any chance to take a look?

**Pull request merged**
