### PR TITLE
Add GroveChain Mainnet

### PR DESCRIPTION
**Pull request by b0d1k**
Please add GroveChain Mainnet

### CODE REVIEW

**Comment by romanR1H2** [comment]
Iruu

**Review by romanR1H2 — COMMENTED** [review]
R1H2

**Review by romanR1H2 — APPROVED** [review]

**Comment by b0d1k** [comment]
@romanR1H2  we made some changes to icons and updated files, can you please check

**Review by sanohj — CHANGES_REQUESTED** [review]
#2740

**Review by romanR1H2 — APPROVED** [review]

**Pull request closed without merging**
