### PR TITLE
Add Aternos

### PR DESCRIPTION
**Pull request by adapt7**
Aternos: Layer 1 network added.

Read more: https://aternoschain.com/

### CODE REVIEW

**Review by adapt7 — COMMENTED** [review]
Please review fix for explorer URL.

**Review by alanaladd21 — APPROVED** [review]

**Comment by adapt7** [comment]
Can you please provide info why validate_formatting check fails? There is no word about the reason. Thank you.

**Comment by adapt7** [comment]
Hi @alanaladd21 @ligi could you please point me what's wrong with the validate_formatting please?

**Comment by adapt7** [comment]
Please review fix for JSON formatting.

**Review by ligi — APPROVED** [review]

**Pull request merged**
