### PR TITLE
Adds mande chain

### PR DESCRIPTION
**Pull request by prtk418**

### CODE REVIEW

**Comment by prtk418** [comment]
@ligi please review and merge

**Comment by prtk418** [comment]
@ligi seems like icon_check job failed incorrectly. please check

**Comment by ligi** [comment]
seems there is a reason:

image

**Comment by prtk418** [comment]
> seems there is a reason:
> 
> image

Ah okay, what's the recommended way to upload to ipfs ?

**Review by ligi — CHANGES_REQUESTED** [review]
Before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by prtk418** [comment]
> Before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

What would help you save costly time is. Update README with:
- Suggested way to upload to IPFS
- A step to put icon inside iconsDownload folder with CID as title.
Would love to raise a PR for this once I have some time. Cheers!

**Comment by prtk418** [comment]
Hi @ligi the checks are passing now, when can we merge ? Didn't update master to this branch yet because not sure if it will reset the workflow build status

**Review by ligi — APPROVED** [review]

**Pull request merged**
