### PR TITLE
Reserving chain IDs for Portal Fantasy

### PR DESCRIPTION
**Pull request by Zaggo34**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
If it is not yet existing add a `status` field with value `incubating`

**Comment by Zaggo34** [comment]
@ligi Thanks! Updated the PR with the requested change.

**Comment by Zaggo34** [comment]
> If it is not yet existing add a `status` field with value `incubating`

Hey @ligi I've done this and awaiting your review. Thanks

**Comment by ligi** [comment]
where did you pin QmeMa6aw3ebUKJdGgbzDgcVtggzp7cQdfSrmzMYmnt5ywc? I cannot resolve it

**Review by ligi — APPROVED** [review]

**Pull request merged**
