### PR TITLE
Update Flare related chains

### PR DESCRIPTION
**Pull request by RareData**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
where did you pin the CIDs? I cannot resolve them

**Comment by RareData** [comment]
> where did you pin the CIDs? I cannot resolve them

Pinata. I just checked again and they all resolve. Maybe they hadn't yet propagated.

**Comment by RareData** [comment]
Hey @ligi can you recheck?

**Review by ligi — CHANGES_REQUESTED** [review]
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

**Comment by RareData** [comment]
> tl;dr: it is now required to put the binary icon into iconDownload
> 
> why: it was a PITA to always `ipfs get` in the review process - sometimes it takes _really long_ or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

Added in https://github.com/ethereum-lists/chains/pull/1710/commits/d8f080dcd30a0563e55539389eaac270f8de8d26

**Comment by RareData** [comment]
Adjusted

**Review by ligi — APPROVED** [review]

**Pull request merged**
