### PR TITLE
Add WrapTag Chain

### PR DESCRIPTION
**Pull request by bacoor-hb**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
please rename `_data/iconsDownload/QmajBejomc8yreVKP3CG15c6rasQpj7qzuF2JqLb6n2RHe.png `to `_data/iconsDownload/QmajBejomc8yreVKP3CG15c6rasQpj7qzuF2JqLb6n2RHe`

**Comment by bacoor-hb** [comment]
> please rename `_data/iconsDownload/QmajBejomc8yreVKP3CG15c6rasQpj7qzuF2JqLb6n2RHe.png `to `_data/iconsDownload/QmajBejomc8yreVKP3CG15c6rasQpj7qzuF2JqLb6n2RHe`

Thanks for your information, we renamed the file.

**Comment by aminhdev** [comment]
Rebased

**Pull request closed without merging**
