### PR TITLE
Add Krest network

### PR DESCRIPTION
**Pull request by neutrinoks**
Adding spec for Krest network with icon

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205267245821359

### CODE REVIEW

**Comment by neutrinoks** [comment]
Due to the github actions are checking for a matching EVM ChainID, we have do to our runtime-upgrade first. I hoped, it works the other way round... register an EVM ChainID, then fix it... Runtime-upgrade of our blockchain is scheduled for next week, so I will update this PR next week again :+1:

**Comment by ligi** [comment]
having it the other way around would mean we have wrong data - I do not think this would be good.

**Comment by neutrinoks** [comment]
> having it the other way around would mean we have wrong data - I do not think this would be good.

We will do our runtime upgrade on the beginning of next week, then the ID will fit and then I will update the last changes to get this finished :+1:

**Comment by neutrinoks** [comment]
@ligi I pushed a little too early, because I was expecting that the GitHub-actions usually take much more time :see_no_evil: sorry!!! Can you initiate the GitHub-actions again? Should work now...

**Pull request closed without merging**
