### PR TITLE
add FREN => FrenChain mainnet is here!

### PR DESCRIPTION
**Pull request by shopglobal**
Name: FrenChain
Symbol: FREN

[Website] => https://frenchain.app
[Explorer] => https://frenscan.io
[Source Code] => https://github.com/fren-chain/go-frenchain
[ERC20] => https://etherscan.io/address/0x8e14c88ab0644ef41bd7138ab91c0160d8c1583a

### CODE REVIEW

**Comment by shopglobal** [comment]
@ligi ready to merge

**Review by ligi — CHANGES_REQUESTED** [review]
name must be unique - but found `FRENCHAIN` more than once

**Comment by shopglobal** [comment]
Hey brother @ligi I got those changes requested and master merged here. 

Looking forward to merge. 
Thanks, [M](https://t.me/interchained)

**Review by ariel3112 — APPROVED** [review]

**Review by ligi — APPROVED** [review]

**Review by regalwright — APPROVED** [review]
It's been corrected

**Pull request merged**
