### PR TITLE
Shibarium changes

### PR DESCRIPTION
**Pull request by anonymus745**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Please fix CI errors

**Comment by Gurpreet745** [comment]
Can you please review the changes if there are any other changes required then please let me know and will do it. This is fixed for 719 and I have put my network on production.

**Comment by yardapen** [comment]
I'm trying to secure my devices some one is stealing my coin

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `SHIB` more than once

**Comment by navdeepgarg1** [comment]
Hey, @ligi can you check this MR and let us know if it can be get approved sooner.

**Comment by ligi** [comment]
no approval until CI errors are solve

**Comment by navdeepgarg1** [comment]
Hey, @ligi can you check this MR and let us know if it can be get approved sooner.

**Comment by ligi** [comment]
will not be approved as long as CI is not happy

**Comment by navdeepgarg1** [comment]
@ligi can you please let us know the issue that it is getting failed again

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by shadqat** [comment]
Nice

**Comment by anonymus745** [comment]
@ligi can you please check this request

**Comment by anonymus745** [comment]
Hi @ligi can you please check above MR

**Comment by navdeepgarg1** [comment]
Hi @ligi can you please check MR

**Comment by navdeepgarg1** [comment]
> ### All checks have passed
> 4 successful checks

**Review by ligi — APPROVED** [review]

**Pull request merged**
