### PR TITLE
add quarkchain chainids

### PR DESCRIPTION
**Pull request by ping-ke**
add quarkchain chainids
    mainnet: https://mainnet.quarkchain.io/ 
    devnet: https://devnet.quarkchain.io/

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I think the RPCs are wrong - they all point to the same
Also these are a lot of shards - will need to check with consumers - we need a way to fold here

**Review by l2ichshop2 — APPROVED** [review]

**Comment by ping-ke** [comment]
> I think the RPCs are wrong - they all point to the same
> Also these are a lot of shards - will need to check with consumers - we need a way to fold here

**Comment by ping-ke** [comment]
All shards rpc calls are implemented by calling root chain rpc, so they all fill in the same PRC.  is that work?
For "will need to check with consumers - we need a way to fold here", do you mean we need to create a folder like qkcchainids, under "_data/chains" and move all those files to that folder?

**Comment by ligi** [comment]
Not yet sure - how do you target the shards in the calls then? I can Imagine for transactions via EIP155 - but how does this work for other calls?

**Pull request closed without merging**
