### PR TITLE
Add Metis Sepolia chain

### PR DESCRIPTION
**Pull request by t0mcr8se**

### CODE REVIEW

**Comment by t0mcr8se** [comment]
Metis Goerli eip155-599 was deprecated with the deprecation of Goerli eip155-4, new metis testnet is metis-sepolia eip155-59902
https://docs.metis.io/dev/readme/connection-details

**Comment by 0x000hx** [comment]
lets goooo

**Comment by 0x000hx** [comment]
@ligi please review again

**Comment by 0x000hx** [comment]
@ligi please review

**Review by ligi — APPROVED** [review]

**Pull request merged**
