### PR TITLE
Add Symplexia Smart Chain

### PR DESCRIPTION
**Pull request by symplexialabs**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by symplexialabs** [comment]
I have put the icon in iconDownload as required. Thank you for your attention.

**Comment by symplexialabs** [comment]
> I have put the icon in iconDownload folder as required. Thank you for your attention.

**Comment by symplexialabs** [comment]
Once again has appeared the message error "Process completed with exit code 1" in the step "Run PR Checks / validate_formatting". I really don't know what's wrong with my configuration and the error message isn't very clear. I would really appreciate if anyone could give me some insight on how to solve this problem. Thanks in advance.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by symplexialabs** [comment]
> Please run the prettier to format your json according to the style

I've  run the prettier to format the json file according your suggestion, Thanks for your help.

**Comment by symplexialabs** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

I've run the prettier to format the json files according your suggestion, Thanks for your help.

**Pull request closed without merging**
