### PR TITLE
Add Ramestta Mainnet & Testnet

### PR DESCRIPTION
**Pull request by webSkg**

### CODE REVIEW

**Comment by webSkg** [comment]
> don't touch gradle files

Can you please elaborate , i have updated the branch please review and approve if all good , else explain the issue so that i can fix

**Comment by webSkg** [comment]
hey there , kindly verify and merge

**Review by ligi — CHANGES_REQUESTED** [review]
I told you not to touch the gradle files - please do not waste my time - fix it or there will be no merge

**Comment by webSkg** [comment]
Kindly check that file is not touched any more

**Comment by ligi** [comment]
you could check yourself before asking me to waste my time

image

**Pull request closed without merging**
