### PR TITLE
Pr/1994

### PR DESCRIPTION
**Pull request by nikolay-nikolaev**
EKTA Chain

### CODE REVIEW

**Comment by nikolay-nikolaev** [comment]
What average time for pull request review?

**Comment by nikolay-nikolaev** [comment]
Hello, when you can review this PR?

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also: name must be unique - but found `EKTA` more than once

**Comment by nikolay-nikolaev** [comment]
Changes for code style merged into PR

**Comment by nikolay-nikolaev** [comment]
@ligi hello, can you review pull request?

**Review by ligi — APPROVED** [review]

**Pull request merged**
