### PR TITLE
Add gesoten verse MainNet

### PR DESCRIPTION
**Pull request by yukihiro-o**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
https://explorer.verse.gesoten.com is not reachable

**Comment by nnnnnnsssss** [comment]
Recheck

**Review by nnnnnnsssss — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by yukihiro-o** [comment]
@ligi 
We are now trying to build an OASYS Chain.
To build it, I need a chainId, so I need to secure the chainId first.

see below. It's oasys layer2 build.
https://docs.oasys.games/docs/verse-developer/how-to-build-verse/manual#build-verse


We plan to build it this month.
The test environment has already been built.

The procedure for the test environment is done at
https://github.com/ethereum-lists/chains/pull/3579

**Comment by ligi** [comment]
I still cannot merge with this information - you can remove the explorer if you want me to merge - then also status incubating

**Comment by yukihiro-o** [comment]
@ligi 
Roger that!
Thanks, I'll re-apply after building the blockchain!

**Pull request closed without merging**
