### PR TITLE
adding deelance mainnet

### PR DESCRIPTION
**Pull request by Deelance**

### CODE REVIEW

**Comment by noorshanu** [comment]
@ligi can you check and approve it please

**Comment by Deelance** [comment]
@ligi hey can you please look into this as it is very important for us

**Comment by Deelance** [comment]
fixed file name  i guess that was the error thanks @ligi

**Comment by noorshanu** [comment]
@ligi  can you guide why this pr error

**Comment by ligi** [comment]
please pay 420DAI to lists.eth

**Comment by Deelance** [comment]
@ligi  didnt get you can you explain?

**Comment by ligi** [comment]
support is not free

**Comment by Deelance** [comment]
ok got your point mam thank you

**Comment by Deelance** [comment]
@ligi  just wanted to know how much it will take to update on lists

**Comment by ligi** [comment]
why is it very important for you this is merged fast?

**Comment by Deelance** [comment]
not urgent just wanna know anyways thanks for your quick response. i appreciate your time

**Review by KingRobZombie-CEO — APPROVED** [review]

**Review by ligi — APPROVED** [review]

**Comment by Deelance** [comment]
how much to fund  and where?

**Comment by Deelance** [comment]
@ligi  let me know details about fund contribution how much and where

**Pull request merged**
