### PR TITLE
Add PlayFi Alberio + mainnet details

### PR DESCRIPTION
**Pull request by Archethect**

### CODE REVIEW

**Comment by Archethect** [comment]
@ligi Can this PR be reviewed and merged?
Thanks!

**Comment by Archethect** [comment]
@ligi can this be merged in?

**Comment by Archethect** [comment]
@ligi  can this PR be reviewed?

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by Archethect** [comment]
@ligi can this be reviewed and merged in if ok?

**Pull request closed without merging**
