### PR TITLE
Create eip155-20181205.json

### PR DESCRIPTION
**Pull request by chenjia404**
Hello, please add quarkscout, thanks

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Unfortunately the explorer is not EIP3091 compatible - please make it so first

**Comment by chenjia404** [comment]
> Unfortunately the explorer is not EIP3091 compatible - please make it so first
thanks，I will delete explorer

**Comment by chenjia404** [comment]
I delete explorer

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
:+1:

**Comment by Hlsinclair** [comment]
Ok I guess you can't help me.  not a IT person. Personally asked if you
could help but you can't .ok

**Pull request merged**
