### PR TITLE
 Add Galaxy Chain

### PR DESCRIPTION
**Pull request by galaxytst**
Hi there ! I'm a dev with the Galaxy team. This PR adds a Galaxy Chain

### CODE REVIEW

**Comment by cassa72** [comment]
galaxytst:patch-2

**Review by Nellyjay22 — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Review by julioAk47 — APPROVED** [review]

**Review by julioAk47 — APPROVED** [review]

**Review by Marvin8122 — APPROVED** [review]

**Review by julioAk47 — APPROVED** [review]

**Comment by thereeroyz** [comment]
Teşekkürler :)

**Review by thereeroyz — APPROVED** [review]
Thanks

**Review by johnnydepp1311 — COMMENTED** [review]
faajiparapara@gmail.com

**Pull request closed without merging**
