### PR TITLE
Add Filfox as Filecoin Calibration explorer

### PR DESCRIPTION
**Pull request by chadwick2143**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
please add new explorers on the end of the list

**Comment by peachcheap** [comment]
What is going on, I want to be involved in getting my funds 🤣

**Review by peachcheap — COMMENTED** [review]
I need help

**Comment by Napulsnik** [comment]
> please add new explorers on the end of the list

ok?

**Pull request closed without merging**
