### PR TITLE
Add SolarChainTestnet

### PR DESCRIPTION
**Pull request by likai1130**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot access https://sctsan.starnet.ltd - also explorers need a standard field

**Comment by likai1130** [comment]
Thank you for telling me why I failed. I want to ask, this is our internal test has not been opened, can it be merged?

**Comment by ligi** [comment]
I do not think we should merge internal tesnets. What is the benefit having an internal testnet in a public repo?

**Comment by likai1130** [comment]
We try to meet the standards first. At present, it is in the testing stage and will be open in the future.

**Comment by likai1130** [comment]
It is mentioned in the document introducing the project that the internal chain can also be applied for. We first submit the JSON file to prevent chainId conflict, and then we will open the address after the test is completed.

**Comment by ligi** [comment]
what document are you referring to?

**Comment by likai1130** [comment]
I just found the document. It's this link https://geth.ethereum.org/docs/interface/private-network

**Comment by ligi** [comment]
where does this document state a private chain can be registered here ?-)

**Comment by likai1130** [comment]
In the title choosing a network ID
 "The main network has ID 1. If you supply your own custom network ID which is different than the main network, your nodes will not connect to other nodes and form a private network. If you’re planning to connect to your private chain on the Internet, it’s best to choose a network ID that isn’t already used. You can find a community-run registry of Ethereum networks at https://chainid.network/."
Can this sentence explain that private chains can be registered here?

**Comment by ligi** [comment]
I do not think it states that private chains can be registered here - but yea one could interpret it that way.
Maybe we can create a field "private" that we can leverage here. But I really do not want that chains like that chains like this clutter sites like https://chainlist.org

**Comment by ligi** [comment]
This needs a larger discussion - opened this issue: https://github.com/ethereum-lists/chains/issues/1144

**Comment by likai1130** [comment]
OK, thank you very much for your patience. Then we open the chain to the outside world according to the current process, and then submit pr.

**Comment by likai1130** [comment]
The chain has been opened. Let's see if it can be merged

**Review by likai1130 — COMMENTED** [review]
add chainId 65535

**Pull request closed without merging**
