### PR TITLE
Revert "Add chain 1080 2"

### PR DESCRIPTION
**Pull request by PawelDycha**
Reverts ethereum-lists/chains#3115

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
a) this is not possible - you can only deprecated
b) why anyway

**Comment by yoheinishikubo** [comment]
@ligi 
Sorry for being late and thank you for everything.
I will deprecate this and resubmit a PR.

**Comment by yoheinishikubo** [comment]
Sorry, I found this PR is merged.
I will just deprecate this.

**Comment by yoheinishikubo** [comment]
@ligi 
Thank you for everything.
I found this PR is not mine and I can do nothing for this.

**Comment by ligi** [comment]
OK - closing it then - unfortunately another troll as it seems

**Pull request closed without merging**
