### PR TITLE
Adding Poodl to the Ethereum chain list

### PR DESCRIPTION
**Pull request by PoodlChain**
https://poodl.org
**Poodl Mainnet**

- Chain ID: 15259
- RPC: https://rpc.poodl.org
- Explorer: https://explorer.poodl.org

**Poodl Testnet**

- Chain ID: 15257
- RPC: https://testnet-rpc.poodl.org
- Faucet: https://faucet.poodl.org
- Explorer: https://testnet.poodl.org

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by PoodlChain** [comment]
@ligi 
https://explorer.poodl.org/
we've fixed it.

**Comment by PoodlChain** [comment]
Hello @ligi 
Kindly assist if there's anything required from our side, We'll do it.
And we've fixed our [explorer](https://explorer.poodl.org/)

**Comment by PoodlChain** [comment]
Closing this pull request

**Pull request closed without merging**
