### PR TITLE
add peer testnet to ethereum

### PR DESCRIPTION
**Pull request by karanvir12**

### CODE REVIEW

**Review by surgarshorts — APPROVED** [review]
Test net feedback to merge

**Comment by karanvir12** [comment]
Why is the validation for formatting check not passing? Could you please let me know where the issue lies?

**Review by alokeutpal — APPROVED** [review]
yes

**Review by alokeutpal — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Review by ligi — APPROVED** [review]

**Pull request merged**
