### PR TITLE
Update eip155-8080.json with Shardeum Network

### PR DESCRIPTION
**Pull request by ashutoshpw**
- Removed the older Network as it is down from a long time
- Added Shardeum network which has the same chain ID

### CODE REVIEW

**Comment by ligi** [comment]
I need to add a flag that indicates this is a reused chainID as this has the risk of replay attacks

**Comment by ashutoshpw** [comment]
Should I add `isChainIdResued:true` or do you have something else in mind?

**Comment by ligi** [comment]
You cannot do it yet - I need to add it to the CI - otherwise it will fail.
Also currently I am leaning more to something generic like "redFlags":["reusedChainId"]

**Comment by ashutoshpw** [comment]
Got it, thanks.

**Comment by ligi** [comment]
redFlags is now supported

**Comment by manny363** [comment]
If your trying to help me out Bless you and if your not it's really not the
best time for this. Like I told you I have had a long stressful week and
half .

**Comment by ashutoshpw** [comment]
Ready to be merged now.

**Review by jonesk7734 — APPROVED** [review]
Ok

**Pull request merged**
