### PR TITLE
Add Coinbit Mainnet

### PR DESCRIPTION
**Pull request by AnggaPvr**

### CODE REVIEW

**Comment by AnggaPvr** [comment]
@mordon93 Hi, would you like to help merge the PR?

**Comment by ligi** [comment]
@mordon93 is a troll

you need to fix CI error: RPC chainId (150) does not match chainId from json (112)

**Comment by AnggaPvr** [comment]
Hi @ligi , thank you for point it out. 
I just fix the RPC Url. Could you help to approve the workflow?

**Comment by AnggaPvr** [comment]
Hi @ligi @mordon93, I just fix the RPC Url. Could you help to approve the workflow?

**Review by 37elivan73 — APPROVED** [review]

**Review by ligi — APPROVED** [review]

**Comment by 37elivan73** [comment]
Los token isu son un lanzamiento

**Pull request merged**
