### PR TITLE
Add ApeChain mainnet

### PR DESCRIPTION
**Pull request by MYKatz**

### CODE REVIEW

**Review by dmrazzy — COMMENTED** [review]
Good

**Review by kaisung — COMMENTED** [review]
looks good to me, ship it

**Comment by kaisung** [comment]
@MYKatz might need to assign @ligi for review

**Comment by MYKatz** [comment]
I don't think I have perms to add him as a reviewer on GH. @ligi can you please review?

**Comment by joescherping** [comment]
Hello! I am also interested in getting ApeChain on the chain list - I created a PR for it but then deleted it when I realized it was a duplicate of this one. @kaisung can you add @ligi as a reviewer? Thanks all! 🚀

**Comment by kaisung** [comment]
> Hello! I am also interested in getting ApeChain on the chain list - I created a PR for it but then deleted it when I realized it was a duplicate of this one. @kaisung can you add @ligi as a reviewer? Thanks all! 🚀

@joescherping sorry I'm not a maintainer so can't add @ligi as reviewer but hoping they see this and can help review and merge soon.

**Comment by Ramyromel** [comment]
@ligi

**Comment by joshuanwankwo** [comment]
@ligi

**Comment by joescherping** [comment]
it's already appearing on chainlist but with different metadata: https://chainlist.org/?search=33139

**Comment by ligi** [comment]
rebase the PR or allow me to rebase

**Comment by MYKatz** [comment]
Apologies for that @ligi, just rebased.

**Review by ligi — CHANGES_REQUESTED** [review]
OK I checked it and could merge - but stupid meme chains are not merged for free - so pay 420 DAI to lists.eth and sent the tx id here

**Comment by kaisung** [comment]
@ligi We will sponsor this merge. Tx IDs are below. Please help merge in the next 24 hours. thanks
https://etherscan.io/tx/0x59042d0c6833ac6099627b19a2ef749ce3ebfbea4d0fb15a54bc60f5eeb6cdec
https://etherscan.io/tx/0x378e80bf65542888c7965c4ff93e5911d789e7e70dc8bf41ea227a762a2c5e9c

**Review by ligi — APPROVED** [review]

**Pull request merged**
