### PR TITLE
Change neonlink native coin symbol

### PR DESCRIPTION
**Pull request by galaxy126**

### CODE REVIEW

**Comment by surgarshorts** [comment]
Change 3262

**Comment by surgarshorts** [comment]
Change 3162

**Comment by surgarshorts** [comment]
Change neon format

**Comment by 08105089540** [comment]
Good

**Comment by ligi** [comment]
svg is better

**Comment by 08105089540** [comment]
You have any idea and why svg better

**Comment by 08105089540** [comment]
You have any idea and why svg better

**Pull request closed without merging**
