### PR TITLE
Add Canto Testnet - Chain 740

### PR DESCRIPTION
**Pull request by hiddenPaul**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
name must be unique - but found `CANTO` more than once

**Comment by hiddenPaul** [comment]
> name must be unique - but found `CANTO` more than once

Changed chain/name to be Canto Tesnet

**Comment by hiddenPaul** [comment]
Updated short name to be unique

**Review by ligi — APPROVED** [review]

**Review by 13364174888 — COMMENTED** [review]
你的未来我预定了

**Pull request merged**
