### PR TITLE
Update Fusion Network rpc, logo, config

### PR DESCRIPTION
**Pull request by fanbsb**
Fusion Network config update
1. RPC update.
2. Explorer update.
3. Icon update.
4. Testnet Network update.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

**Comment by fanbsb** [comment]
Thanks for the reminder, I have uploaded the icon files into the iconDownload folder, please review

**Review by ligi — CHANGES_REQUESTED** [review]
: width in json (../_data/icons/fusion.json) is 1000 but actually is in imageDownload 31

**Comment by fanbsb** [comment]
> : width in json (../_data/icons/fusion.json) is 1000 but actually is in imageDownload 31

Update the size for both 2 images

**Review by ligi — APPROVED** [review]

**Pull request merged**
