### PR TITLE
Add PlayFi Alberio + Mainnet

### PR DESCRIPTION
**Pull request by Archethect**

### CODE REVIEW

**Comment by Archethect** [comment]
@ligi Can this one be merged in please?

**Review by ligi — CHANGES_REQUESTED** [review]
explorer does not seem to be EIP3091 compatible

**Review by Hanae1963 — COMMENTED** [review]
A

**Comment by Archethect** [comment]
> explorer does not seem to be EIP3091 compatible

Its a clone of ZKSync Mainnet, which is also stated as EIP3091 compatible
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-324.json

So can you tell me why this one is accepted, and ours wouldn't?

**Comment by ligi** [comment]
AFAIR it did not work when it came to blocks - but seems to work now

**Pull request merged**
