### PR TITLE
Add new rpc to existing ones

### PR DESCRIPTION
**Pull request by veljkoTNFT**

### CODE REVIEW

**Comment by veljkoTNFT** [comment]
Hi @ligi if you can approve this one, we added a new RPC to our chain

**Review by ligi — CHANGES_REQUESTED** [review]
please add new RPCs to the end of the list

**Comment by veljkoTNFT** [comment]
I did it on purpose to make the new one first and more desirable.

**Comment by ligi** [comment]
what last update are you referencing?

**Comment by veljkoTNFT** [comment]
My last PR for updating this file. Can you pls approve, the one I added is the most desirable now to be added in the wallet?

**Comment by veljkoTNFT** [comment]
If it's a must, I'll put it at the end, I just want this change to be reflected as soon as possible.

**Comment by ligi** [comment]
provide a link to the last PR

**Comment by veljkoTNFT** [comment]
https://github.com/ethereum-lists/chains/pull/5548/files this one

**Comment by veljkoTNFT** [comment]
all ok or I need to resubmit @ligi ?

**Comment by veljkoTNFT** [comment]
ping @ligi

**Comment by veljkoTNFT** [comment]
ping @ligi

**Review by ligi — APPROVED** [review]

**Pull request merged**
