### PR TITLE
add imversed testnet and imversed canary up

### PR DESCRIPTION
**Pull request by denisesaulov**

### CODE REVIEW

**Comment by denisesaulov** [comment]
> short name must be unique - but found `Imversed` more than once

changes have been made

**Comment by fulldiver-ilya** [comment]
Is there any expected ETA for approving? @ligi :]

**Review by ligi — APPROVED** [review]

**Comment by denisesaulov** [comment]
done

**Comment by denisesaulov** [comment]
merging?

**Comment by alexeysuvorov** [comment]
Hello @ligi. it is Alex from Imversed. Would you please consider to merge this pull request? Looks like it is ready to be merged for a while already. If you have any doubts regarding the legitimacy of this network, please feel free to join our discord community (https://discord.gg/PTcWKDqEer), check the documentation (http://docs.imversed.com) or whitepaper (https://imversed.com/Imversed_Whitepaper.pdf). Also feel free to ping me directly if you have any questions regarding this project. I will be happy to chat. Thanks.

**Review by robledo6 — COMMENTED** [review]
No se nadie esta serca de lonq7e pudiera hacer y como que diculgarled mis aptod haaa haaaa

**Review by ligi — APPROVED** [review]

**Pull request merged**
