### PR TITLE
add web3games chain and icon

### PR DESCRIPTION
**Pull request by Zombieliu**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
https://explorer.web3games.org seems to redirect to the devnet one - so this cannot work
also please remove the tailing slash from all explorer URLs

**Comment by Zombieliu** [comment]
> 
Yep,my friend, mainnet browser is not online. 
Currently, it is temporarily replaced by the development dev network.

**Comment by ligi** [comment]
please only submit the dev network then - I do not want to merge wrong data

**Comment by Zombieliu** [comment]
> please only submit the dev network then - I do not want to merge wrong data



> please only submit the dev network then - I do not want to merge wrong data

ok! Thx

**Pull request merged**
