### PR TITLE
add cube chain infos

### PR DESCRIPTION
**Pull request by hcgaptx**
add cube chain infos

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Something is weird with the explorer - when I open `https://scan.cube.network` I first get a warning and then I am redirected

**Comment by hcgaptx** [comment]
> Something is weird with the explorer - when I open `https://scan.cube.network` I first get a warning and then I am redirected

Sorry, I have asked relevant personnel, the overall service is not online at present, the domain name is just applied for first, can not access temporarily. I would like to register the relevant information first, is that ok ？

**Comment by hcgaptx** [comment]
> Something is weird with the explorer - when I open `https://scan.cube.network` I first get a warning and then I am redirected

I'm sorry, I asked the relevant personnel, but the overall service is not yet online, the domain name is just applied for, and it is temporarily unavailable. I want to register the relevant information first, can you?

**Comment by ligi** [comment]
no - e.g. as I cannot check EIP3091 compliance then

**Comment by hcgaptx** [comment]
All right, thanks anyway

**Pull request closed without merging**
