### PR TITLE
Fix length error for symbol

### PR DESCRIPTION
**Pull request by ammar-lakho**
Symbol for testnet was >6 characters and hence I was getting an error while trying to add the network. Kindly merge the fix.

### CODE REVIEW

**Comment by ligi** [comment]
Thanks - seeing this for the second time now - did MetaMask just introduce this constraint?

**Comment by ammar-lakho** [comment]
> Thanks - seeing this for the second time now - did MetaMask just introduce this constraint?

Not sure, I think the error is from the website?

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
From which website? Can you show the error you got?
This:
https://github.com/ethereum-lists/chains/pull/1060
made me think it comes from MetaMask

**Comment by ammar-lakho** [comment]
> From which website? Can you show the error you got? This: #1060 made me think it comes from MetaMask

https://chainlist.org/

Error
Expected 2-6 character string 'nativeCurrency.symbol'. Received: tZENITH

Screenshot 2022-04-11 at 11 09 49 AM

**Comment by ligi** [comment]
thanks - I think this error comes from MetaMask - is just displayed by the site

**Pull request merged**
