### PR TITLE
Add Nepal Blockchain Network (977)

### PR DESCRIPTION
**Pull request by nepalbitcoin**
Namaste  :pray:
I'm adding Nepal Blockchain Network, it's Open + FREE Blockchain as a Service using a community managed clique/POA consensus. We're currently running on Goerli Testnet to bootstrap our basic infrastructures that we'll replace with our chain's genesis in few days. 

Stats Page : https://stats.nepalblockchain.network/ 
Faucet, explorer and main page are still missing for now..

And thank you Mr. @ligi for pointing this repo on twitter. :vulcan_salute: 
Finally this closes walleth/walleth/issues/36

### CODE REVIEW

**Comment by ligi** [comment]
great! Will merge when your chain is live

**Comment by nepalbitcoin** [comment]
I've changed short name to "YETI".
It was voted yesterday during our community calls.
This should be final. :vulcan_salute:

**Comment by juan21232** [comment]
Si digame

**Comment by ligi** [comment]
is this chain now launched? Hesitating a bit to merge as e.g. https://faucet.nepalblockchain.network does not resolve for me - guess there have been some problems with the launch?

**Comment by nepalbitcoin** [comment]
:pray: @ligi
We are still testing genesis allocation for "time capsules" that'll store coins locked in future timestamps/vault, using `CREATE2/EIP1014`.. and I'm waiting for landing page/basic docs to finish and our logo competition is still out there.

It'll take 2-4 days moar to init our chain and faucet. :vulcan_salute:

**Comment by juan21232** [comment]
mi pago

**Comment by nepalbitcoin** [comment]
@ligi :pray: Sorry for late reply, 
I'm forwarding both API endpoints to same RPC/node for now. 
We need both API endpoints which will be load balanced over multiple nodes.

**Comment by ligi** [comment]
```
✓ ~ ping api.nepalblockchain.de                                         00:44:28
ping: api.nepalblockchain.de: No address associated with hostname
```

**Comment by pedrouid** [comment]
Please continue this PR discussion on the new one on #60

**Pull request closed without merging**
