### PR TITLE
add debank mainnet

### PR DESCRIPTION
**Pull request by recursion128**
This PR adds DeBank Chain mainnet to the list of registered chains.

### CODE REVIEW

**Comment by Srikarrao1** [comment]
@recursion128 Please let me know if I can help you passing the tests and merge this PR properly for few bucks.

**Comment by Srikarrao1** [comment]
@recursion128 The formatting is not as expected by the checks be it Json or Icon, let's wait till the checks.

**Review by Tumelo-Alt — COMMENTED** [review]
Unable to merge

**Comment by Srikarrao1** [comment]
@recursion128  I cannot actually see what is the blocker here other than your commit hash, I can help you merge this PR seperately from my side for small charge, after successful commit today, please let me know if we can proceed ahead

**Pull request closed without merging**
