### PR TITLE
SKALE Testnets Update

### PR DESCRIPTION
**Pull request by manuelbarbas**
Due to recent updates on the SKALE Testnets the list needed to be updated
For each of the 4 SKALE testnets presents on the list it was updated the following:
- RPC
- ChainId
- Faucet
- Explorer URL

### CODE REVIEW

**Comment by manuelbarbas** [comment]
Hey @ligi 

The SKALE testnets where updated. Could you please review this PR?

Thanks

**Review by ligi — CHANGES_REQUESTED** [review]
you cannot delete chains - you can only mark them deprecated

**Comment by manuelbarbas** [comment]
The name of the chains are the exact same. The changes were the RPCs, ChainIds, Explorer, ect...

Example:

The SKALE Nebula Testnet Hub is still called like this, but the RPCs, ChainId, Explorer are different.

I updated those details in each SKALE Testnet hub

**Comment by ligi** [comment]
image

you deleted chains - this cannot happen as it allows replay attacks in the future - will not merge as is

**Comment by manuelbarbas** [comment]
got it, thank you.

To deprecate chains is just add to the json the following: "status": "deprecated". Is this correct?

**Pull request merged**
