### PR TITLE
Added Avascan logo and Avalanche subnets configs

### PR DESCRIPTION
**Pull request by iJaack**
New subnet configs added:
- Swimmer Subnet Mainnet (73772)
- Swimmer Subnet Testnet (73771)
- Kaira Testnet (71524)
- Hero Testnet (17771)
- Castle Crush Testnet (31416)

Existing subnet configs updated:
- DFK Chain Mainnet (53935)
- DFK Chain Testnet (335)
- C-Chain Mainnet (43114)
- C-Chain Testnet (43113)
- Dexalot Testnet (432201)

Added Avascan explorer logo

EDIT June 22nd: added Swimmer logo

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Where did you pin QmZnLaoE2mxftVAVXrPxvrn6i1PLsBuV1B4VxbT5jiu7Y7 - I cannot resolve it

**Comment by ligi** [comment]
ah wait - now it resolved - just took a long time

**Comment by iJaack** [comment]
> ah wait - now it resolved - just took a long time

It's on ipfs.infura.io via this website: https://anarkrypto.github.io/upload-files-to-ipfs-from-browser-panel/public/

Do you need me to upload/pin it to another provider?

**Comment by iJaack** [comment]
@ligi I removed Avascan logo and merged with the latest commits, let me know if everything's good.

**Comment by ligi** [comment]
the logo resolved in the end - so you could have kept it - see https://github.com/ethereum-lists/chains/pull/1236#issuecomment-1153117421

**Comment by iJaack** [comment]
> the logo resolved in the end - so you could have kept it - see https://github.com/ethereum-lists/chains/pull/1236#issuecomment-1153117421

It's better to use a faster pinning. In the meantime @ligi , are there other issues that block this PR to be merged?

**Comment by vickissbaba** [comment]
Can I say something

**Comment by iJaack** [comment]
In the meantime, I added the Swimmer network logo and merged the latest contributions. Let me know if there's anything I can do to speed this up.

**Comment by iJaack** [comment]
@ligi any update?

**Comment by iJaack** [comment]
@ligi any feedback on this?

**Pull request closed without merging**
