### PR TITLE
change Smart Bitcoin Cash Testnet to EthereumPoW Mainnet

### PR DESCRIPTION
**Pull request by XDDTristan**
EthereumPoW Twitter: https://twitter.com/EthereumPoW

### CODE REVIEW

**Comment by ligi** [comment]
nope

**Comment by ligi** [comment]
https://github.com/ethereum-lists/chains#collision-management

**Review by jonesk7734 — APPROVED** [review]
😀

**Comment by dinhtuananhne** [comment]
- [ ] #

**Review by Herand19 — COMMENTED** [review]
Hi

**Pull request closed without merging**
