### PR TITLE
Add API_KEY parameter for Infura RPC endpoints

### LINKED ISSUE #36: API keys
follow up from this mail from infura: 

```

7 days remaining to update your Infura API authentication | 7 days remaining to update your Infura API authentication | 7 days remaining to update your Infura API authentication
-- | -- | --
7 days remaining to update your Infura API authentication | 7 days remaining to update your Infura API authentication
7 days remaining to update your Infura API authentication
This is the final message being sent prior to a very important change that will impact all users of the Infura API endpoints.  In this January 17th blog post,  we provided the latest timeline to deprecate our legacy API  authentication. Requests will start to require a Project ID generated  from the Infura Dashboard. More information on how to send requests  using a Project ID can be found in our docs. The next upcoming change will occur on:  March 27, 2019, 20:00 UTC Support will officially stop for all requests not sent using an Infura Dashboard-generated Project ID.  This transition will ensure that our service reliability and performance  is consistent for all users. For more information about the changes  please see the blog post linked above.  What do I need to do? If you haven’t done so already, create a free account at https://infura.io/register.  Once you log in to the Dashboard, simply create a new project, and your  Project ID (and associated Infura API endpoint URLs) will be generated.  Replace your old Infura URL in your code with the newly generated URL  from the Dashboard.  You may also create multiple projects to isolate traffic for multiple  dapps/use-cases. Stats can be viewed in aggregate or on a per-project  basis.  If you maintain a library that leverages Infura, please reach out directly to help you with this transition.  How do I know I am using the correct API endpoint URL? Prior to July 2018, your Infura API endpoint would have looked like this:  https://mainnet.infura.io/[YOUR_KEY]   The updated API endpoint using the new authentication generated in the Infura Dashboard will look like this:  https://mainnet.infura.io/v3/[PROJECT_ID]   If you have any questions please post them at community.infura.io or email us at support@infura.io. | This is the final message being sent prior to a very important change that will impact all users of the Infura API endpoints.  In this January 17th blog post,  we provided the latest timeline to deprecate our legacy API  authentication. Requests will start to require a Project ID generated  from the Infura Dashboard. More information on how to send requests  using a Project ID can be found in our docs. The next upcoming change will occur on:  March 27, 2019, 20:00 UTC Support will officially stop for all requests not sent using an Infura Dashboard-generated Project ID.  This transition will ensure that our service reliability and performance  is consistent for all users. For more information about the changes  please see the blog post linked above.  What do I need to do? If you haven’t done so already, create a free account at https://infura.io/register.  Once you log in to the Dashboard, simply create a new project, and your  Project ID (and associated Infura API endpoint URLs) will be generated.  Replace your old Infura URL in your code with the newly generated URL  from the Dashboard.  You may also create multiple projects to isolate traffic for multiple  dapps/use-cases. Stats can be viewed in aggregate or on a per-project  basis.  If you maintain a library that leverages Infura, please reach out directly to help you with this transition.  How do I know I am using the correct API endpoint URL? Prior to July 2018, your Infura API endpoint would have looked like this:  https://mainnet.infura.io/[YOUR_KEY]   The updated API endpoint using the new authentication generated in the Infura Dashboard will look like this:  https://mainnet.infura.io/v3/[PROJECT_ID]   If you have any questions please post them at community.infura.io or email us at support@infura.io. | This is the final message being sent prior to a very important change that will impact all users of the Infura API endpoints.  In this January 17th blog post,  we provided the latest timeline to deprecate our legacy API  authentication. Requests will start to require a Project ID generated  from the Infura Dashboard. More information on how to send requests  using a Project ID can be found in our docs. The next upcoming change will occur on:  March 27, 2019, 20:00 UTC Support will officially stop for all requests not sent using an Infura Dashboard-generated Project ID.  This transition will ensure that our service reliability and performance  is consistent for all users. For more information about the changes  please see the blog post linked above.  What do I need to do? If you haven’t done so already, create a free account at https://infura.io/register.  Once you log in to the Dashboard, simply create a new project, and your  Project ID (and associated Infura API endpoint URLs) will be generated.  Replace your old Infura URL in your code with the newly generated URL  from the Dashboard.  You may also create multiple projects to isolate traffic for multiple  dapps/use-cases. Stats can be viewed in aggregate or on a per-project  basis.  If you maintain a library that leverages Infura, please reach out directly to help you with this transition.  How do I know I am using the correct API endpoint URL? Prior to July 2018, your Infura API endpoint would have looked like this:  https://mainnet.infura.io/[YOUR_KEY]   The updated API endpoint using the new authentication generated in the Infura Dashboard will look like this:  https://mainnet.infura.io/v3/[PROJECT_ID]   If you have any questions please post them at community.infura.io or email us at support@infura.io.
This is the final message being sent prior to a very important change that will impact all users of the Infura API endpoints.  In this January 17th blog post,  we provided the latest timeline to deprecate our legacy API  authentication. Requests will start to require a Project ID generated  from the Infura Dashboard. More information on how to send requests  using a Project ID can be found in our docs. The next upcoming change will occur on:  March 27, 2019, 20:00 UTC Support will officially stop for all requests not sent using an Infura Dashboard-generated Project ID.  This transition will ensure that our service reliability and performance  is consistent for all users. For more information about the changes  please see the blog post linked above.  What do I need to do? If you haven’t done so already, create a free account at https://infura.io/register.  Once you log in to the Dashboard, simply create a new project, and your  Project ID (and associated Infura API endpoint URLs) will be generated.  Replace your old Infura URL in your code with the newly generated URL  from the Dashboard.  You may also create multiple projects to isolate traffic for multiple  dapps/use-cases. Stats can be viewed in aggregate or on a per-project  basis.  If you maintain a library that leverages Infura, please reach out directly to help you with this transition.  How do I know I am using the correct API endpoint URL? Prior to July 2018, your Infura API endpoint would have looked like this:  https://mainnet.infura.io/[YOUR_KEY]   The updated API endpoint using the new authentication generated in the Infura Dashboard will look like this:  https://mainnet.infura.io/v3/[PROJECT_ID]   If you have any questions please post them at community.infura.io or email us at support@infura.io. | This is the final message being sent prior to a very important change that will impact all users of the Infura API endpoints.  In this January 17th blog post,  we provided the latest timeline to deprecate our legacy API  authentication. Requests will start to require a Project ID generated  from the Infura Dashboard. More information on how to send requests  using a Project ID can be found in our docs. The next upcoming change will occur on:  March 27, 2019, 20:00 UTC Support will officially stop for all requests not sent using an Infura Dashboard-generated Project ID.  This transition will ensure that our service reliability and performance  is consistent for all users. For more information about the changes  please see the blog post linked above.  What do I need to do? If you haven’t done so already, create a free account at https://infura.io/register.  Once you log in to the Dashboard, simply create a new project, and your  Project ID (and associated Infura API endpoint URLs) will be generated.  Replace your old Infura URL in your code with the newly generated URL  from the Dashboard.  You may also create multiple projects to isolate traffic for multiple  dapps/use-cases. Stats can be viewed in aggregate or on a per-project  basis.  If you maintain a library that leverages Infura, please reach out directly to help you with this transition.  How do I know I am using the correct API endpoint URL? Prior to July 2018, your Infura API endpoint would have looked like this:  https://mainnet.infura.io/[YOUR_KEY]   The updated API endpoint using the new authentication generated in the Infura Dashboard will look like this:  https://mainnet.infura.io/v3/[PROJECT_ID]   If you have any questions please post them at community.infura.io or email us at support@infura.io.
This is the final message being sent prior to a very important change that will impact all users of the Infura API endpoints.  In this January 17th blog post,  we provided the latest timeline to deprecate our legacy API  authentication. Requests will start to require a Project ID generated  from the Infura Dashboard. More information on how to send requests  using a Project ID can be found in our docs. The next upcoming change will occur on:  March 27, 2019, 20:00 UTC Support will officially stop for all requests not sent using an Infura Dashboard-generated Project ID.  This transition will ensure that our service reliability and performance  is consistent for all users. For more information about the changes  please see the blog post linked above.  What do I need to do? If you haven’t done so already, create a free account at https://infura.io/register.  Once you log in to the Dashboard, simply create a new project, and your  Project ID (and associated Infura API endpoint URLs) will be generated.  Replace your old Infura URL in your code with the newly generated URL  from the Dashboard.  You may also create multiple projects to isolate traffic for multiple  dapps/use-cases. Stats can be viewed in aggregate or on a per-project  basis.  If you maintain a library that leverages Infura, please reach out directly to help you with this transition.  How do I know I am using the correct API endpoint URL? Prior to July 2018, your Infura API endpoint would have looked like this:  https://mainnet.infura.io/[YOUR_KEY]   The updated API endpoint using the new authentication generated in the Infura Dashboard will look like this:  https://mainnet.infura.io/v3/[PROJECT_ID]   If you have any questions please post them at community.infura.io or email us at support@infura.io.

```

wonder how we deal with mandatory api keys in rpc services

### PR DESCRIPTION
**Pull request by pedrouid**
Fix #36

### CODE REVIEW

**Comment by pedrouid** [comment]
Personally I find it cleaner to have the same variable name to replace rather than different ones based on the url.

```typescript
function handleApiKey(rpc: string) {
  if (rpc.includes('infura.io)) {
    rpc = rpc.replace('%API_KEY%', INFURA_API_KEY)
  } else if (rpc.includes('etherscan.io') {
    rpc = rpc.replace('%API_KEY%', ETHERSCAN_API_KEY)
  } else {
    throw new Error('Couldn't replace API_KEY for rpc url:', rpc)
  }
}
```
But it's also not much different than this
```typescript
function handleApiKey(rpc: string) {
  if (rpc.includes('INFURA_API_KEY)) {
    rpc = rpc.replace('%INFURA_API_KEY%', INFURA_API_KEY)
  } else if (rpc.includes('ETHERSCAN_API_KEY') {
    rpc = rpc.replace('%ETHERSCAN_API_KEY%', ETHERSCAN_API_KEY)
  } else {
    throw new Error('Couldn't replace API_KEY for rpc url:', rpc)
  }
}
```
Also if you want to change from `%API_KEY%` to `${API_KEY}`. I'm also fine with that!

Feel free to make the changes on the branch. We need to at least get this by this afternoon

**Comment by ligi** [comment]
ack I will do the change - but I really want to have the different variable names. Think this is better. you do not even need the ifs for every case then as you can have a hashmap in the input

hashMapOf("INFURA_API_KEY" to "myInfuraKey","ETHERSCAN_API_KEY" to "myEtherscanAPIKey", ..)

then find the ${<KEY>} and grab hashMap(key). Also this is more robust for ununiform URLS. Really lean to this solution

**Comment by ligi** [comment]
@pedrouid done in #42 - did it as a new PR - just easier this way - did not include the drive by indentation - so only the change in the context of the issue

**Comment by pedrouid** [comment]
Replaced by #42

**Pull request closed without merging**
