### PR TITLE
BLGChain Testnet Adding

### PR DESCRIPTION
**Pull request by waliair**
BLGChain Testnet Adding.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The Icon BLG does not exist - was used in eip155-123321.json

**Review by ligi — CHANGES_REQUESTED** [review]
chainId must match the filename

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by ligi** [comment]
prettier still fails on the icon

**Review by 13364174888 — APPROVED** [review]

**Review by ligi — APPROVED** [review]

**Pull request merged**
