### PR TITLE
Create eip155-973.json

### PR DESCRIPTION
**Pull request by plunyach**
list plm smart chain

### CODE REVIEW

**Comment by plunyach** [comment]
Palm Smart Chain

**Comment by plunyach** [comment]
Add Palm Smart  Chain

**Review by plunyach — COMMENTED** [review]
update file name and chain id

**Comment by plunyach** [comment]
update chain id

**Review by plunyach — COMMENTED** [review]
update icon name

**Comment by plunyach** [comment]
update icon

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by plunyach** [comment]
live explorer

**Pull request closed without merging**
