### PR TITLE
Add asset chain testnet

### PR DESCRIPTION
**Pull request by CeoFred**

### CODE REVIEW

**Comment by CeoFred** [comment]
Hello @ligi could you check out this, thank you.

**Comment by CeoFred** [comment]
@ligi hey man, i promise you.. this changes lit. would appreciate some review here.

**Comment by CeoFred** [comment]
this action be tripping https://github.com/ethereum-lists/chains/actions/runs/10267081299/job/28407351198?pr=5639

even `[
  {
    "url": "ipfs://QmdwQDr6vmBtXmK2TmknkEuZNoaDqTasFdZdu3DRw8b2wt",
    "width": 1000,
    "height": 1628,
    "format": "png"
  }
]
`
returns a html content type

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time  or cloudflare could not resolve the image in a reasonable time for the CI - maybe you have the icon only locally in your ipfs node that is not properly connected or there is some other IPFS problem - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by CeoFred** [comment]
> I could not resolve your CID with `ipfs get` in a reasonable time or cloudflare could not resolve the image in a reasonable time for the CI - maybe you have the icon only locally in your ipfs node that is not properly connected or there is some other IPFS problem - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

I think it's now available.. sorry for wasting your time, it was an issue with node syncing I guess. @ligi . thank you for your patience.

**Review by CeoFred — COMMENTED** [review]
I've been able to access it via ipfs get command

**Comment by CeoFred** [comment]
@ligi Hello, can you please review now?

**Comment by CeoFred** [comment]
@lance-web3 @ligi @farcaller @artob @zapnap please please, can you attend to me?

**Review by ligi — APPROVED** [review]

**Pull request merged**
