### PR TITLE
Update token symbol for VinuChain

### PR DESCRIPTION
**Pull request by agopankov**
The changes concern the symbol for VinuChain.
By mistake, the previous developer inserted the Cyrillic symbol С instead of the English symbol C.

### CODE REVIEW

**Review by PizzaShift — APPROVED** [review]

**Review by PizzaShift — APPROVED** [review]

**Review by PizzaShift — APPROVED** [review]
[]()

**Review by ligi — CHANGES_REQUESTED** [review]
please elaborate on the change

**Comment by agopankov** [comment]
Good day!
The changes concern the symbol for VinuChain.
By mistake, the previous developer inserted the Cyrillic symbol С instead of the English symbol C.

**Comment by agopankov** [comment]
> Good day!
> The changes concern the symbol for VinuChain.
> By mistake, the previous developer inserted the Cyrillic symbol С instead of the English symbol C.

**Comment by agopankov** [comment]
> please elaborate on the change

Good day!
The changes concern the symbol for VinuChain.
By mistake, the previous developer inserted the Cyrillic symbol С instead of the English symbol C.

**Pull request merged**
