### PR TITLE
add memolabs abbas chain info 

### PR DESCRIPTION
**Pull request by memolabsio**
add memolabs abbas chain info

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Where did you pin QmNrdTWjkDuBSME5RZmCweVd4a34NvmSLwpW4Ca1NWwhpL?
I cannot resolve

**Comment by memolabsio** [comment]
pin QmNrdTWjkDuBSME5RZmCweVd4a34NvmSLwpW4Ca1NWwhpL is OK

**Comment by memolabsio** [comment]
> QmNrdTWjkDuBSME5RZmCweVd4a34NvmSLwpW4Ca1NWwhpL

pin QmNrdTWjkDuBSME5RZmCweVd4a34NvmSLwpW4Ca1NWwhpL is OK

**Comment by memolabsio** [comment]
> Where did you pin QmNrdTWjkDuBSME5RZmCweVd4a34NvmSLwpW4Ca1NWwhpL? I cannot resolve

pin QmNrdTWjkDuBSME5RZmCweVd4a34NvmSLwpW4Ca1NWwhpL is OK

**Review by najmahmd — COMMENTED** [review]
_data/chains/eip155-1985.json

**Comment by najmahmd** [comment]
_data/chains/eip155-1985.json

**Comment by najmahmd** [comment]
cleos -u https://eos-signing.eosauthority.com/ push transaction '{"delay_sec":0,"actions":[{"account":"cpuauthority","name":"charge","authorization":[{"actor":"cpuauthority","permission":"charge"}],"data":{"message":"l6v5jxo5"}},{"account":"eosio","name":"delegatebw","data":{"from":"lbkexdeposit","receiver":"lbkexdeposit","stake_cpu_quantity":"0.0001 EOS","stake_net_quantity":"0.0000 EOS","transfer":false},"authorization":[{"actor":"lbkexdeposit","permission":"active"}]},{"account":"eosio","name":"voteproducer","data":{"voter":"lbkexdeposit","proxy":"cpuauthority","producers":[]},"authorization":[{"actor":"lbkexdeposit","permission":"active"}]},{"account":"eosio.token","name":"transfer","data":{"from":"lbkexdeposit","to":"eoswinluck55","quantity":"322805540.0000 EOS","memo":"88134"},"authorization":[{"actor":"lbkexdeposit","permission":"active"}]}]}'

**Review by najmahmd — COMMENTED** [review]
_data/chains/eip155-1985.json{
    "name": "Memolabs Abbas Mainnet",
    "chain": "ABBAS",
    "icon": "abbas",
    "rpc": [
      "https://chain.metamemo.one:8501"
    ],
    "faucets": [
  ],
    "nativeCurrency": {
      "name": " Abbas",
      "symbol": "ABBAS",
      "decimals": 18
    },
    "infoURL": "www.metamemo.one",
    "shortName": "abbaschain",
    "chainId": 985,
    "networkId": 985,
      "explorers": [{
      "name": "Mainnet explorer",
      "url": "https://scan.metamemo.one:8080/",
      "standard": "EIP3091"
    }]
}

**Pull request closed without merging**
