### PR TITLE
Add Gravity Alpha Mainnet explorer gscan

### PR DESCRIPTION
**Pull request by oyyblin**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Add the new explorer to the end of the list

**Comment by oyyblin** [comment]
Moved new explorer to the end of the list

**Review by ligi — CHANGES_REQUESTED** [review]
the explorer does not seem to be EIP3091 compatible

**Comment by oyyblin** [comment]
Hi @ligi I pinged the team behind gscan (l2scan) and they've updated gscan to be EIP3091 compatible. Please let me know if there are other issues :)

**Review by ligi — APPROVED** [review]

**Pull request merged**
