### PR TITLE
Add godwoken v1.1 reservation

### PR DESCRIPTION
**Pull request by m-bo-one**

### CODE REVIEW

**Review by Kuzirashi — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
Please do not delete old chains - only deprecate them - this is to prevent replay attacks

**Comment by Kuzirashi** [comment]
Hello @ligi, your feedback has been addresses. Could you please re-check? 🙏

**Comment by Kuzirashi** [comment]
@ligi 

Can you please take a look?

**Comment by Kuzirashi** [comment]
Wrong chain id on https://chainlist.org/ for Godwoken is blocking our work to integrate Gnosis Safe (https://github.com/safe-global/safe-eth-py/pull/258). :(

image

For the testnet it should be: 71401, not 868455272153094 (old).

**Comment by Kuzirashi** [comment]
Replaced by: https://github.com/ethereum-lists/chains/pull/1205.

**Pull request closed without merging**
