### PR TITLE
Chiliz Chain Update

### PR DESCRIPTION
**Pull request by ersanyakit**
IVAR is a dead network. It no longer operates. 88888 is being used by the Chiliz network. Chain information has been updated.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Now that IVAR seems to be down since a month this has good chances to be merged - but you need to add redFlags reusedChainId

**Comment by ersanyakit** [comment]
> Now that IVAR seems to be down since a month this has good chances to be merged - but you need to add redFlags reusedChainId

Done.

**Review by ligi — CHANGES_REQUESTED** [review]
you cannot remove a chain - only mark it deprecated

**Comment by ersanyakit** [comment]
> you cannot remove a chain - only mark it deprecated

I updated its status to deprecated by adding it again. Thank you.

**Review by ligi — APPROVED** [review]

**Pull request merged**
