### PR TITLE
Add Gemuchain testnet support

### PR DESCRIPTION
**Pull request by 0xh3rtb3at**

### CODE REVIEW

**Comment by Orhanoguz3567** [comment]
Ol

**Comment by sdrozdkov** [comment]
Hi folks, pls run checks. It should works now.

**Comment by 0xh3rtb3at** [comment]
kindly bump
@Orhanoguz3567 pls check the PR

**Comment by 0xh3rtb3at** [comment]
bump

**Comment by heroesbattlearena** [comment]
@ligi kindly review please

**Pull request closed without merging**
