### PR TITLE
Fix Evmos Public RPC Listings

### PR DESCRIPTION
**Pull request by KagemniKarimu**
Lava in partnership with the Evmos team was  tasked with providing incentivized public RPC endpoints as the default RPC for Evmos ecosystem. This PR adds ipRPC endpoints to rpc lists on both `eip155-9000.json` (Evmos Testnet) and `eip155-9001.json` (Evmos Mainnet). This PR is a potential pre-requisite for upstream changes on chainlist.org.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Please add your new RPCs at the end of the list

**Comment by KagemniKarimu** [comment]
> Please add your new RPCs at the end of the list

Does it matter that Evmos team has requested that Lava be the default RPC for their chains? Will putting the links at the end as opposed to beginning of the array change their order of priority?

**Comment by ligi** [comment]
Do you have any link to that claim?

**Comment by danburck** [comment]
@ligi I'm Dan CPO at Altiplanic, the core contributor to the Evmos chain. The lava endpoints are delivering decentralized reliable RPC endpoints and should replace the existing default, due to their instability. This project also has been supported through the Encode Grants Programm on Evmos. 

We kindly ask to support them as the new default.

**Review by Ranahayat1122 — CHANGES_REQUESTED** [review]
Pushing

**Comment by danburck** [comment]
@ligi @Ranahayat1122 is there anything blocking this? We have many users who suffer with the current default endpoint from Blockdaemon as it is not reliable. 

Would appreciate, if we could merge this today.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by KagemniKarimu** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

I ran the linter. We should be good to go!

**Comment by danburck** [comment]
@ligi We'd really if we could speed this up and get the PR merged.  It's been three weeks and our users are still running into the same issue.

**Review by ligi — APPROVED** [review]

**Pull request merged**
