### PR TITLE
eip155-126 update to mainnet

### PR DESCRIPTION
**Pull request by nfttoken**
eip155-126 update to mainnet,  and want to apply chainID 125 for testnet.  Thank you.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
please resolve the conflicts

**Review by alirezaayande — APPROVED** [review]

**Comment by ligi** [comment]
@nfttoken I reviewed and you need to resolve the conflicts

**Comment by nfttoken** [comment]
> please resolve the conflicts

sorry, I am not conf

> @nfttoken I reviewed and you need to resolve the conflicts

sorry, i am not sure where the conflicts, could you mark it. I will modify it.

**Comment by ligi** [comment]
image

**Comment by nfttoken** [comment]
@ligi @alirezaayande   you are excellent， great job!

**Pull request merged**
