### PR TITLE
Create ambrosus.json

### PR DESCRIPTION
**Pull request by VoroninDima**

### CODE REVIEW

**Comment by VoroninDima** [comment]
> seems this file is not pinned somewhere? Also please add size fields

ready

**Comment by VoroninDima** [comment]
> seems this file is not pinned somewhere? Also please add size fields
i have changed the url to ipfs because previous url crashed the build

**Comment by ligi** [comment]
I still cannot get this file - where did you pin it?

**Review by Esweetsilascrypto7 — APPROVED** [review]
Nice one

**Comment by VoroninDima** [comment]
> I still cannot get this file - where did you pin it?
i`ve upload our logo to ipfs. Here is link https://ipfs.infura.io/ipfs/QmX14bNk3EDuEfzmFRJMFEbQ795JR3JjEbvu4cMsitrCGu. I set the url property to "ipfs://QmX14bNk3EDuEfzmFRJMFEbQ795JR3JjEbvu4cMsitrCGu". Sorry but i dont understand what file are you talking about. For image you need only .json file or i should send you .png too?

**Pull request closed without merging**
