### PR TITLE
modified rpc url

### PR DESCRIPTION
**Pull request by ericHwangMetabora**
modified rpc url in eip155-77001.json

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
elaborate on why - feels wrong to me

**Comment by ericHwangMetabora** [comment]
Hi, @ligi 
I would like to make sure that BORAchain users can send rpc requests through the specified .io domain.

**Comment by ericHwangMetabora** [comment]
Hi, @ligi 
I would like to receive the rpc request through the .io domain.
What kind of problem are you worried about?

**Comment by ericHwangMetabora** [comment]
.io and .com both ours.

**Pull request closed without merging**
