### PR TITLE
add omax mainnet

### PR DESCRIPTION
**Pull request by OMAXCHAIN**
This PR adds omax mainnet to chainlist. Please review. Thanks

### CODE REVIEW

**Comment by OMAXCHAIN** [comment]
@ligi

**Comment by OMAXCHAIN** [comment]
@ligi could you please review . Thank you

**Review by ligi — CHANGES_REQUESTED** [review]
Where did you pin Qmd7omPxrehSuxHHPMYd5Nr7nfrtjKdRJQEhDLfTb87w8G ? I cannot resolve it

**Review by robledo6 — APPROVED** [review]

**Comment by OMAXCHAIN** [comment]
> 
it's at https://ipfs.io/ipfs/Qmd7omPxrehSuxHHPMYd5Nr7nfrtjKdRJQEhDLfTb87w8G
It's resolving now.

**Comment by OMAXCHAIN** [comment]
@ligi

**Comment by ligi** [comment]
This CID you provided does not resolve
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

**Comment by OMAXCHAIN** [comment]
@ligi Done. Could you please review

**Comment by OMAXCHAIN** [comment]
@ligi

**Comment by OMAXCHAIN** [comment]
@ligi can you please look into now . Thank you

**Comment by OMAXCHAIN** [comment]
@ligi could you please review now.

**Review by ligi — APPROVED** [review]

**Pull request merged**
