### PR TITLE
add eip155-4691.json

### PR DESCRIPTION
**Pull request by dustinxie**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
https://nightly.iotexscan.io does not seem to exist

**Comment by dustinxie** [comment]
@ligi can you check the PR again? we set up the chain explorer, https://nightly.iotexscan.io/ is up and running now

**Comment by dustinxie** [comment]
@ligi could you check the PR again? thx

**Comment by dustinxie** [comment]
@ligi could you check the PR again? https://nightly.iotexscan.io/ is working now, thx

**Pull request closed without merging**
