### PR TITLE
Add Centrifuge, Altair, and their test nets

### PR DESCRIPTION
**Pull request by branan**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
RPC chainId (2031) does not match chainId from json (2032)

**Review by Heheehd — APPROVED** [review]

**Review by fukstyx1984 — APPROVED** [review]
👍

**Review by alokeutpal — APPROVED** [review]
Yes

**Comment by branan** [comment]
@ligi We've finally had time to fix our test network to report its own ID instead of mainnet's, and I've fixed the formatting issues that were reported. This should be good to re-run CI and merge

**Review by rorysan333 — APPROVED** [review]

**Review by ligi — APPROVED** [review]

**Comment by branan** [comment]
I've rebased again (and fixed prettier again, which I thought I did last time). Hopefully last time this all needs to run

**Comment by branan** [comment]
Bumping this again :eyes:

**Review by ligi — APPROVED** [review]

**Pull request merged**
