### PR TITLE
added kanazawa chain details

### PR DESCRIPTION
**Pull request by atmd83**
Added our Kanazawa test net

### CODE REVIEW

**Comment by atmd83** [comment]
@ligi yes thats correct, it's been requested to be set up but hasn't completed yet.
Is that a prerequisite of this getting in the list?

**Review by ligi — CHANGES_REQUESTED** [review]
I can't verify EIP3091 compatibility when the explorer is not reachable. You can remove the explorer if it does not work.

**Comment by ligi** [comment]
? it's still there - please do not waste my time - time is precious

**Comment by atmd83** [comment]
@ligi very sorry, not sure what happened there, can confirm its no longer showing in the PR

**Review by ligi — APPROVED** [review]

**Pull request merged**
