### PR TITLE
Add MXC zkEVM testnet

### PR DESCRIPTION
**Pull request by sheenhx**
Hey thanks!

### CODE REVIEW

**Comment by sheenhx** [comment]
Thanks just changed the logo

**Review by Amazinggrace07 — APPROVED** [review]

**Comment by applebeneRD** [comment]
thank you for this

**Comment by kingwill3** [comment]
No problem.

**Comment by sheenhx** [comment]
Hey thanks do you know when it will be merged?

**Review by ligi — APPROVED** [review]

**Pull request merged**
