### PR TITLE
Add Berachain Artio

### PR DESCRIPTION
**Pull request by dethebera**
🐻 🫶 
Add Berachain Artio Chain ID to chainlist 

Docs: https://docs.berachain.com/
Chain ID Reference: https://docs.berachain.com/developers/#add-the-network-manually

✅ Pre-PR Check 
./gradlew run 
BUILD SUCCESSFUL in 5s
8 actionable tasks: 3 executed, 5 up-to-date

### CODE REVIEW

**Review by yam3t3 — APPROVED** [review]

**Review by GrayFieth — APPROVED** [review]

**Comment by dethebera** [comment]
The reviewers mentioned above are not from the Berachain org, pls ignore.

**Comment by dethebera** [comment]
@ligi i reformatted using prettier for icon file, if there's anything else missing, please let me know.

**Comment by dethebera** [comment]
Hey @ligi possible to merge or let me know if there's still issues with the commit? 

I reformatted the icon details using a formatter. 

ty

**Comment by dethebera** [comment]
@ligi 

somewhere b/w merges correct link was reverted. 

my bad

pls re-run and merger. 

ty

**Pull request merged**
