### PR TITLE
new chain

### PR DESCRIPTION
**Pull request by mubeenafzalchattha**

### CODE REVIEW

**Comment by MubeenAfzal979** [comment]
nordek chain nrk

**Comment by MubeenAfzal979** [comment]
changed chain info

**Review by MubeenAfzal979 — COMMENTED** [review]
Nordek blockchain with nrk coin

**Comment by Savagesonly1** [comment]
#2361

**Review by MubeenAfzal979 — COMMENTED** [review]
Nordek mainnet

**Comment by Mohito62** [comment]
Hi

**Comment by Mikemfnb1** [comment]
I really don't know what to do

**Pull request closed without merging**
