### PR TITLE
xanachain info added

### PR DESCRIPTION
**Pull request by SalmanNoborderz**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Icon URL must be IPFS CID link

**Comment by SalmanNoborderz** [comment]
> Icon URL must be IPFS CID link

Sure I'll do that, what about the chainId as I can see that a chain with '8888' is already added?

**Comment by SalmanNoborderz** [comment]
@ligi please check if the URL is correct now

**Comment by ligi** [comment]
filename chainID does not match json

**Comment by SalmanNoborderz** [comment]
> filename chainID does not match json

@ligi  There is already a json file with chainId 8888 in its name, how can I resolve that?

**Comment by ligi** [comment]
https://github.com/ethereum-lists/chains#collision-management

**Comment by SalmanNoborderz** [comment]
> https://github.com/ethereum-lists/chains#collision-management

@ligi so how should I add info for XANAChain here, do I edit the otherone? otherwise the filename and chainId won't match

**Pull request closed without merging**
