### PR TITLE
Add Highbury Network

### PR DESCRIPTION
**Pull request by sudopunk**

### CODE REVIEW

**Comment by sudopunk** [comment]
linted and updated

**Comment by sudopunk** [comment]
@ligi The icon link seems to resolve fine but the asset file isn't passing validation. So I have updated the 'bafy' hash instead.

**Comment by sudopunk** [comment]
@ligi I hope everything's in order. Please take it forward. Thanks.

**Comment by sudopunk** [comment]
The IPFS hash is resolving as intended when using it with the link in the validation script.

**Review by ligi — APPROVED** [review]

**Pull request merged**
