### PR TITLE
Added Vanguard and Vanar Mainnet

### PR DESCRIPTION
**Pull request by hussamBim**

### CODE REVIEW

**Comment by hussamBim** [comment]
It seems like all tests have passed, and the provided information is accurate. Could you please take a look at my pull request (PR) for confirmation?

Screenshot 2024-01-11 at 10 03 47 AM

**Comment by hussamBim** [comment]
@ligi can you please mention which change needs to be done?

**Comment by hussamBim** [comment]
added new lint at the end of files.

**Comment by hussamBim** [comment]
@ligi any estimated time on this?

**Comment by hussamBim** [comment]
@ligi how much time it will take to merge ?

**Comment by hussamBim** [comment]
@ligi all check are passed. daily it says to update branch. can you please review our PR?

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by hussamBim** [comment]
@ligi We need to reserver 2024 for our mainnet in advance is there anything for that?

**Comment by hussamBim** [comment]
@ligi i have removed the mainnet files can you appove it for testnet?

**Comment by hussamBim** [comment]
@ligi can you please review now i have done the required changes.

**Comment by hussamBim** [comment]
@ligi can you please check the PR now?

**Comment by hussamBim** [comment]
@ligi its very urgent for us can you please re-view this.

**Comment by hussamBim** [comment]
> image

@ligi this issue is resolved can you please have a look at this?

**Comment by anischohan** [comment]
> image

Hey @ligi we have updated our block explorer urls and details. Do let me know if you have problems approving this request.

**Pull request closed without merging**
