### PR TITLE
Apex Fusion Nexus Testnet

### PR DESCRIPTION
**Pull request by AlejandroAFF**
Registration of Apex Fusion Nexus Testnet chain

### CODE REVIEW

**Comment by AlejandroAFF** [comment]
Hi @ligi, we've fixed the formatting, could you check again?

**Comment by AlejandroAFF** [comment]
Hi @ligi, I just added EOL at the end of the json file. Now, everything should work! Thanks a lot!!

**Comment by dcejtlin-apex** [comment]
Hi @ligi , sorry for the inconvenience, seems like [github had issues](https://www.githubstatus.com/incidents/2qxyr481ywxf) and our prettier review didnt pass because of a timeout:

https://github.com/ethereum-lists/chains/actions/runs/10370292728/job/28707855726

Could you please run the checks again?

**Comment by AlejandroAFF** [comment]
Hi @ligi , it looks like we solved the issue as we passed the first validation. Thanks for your support

**Review by ligi — APPROVED** [review]

**Pull request merged**
