### PR TITLE
add: canto testnet

### PR DESCRIPTION
**Pull request by jessepinkman9900**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `CANTO` more than once

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `CANTO` more than once

**Comment by jessepinkman9900** [comment]
@ligi bump

**Comment by ligi** [comment]
@jessepinkman9900 short name is still not unique ..

**Comment by jessepinkman9900** [comment]
@ligi my bad i thought it symbol was the issue. have fixed short name as well

**Review by ligi — CHANGES_REQUESTED** [review]
still collides with eip155-740.json

**Comment by jnsdls** [comment]
according to the CANTO docs they're "migrating" to this new chain: https://docs.canto.io/evm-development/testnet

@ligi in such a case is my assumption correct that the correct approach would be to:
- create a new shortname for this new entry (unanbiguous)
- mark the old chain (eip155-740 in this case) as `deprecated` status

submit a PR that does both on one go?

If so maybe @jessepinkman9900 can make this change in this PR, otherwise I'm happy to submit one today that makes these changes.

**Comment by jessepinkman9900** [comment]
@ligi  @jnsdls 
have updated 740 as deprecated & fixed 7701 short-name

**Pull request merged**
