### PR TITLE
Create eip155-49049.json

### PR DESCRIPTION
**Pull request by cristianopolicarpo**

### CODE REVIEW

**Comment by cristianopolicarpo** [comment]
I would like to propose the inclusion of Wireshape Testnet Floripa.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also: missing field(s) [faucets]

**Comment by Ahmednoshy** [comment]
C

**Comment by cristianopolicarpo** [comment]
Json file was updated

**Review by ligi — APPROVED** [review]

**Pull request merged**
