### PR TITLE
Add Zether Chain ID

### PR DESCRIPTION
**Pull request by ZetherWiz**
Add Zether Chain ID

### CODE REVIEW

**Comment by ZetherWiz** [comment]
Fixed image.

**Review by ligi — CHANGES_REQUESTED** [review]
CI still failing - fix these errors

**Comment by ZetherWiz** [comment]
IPFS link of image is correct: https://ipfs.io/ipfs/QmZwdhRze34c3synJSp6QNv5zSpMiQf7DZS3N16HxGuzGh

**Review by ligi — CHANGES_REQUESTED** [review]
please do not request a review if you do not address the problems

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Review by ligi — APPROVED** [review]

**Pull request merged**
