### PR TITLE
Add Electra Network and Electra Test Network chain configurations

### PR DESCRIPTION
**Pull request by safuapy**
# Add Electra Network and Testnet

## Description
This PR adds support for Electra Network (ELC) and its corresponding testnet to the chainlist.

### Electra Network (Chain ID: 861)
- Native token: ELC (Electra)
- RPC: https://rpc.elcscan.com
- Explorer: https://www.elcscan.com

### Electra Testnet (Chain ID: 871)
- Native token: TELC (Test Electra)
- RPC: http://rpc.testnet.elcscan.com
- Explorer: https://scan.testnet.elcscan.com

## Checklist
- [x] Added mainnet configuration (eip155-861.json)
- [x] Added testnet configuration (eip155-871.json)
- [x] Followed JSON format guidelines
- [x] Verified unique chain IDs
- [x] Included explorer URLs
- [x] Provided RPC endpoints

### CODE REVIEW

**Comment by irajsava** [comment]
- [ ] []()_[]()_

**Comment by irajsava** [comment]
> You successfully submitted a PR! Due to the amount of PRs coming in: we will only look at PRs that the CI is happy with. We can also not hold your hand getting the CI green - just look how others that where merged did it and RTFM. So as long as there is any CI check that reports an error - no human will look at this. You might be able to ask for some support after supporting the project - e.g. by sending funds to lists.eth. When you fixed things after a requested change - then you also need to (re-)request a review.

**Comment by safuapy** [comment]
Please do not merge we have to change the domain name

**Comment by safuapy** [comment]
SHIP IT! 🚢

**Review by ligi — APPROVED** [review]

**Pull request merged**
