### PR TITLE
redFlags reusedChainId for SCAI

### PR DESCRIPTION
**Pull request by solidityx**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
you need to add redFlags reusedChainId

**Comment by solidityx** [comment]
> you need to add redFlags reusedChainId

Can you please tell me how exactly I can add redFlags reusedChainId? Ty

**Comment by ligi** [comment]
see e.g. https://github.com/ethereum-lists/chains/blob/ce084497a6677aa95d3bbd9393d230761b0b68ce/_data/chains/eip155-24.json#L14

**Comment by dwarkesh8** [comment]
Is that okay now? Let me know Please :)

**Comment by solidityx** [comment]
Is that all okay now? Since I've added  redFlags reusedChainId as per your suggestion. Let me know if anything else required from my side. Thanks

**Comment by Romantix2** [comment]
Kullanıcı adı ***@***.*** pasword Tt812660  ne yapmış işlem
bilincli değil yziyorsun ama anlamıyorum gir hallet sen

21 Eki 2023 Cmt 04:16 tarihinde ligi ***@***.***> şunu yazdı:

**Pull request merged**
