### PR TITLE
Add Movement Chains

### PR DESCRIPTION
**Pull request by 0xPrimata**
Add Movement Legacy, Movement Devnet, Movement Testnet and Movement Mainnet.

### CODE REVIEW

**Comment by 0xPrimata** [comment]
Hey there @ligi , build fails because some of the endpoints are still not live. Since these are chains we are incubating, are those required functional endpoints or should we leave those fields blank for the time being?

**Comment by ligi** [comment]
blank

**Comment by 0xPrimata** [comment]
@ligi fixed, appreciate the help.

**Comment by 0xPrimata** [comment]
fixed issue @ligi , apologies.

**Pull request merged**
