### PR TITLE
Create eip155-968.json

### PR DESCRIPTION
**Pull request by cqcwasd**
Add Waltonchain Mainnet

### CODE REVIEW

**Review by cqcwasd — COMMENTED** [review]
modify chainid:968

**Review by cqcwasd — COMMENTED** [review]
modify chainID:968
./gradlew run
BUILD SUCCESSFUL in 39s

**Comment by cqcwasd** [comment]
Exception in thread "main" java.lang.IllegalStateException: RPC chainId (15) does not match chainId from json (968)

**Comment by cqcwasd** [comment]
Exception in thread "main" java.lang.IllegalStateException: RPC chainId (15) does not match chainId from json (968)

**Comment by cqcwasd** [comment]
“Exception in thread "main" java.lang.IllegalStateException: RPC chainId (15) does not match chainId from json (968)“                   My chainid and network should both be 15, but I found that there is already eip55-15 in it, please tell me how to do it.

**Comment by Savagesonly1** [comment]
NASDAQIXID

**Pull request closed without merging**
