### PR TITLE
Add Hertz Network Chain.

### PR DESCRIPTION
**Pull request by htz-zendx**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The Icon hertz does not exist - was used in eip155-26600.json

**Comment by htz-zendx** [comment]
> The Icon hertz does not exist - was used in eip155-26600.json

Updated icon references.

**Review by ligi — COMMENTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also:

 width in json (../_data/icons/hertz-network.json) is 200 but actually is in imageDownload 162

**Comment by denizturgut** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`
> 
> also:
> 
> width in json (../_data/icons/hertz-network.json) is 200 but actually is in imageDownload 162

Updated

**Review by ligi — CHANGES_REQUESTED** [review]
width in json (../_data/icons/hertz-network.json) is 162 but actually is in imageDownload 129

**Comment by htz-zendx** [comment]
> width in json (../_data/icons/hertz-network.json) is 162 but actually is in imageDownload 129

In your previous comment, you mentioned imageDownload was 162. Is it possible for the imageDownload size to change?

**Comment by ligi** [comment]
width<>height

image

**Comment by htz-zendx** [comment]
> width<>height
> 
> image

Thanks for clarifying. Fixed!

**Pull request merged**
