### PR TITLE
Janus Network Testnet added

### PR DESCRIPTION
**Pull request by ulgacemre**
Hey,

Could you please add Janus Network testnet?

Thanks.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
https://explorer.testnet.janusnetwork.io is not working

**Comment by ulgacemre** [comment]
@ligi  I just fixed the issues. Thanks

**Review by ulgacemre — COMMENTED** [review]
Updated based on the request

**Review by ligi — CHANGES_REQUESTED** [review]
Still can't access the explorer

**Comment by ligi** [comment]
ah - just see you changed the explorer URL

**Pull request merged**
