### PR TITLE
add DeBank Testnet

### PR DESCRIPTION
**Pull request by cryptocifer**

### CODE REVIEW

**Review by Qmig — COMMENTED** [review]
Ok

**Review by ligi — CHANGES_REQUESTED** [review]
rebase to master

**Review by ligi — CHANGES_REQUESTED** [review]
also short name cannot be empty

**Review by ligi — CHANGES_REQUESTED** [review]
name must be unique - but found `DEBANKTESTNET` more than once

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Review by ligi — CHANGES_REQUESTED** [review]
name must be unique - but found `DEBANKTESTNET` more than once

Please do not submit chainIDs that you do not use - we cannot delete chains as we need to protect users from replay attacks

**Review by ligi — APPROVED** [review]

**Pull request merged**
