### PR TITLE
Updating Nordek Mainnet

### PR DESCRIPTION
**Pull request by sounxk**

### CODE REVIEW

**Comment by Cripdalocc** [comment]
no thanks

INeedAVault

**Comment by Cripdalocc** [comment]
I need help removing all the phish and firmware and Ransome rare and all
the stalking applications and plugins

INeedAVault

**Review by ligi — CHANGES_REQUESTED** [review]
The error is quite clear:

explorer standard must be 'none' or 'EIP3091'

not sure why you entered 721 as an explorer standard ..

**Review by ligi — APPROVED** [review]

**Comment by armandRobled** [comment]
https://www.armandorobleee.com/patch

**Pull request merged**
