### PR TITLE
Add  ChainId 2559 for kortho mainnet

### PR DESCRIPTION
**Pull request by Eric0718**
{
    "name": "Kortho Mainnet",
    "chain": "Kortho Chain",
    "network": "mainnet",
    "rpc": [
        "https://www.kortho-chain.com"
    ],
    "faucets": [
    ],
    "nativeCurrency": {
    "name": "KorthoChain",
    "symbol": "KTO",
    "decimals": 11
    },
    "infoURL": "https://www.kortho.io/",
    "shortName": "Kortho",
    "chainId": 2559,
    "networkId": 2559
}

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The short names must be unique

**Comment by Eric0718** [comment]
Hi @ligi,please try again.Thanks.

**Comment by ligi** [comment]
the short names are still the same

**Comment by Eric0718** [comment]
Hi @ligiSorry，please try again.Thanks.

**Comment by Eric0718** [comment]
@ligi，Sorry, I didn't realize the Pr, I just changed the file. It should be all right this time.

**Comment by Eric0718** [comment]
Hi @ligi ，is this modification OK?

**Comment by ligi** [comment]
I do not see a change

**Pull request merged**
