### PR TITLE
Updated Chain ID for ShimmerEVM Testnet

### PR DESCRIPTION
**Pull request by anistark**
Recently due to certain conditions this testnet chain was reset and resulted in a change in Chain ID.
Also, fixing a mistake on decimals from before.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
You cannot just delete a chain - you need to deprecate the old one and add the new one

**Comment by anistark** [comment]
> You cannot just delete a chain - you need to deprecate the old one and add the new one

Ah I see. How to deprecate a chain?

**Comment by ligi** [comment]
"status" : "deprecated"

**Review by ligi — CHANGES_REQUESTED** [review]
RPC chainId (1072) does not match chainId from json (1071)

you might need to remove the RPCs from the deprecated chains if you reuse the same addresses

**Comment by ligi** [comment]
please also rename one of the shortnames - so they are unique

**Review by ligi — APPROVED** [review]

**Pull request merged**
