### PR TITLE
Dis

### PR DESCRIPTION
**Pull request by FranckStone**

### CODE REVIEW

**Comment by FranckStone** [comment]
change name

**Review by ligi — CHANGES_REQUESTED** [review]
The other chain still seems to be active

**Comment by FranckStone** [comment]
dis and ethf just switch names, the data is consistent. The rpc link of ethf and dis are the same node, just so that the previous users will not be directly disconnected.

**Comment by FranckStone** [comment]
I can now stop the ethf link, but many users still need to modify the link, so it has not been closed.

**Pull request closed without merging**
