### PR TITLE
update logo

### PR DESCRIPTION
**Pull request by nova-network-inc**
update logo ipfs

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Where did you pin the CID? I cannot resolve it

**Comment by nova-network-inc** [comment]
I've used Pinata Cloud to pin it, and it's working here when I query via HTTP through their public gateway https://gateway.pinata.cloud/ipfs/QmeFaJtQqTKKuXQR7ysS53bLFPasFBcZw445cvYJ2HGeTo Also have the URL for the file hosted at our website if it is of any help https://novanetwork.io/wp-content/uploads/2022/07/RD-512NNeb.png

**Comment by nova-network-inc** [comment]
> Where did you pin the CID? I cannot resolve it

Any news on this?

**Comment by nova-network-inc** [comment]
> Where did you pin the CID? I cannot resolve it

Hi Ligi, can we have this looked at please? Passed in all checks, and it's working fine in here. Cheers.

**Review by ligi — APPROVED** [review]

**Pull request merged**
