### PR TITLE
add new chain

### PR DESCRIPTION
**Pull request by FiboChain**
Support Fibonacci Chain

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Review by efateva — COMMENTED** [review]
prettierd

**Review by efateva — APPROVED** [review]
prettierd

**Comment by FiboChain** [comment]
Hello,@ligi ! Can you help to approve this workflow?

**Review by ligi — APPROVED** [review]

**Pull request merged**
