### PR TITLE
eip155-1011, eip155-3033 added chainIDs for Rebuschain

### PR DESCRIPTION
**Pull request by nicolam1**
Added configuration for Rebuschain mainnet and testnet

### CODE REVIEW

**Comment by nicolam1** [comment]
@ligi Can you please approve the workflows. Thank you

**Review by Jess25051980 — APPROVED** [review]

**Review by Jess25051980 — APPROVED** [review]

**Comment by pierstab** [comment]
@ligi everything now should be ok, may you approve  the workflow. thank you

**Comment by nicolam1** [comment]
@ligi can you please approve the workflow we should be good to go now. Thank you

**Comment by nicolam1** [comment]
@ligi, sorry to bother you about this, but the build step is failing. It says that the icon we added to this PR is unreferenced, but we do have it referenced in the icon file. Do you have any suggestions on how to fix this?

**Comment by ligi** [comment]
Your PR is wrong - I can fix it for you if you send some funds to lists.eth

**Comment by pierstab** [comment]
@ligi PR now should be ok

**Comment by nicolam1** [comment]
@ligi can we get a run of the workflow please?

**Review by ligi — APPROVED** [review]

**Pull request merged**
