### PR TITLE
change xpla:3701 <-> SeedCoin-Network:37.

### PR DESCRIPTION
**Pull request by park1847**
change xpla:3701 <-> SeedCoin-Network:37.
SeedCoin-Network deprecated.

I want to use the chainId 37 used by SeedCoin-Network as XPLA.
All sites related to SeedCoin-Network are inaccessible.
"infoURL": "https://www.seedcoin.network/"
"rpc": ["https://node.seedcoin.network"]

thank you

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
why is 3701 now seedcoin?

**Comment by park1847** [comment]
> why is 3701 now seedcoin?

When I changed 37 to xpla, a build error occurred saying that the icon of the existing seed coin was not used.
So I moved the seed coin to 3701.

**Comment by ligi** [comment]
this is BS - delete the icon then
please do not provide wrong information

**Comment by park1847** [comment]
> this is BS - delete the icon then please do not provide wrong information

sorry 😅

**Pull request merged**
