### PR TITLE
Create eip155-11119.json

### PR DESCRIPTION
**Pull request by Hashbit-hbit**
hopefully it now fine

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
filename is wrong

**Comment by Hashbit-hbit** [comment]
Hello.
how do i name the file.?
kindly give me the steps.

**Comment by ligi** [comment]
no

**Comment by Hashbit-hbit** [comment]
how should it be?

**Comment by ligi** [comment]
please just look at the other chains

**Comment by Hashbit-hbit** [comment]
Is it fine now?

**Comment by ligi** [comment]
no

**Comment by Hashbit-hbit** [comment]
give me an example of how it should look like.

**Comment by Hashbit-hbit** [comment]
What about now? Is it fine?

**Review by ligi — COMMENTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also: The Icon hashbit does not exist - was used in eip155-11119.json

**Comment by PaulinaParangerHr** [comment]
Try as soon as well enough

**Pull request closed without merging**
