### PR TITLE
remove Harmony shards 2 and 3 due to HIP30, reason - https://talk.harmony.one/t/hip30v2-update-announcement/23268

### PR DESCRIPTION
**Pull request by mur-me**
Hello chains maintainers,

Harmony decided to shutdown shards 2 and 3, due to this I want to remove both of them.

Source: https://talk.harmony.one/t/hip30v2-update-announcement/23268

### CODE REVIEW

**Comment by sophoah** [comment]
official announcement https://x.com/harmonyprotocol/status/1720202529588527495?s=20

**Review by sophoah — APPROVED** [review]

**Comment by mur-me** [comment]
Hi @ligi, 

Sorry for bothering you, but can you be so kindly and merge this one? :pray:

**Review by ligi — CHANGES_REQUESTED** [review]
No - this will not be merged like this - you cannot delete chains - you can only mark them deprecated

**Comment by mur-me** [comment]
@ligi fixed, thanks!

**Review by ligi — APPROVED** [review]

**Pull request merged**
