### PR TITLE
Add Fahrenheit Chain Mainnet

### PR DESCRIPTION
**Pull request by fahrenheitchain**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Where did you pin QmQzy1VbWvdLew6xCJEccAQNSfc7Tgr43ULgxWWyxtgNaH - I cannot resolve it

**Comment by fahrenheitchain** [comment]
Hi @ligi , please review again and merge. Thank you!

**Comment by fahrenheitchain** [comment]
@ligi Please review again and merge

**Review by ligi — CHANGES_REQUESTED** [review]
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

**Comment by ligi** [comment]
still cannot resolve your CID ..

**Comment by fahrenheitchain** [comment]
@ligi I added binary icon to iconDownload, and pin the image in Filebase (instead of pinata). Please review again.

**Review by AlAstor66767 — CHANGES_REQUESTED** [review]
1

**Pull request closed without merging**
