### PR TITLE
Add chain 1080 2

### PR DESCRIPTION
**Pull request by yoheinishikubo**
Created _data/chains/eip155-1080.json to add Mintara Mainnet network to the chain list.
Created _data/icons/mintara.json for linking the official icon.

### CODE REVIEW

**Review by 357SANDIIIP — APPROVED** [review]

**Comment by yoheinishikubo** [comment]
@357SANDIIIP Thank you for approving this.

**Review by ligi — CHANGES_REQUESTED** [review]
explorer is not working 
image

**Comment by yoheinishikubo** [comment]
@ligi Thank you for your help not only with this PR but also with another one.
The explorer is still under development.
Can I ask which is better to update the file with no definition for explorers or wait for the launch of the explorer?

**Comment by ligi** [comment]
for me it is easier/less work if you wait for the launch of the explorer - but both options are possible. I just will not merge with a failing link

**Comment by yoheinishikubo** [comment]
@ligi Thank you for your help.
We just made the explorer https://subnets.avax.network/mintara work.
It's appreciated to merge this PR.

**Review by sennhann29 — COMMENTED** [review]
👍👍🍭

**Pull request merged**
