### PR TITLE
Add TBSI networks

### PR DESCRIPTION
**Pull request by kitt-tientanopajai**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
missing field(s) [faucets]
it can be an empty array

**Review by kophyo1234 — APPROVED** [review]

**Comment by kitt-tientanopajai** [comment]
please review the changes.

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `TBSI` more than once

**Comment by kitt-tientanopajai** [comment]
duplicated short name fixed, please review.

**Review by ligi — APPROVED** [review]

**Pull request merged**
