### PR TITLE
Update Chain 7001 - ZetaChain Athens Testnet

### PR DESCRIPTION
**Pull request by CharlieMc0**
Updated the RPC endpoints and icon for ZetaChain Athens Testnet

### CODE REVIEW

**Comment by CharlieMc0** [comment]
Not sure why the checks are failing. Let me know what I need to change to get them to pass.

**Review by ligi — CHANGES_REQUESTED** [review]
Explorer have url starting with https:// or http://

**Review by Amirmortazavi61 — APPROVED** [review]

**Comment by CharlieMc0** [comment]
Fixed all the issues. Thanks!

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot reach https://zetachain-athens-3.blockscout.com

**Comment by CharlieMc0** [comment]
https://zetachain-athens-3.blockscout.com isn't online yet so I've removed it for now. We'll update in a new PR later once it is online.

**Review by ligi — APPROVED** [review]

**Pull request merged**
