### PR TITLE
EIP155-198

### PR DESCRIPTION
**Pull request by sexdefi**
BitSwap - A next evolution DeFi exchange on BitChain.
Cheaper and faster than Uniswap.  Discover BitSwap, the leading DEX on Base.

### CODE REVIEW

**Comment by sexdefi** [comment]
Thanks

**Review by ligi — CHANGES_REQUESTED** [review]
RPC chainId (2023) does not match chainId from json (198)

**Comment by sexdefi** [comment]
Thanks . I already change THE RPC endpoint ChainId(2023) to 198 .

**Review by ligi — APPROVED** [review]

**Comment by sexdefi** [comment]
thanks a lot

**Pull request merged**
