### PR TITLE
Changing vanguard currency symbol

### PR DESCRIPTION
**Pull request by hussamBim**
Changing vanguard currency symbol

### CODE REVIEW

**Comment by hussamBim** [comment]
@hussamBim then how we can change our symbol?

**Comment by hussamBim** [comment]
@ligi how we can update our currency symbol?

**Comment by hussamBim** [comment]
@ligi its very urgent for us to change this symbol. Please have a look at this.

**Comment by ligi** [comment]
https://github.com/ethereum-lists/chains/pull/4421#issuecomment-1964141368

**Comment by hussamBim** [comment]
@ligi now thing or previous state? or can you be more specific about 
please back up this change?

**Comment by ligi** [comment]
some official thing stating the change

**Comment by hussamBim** [comment]
@ligi We're seeking the identical adjustments outlined in our official links to avoid confusion for end-users. Please refer to this link https://faucet.vanarchain.com/ for the specific modifications, as we aim to maintain consistency in symbols between the chain link and our sites

**Comment by hussamBim** [comment]
@ligi can you suggest further steps?

**Comment by hussamBim** [comment]
@ligi because you said to redo the change.

**Pull request closed without merging**
