### PR TITLE
Add eip155-62621.json for MultiVAC mainnet

### PR DESCRIPTION
**Pull request by 0x13e**
I would be grateful if the MultiVAC chain could be added. The current explorer is custom, but a possible blockscout instance and integration with sourcify.eth in the near future.

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Comment by Binary178** [comment]
How do I add a new network to my metamast account

**Review by Binary178 — COMMENTED** [review]
I will be greatfull if polygon could be added

**Comment by Stanley114** [comment]
The process is hard 
Send me your WhatsApp number so we can chat

**Comment by Binary178** [comment]
On Mon, Apr 25, 2022 at 5:02 AM, Stanley114

07021331540

**Comment by Stanley114** [comment]
Your number is not on WhatsApp

**Comment by Binary178** [comment]
+2349021331540

**Pull request merged**
