### PR TITLE
Adding Eleanor Metatime Testnet

### PR DESCRIPTION
**Pull request by metatimeofficial**

### CODE REVIEW

**Comment by AranTrx** [comment]
Good project

**Comment by joysarkee** [comment]
Good

**Comment by Nuradde** [comment]
Good project

**Comment by Nuradde** [comment]
Go

**Comment by gmoni1981** [comment]
Great project

**Review by gmoni1981 — COMMENTED** [review]
Great

**Comment by ID098** [comment]
Great what,i can't to verification whit github,when i verifi in the web,so
be error,bit did do all task,how to fix this ?

Pada tanggal Jum, 30 Jun 2023 23.03, gmoni1981 ***@***.***>
menulis:

**Pull request closed without merging**
