### PR TITLE
Update AlveyChain RPC

### PR DESCRIPTION
**Pull request by devorso**
Here is the new RPC of Alveychain with new changes.

### CODE REVIEW

**Comment by dglw** [comment]
@ligi looks latest changes failed because of ipfs link was broken, we updated with last push, could you check?

**Comment by dglw** [comment]
@ligi could you check again? we checked the required status errors but looks it was checked old icon address.

**Comment by dglw** [comment]
@ligi check status says "No newline at end of file" but we have actually, can you check if it is possible to fix that issue? i cant find the difference on formatting.

**Comment by dglw** [comment]
thanks, we just did. could you check now?

**Comment by dglw** [comment]
@ligi hey, 
It says failed on build about icon. But that icon url is old one, we already changed with new ipfs url with our commit. Could you check?
image

image

**Review by tilemanrenovations — COMMENTED** [review]
IMG_2193
IMG_2190
f7be5950-441d-4b3f-ae9e-693c4dc5158e

**Comment by dglw** [comment]
@ligi all changes done, can you check?

**Review by ligi — APPROVED** [review]

**Pull request merged**
