### PR TITLE
Add HashKey Chain Testnet Chainid

### PR DESCRIPTION
**Pull request by HashKeyCloud**
Apply for HashKey Chain Testnet Chainid first then update rpc links and explorer link

### CODE REVIEW

**Review by tangjeff1995 — APPROVED** [review]

**Review by tangjeff1995 — APPROVED** [review]

**Review by tangjeff1995 — APPROVED** [review]

**Review by tangjeff1995 — APPROVED** [review]

**Review by tangjeff1995 — APPROVED** [review]

**Review by tangjeff1995 — APPROVED** [review]

**Comment by HashKeyCloud** [comment]
@gyllone the author of eip155-230315.json

**Comment by vehicles4real** [comment]
add key to me.

**Comment by HashKeyCloud** [comment]
> add key to me.

sorry, what key?

**Comment by vehicles4real** [comment]
Nope

**Pull request merged**
