### PR TITLE
Add Crystaleum💎

### PR DESCRIPTION
**Pull request by billaure-crystaleum**
Crystaleum main net is already working.

### CODE REVIEW

**Comment by billaure-crystaleum** [comment]
Ready for merge

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot `ìpfs get ` ipfs://Qmbry1Uc6HnXmqFNXW5dFJ7To8EezCCjNr4TqqvAyzXS4h - did you pin it on a public node?

**Comment by billaure-crystaleum** [comment]
Good eye! Thanks. 

Pinning on local ipfs node.

**Comment by billaure-crystaleum** [comment]
Will update my PR

**Comment by billaure-crystaleum** [comment]
Pinned, this PR is ready for merge now. Thanks

**Comment by shopglobal** [comment]
Hi @ligi could we get this merged? Thanks, M

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
Please consider contributing to our grant: https://gitcoin.co/grants/2974/ethereum-lists

**Pull request merged**
