### PR TITLE
Add WhiteBIT Network testnet

### PR DESCRIPTION
**Pull request by john-whitebit**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
seems your svg is no good: The attribute "offset" of the element <stop> is required

**Review by MOMMABEAR5 — COMMENTED** [review]
Request

**Comment by john-whitebit** [comment]
@ligi Hello. Uploaded corrected version. Thank you!

**Comment by Hashgong** [comment]
> seems your svg is no good: The attribute "offset" of the element <stop> is required

Can you help??idont know what to do & where should I start

**Review by andrewh112 — APPROVED** [review]

**Comment by ccxdev** [comment]
@ligi could you check it please ?)

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Review by ligi — APPROVED** [review]

**Pull request merged**
