### PR TITLE
Add Shape testnet definition

### PR DESCRIPTION
**Pull request by good-shape**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
the website does not seem to work - also please chime into #5474

**Comment by good-shape** [comment]
> the website does not seem to work - also please chime into #5474

The website is behind an auth wall but will be open in the next week. Happy to hold off on merging until then if required but want to ensure the chain id is properly reserved at least

And thanks will chime in there shortly!

**Comment by good-shape** [comment]
> the website does not seem to work - also please chime into #5474

The website is public now @ligi!

**Comment by good-shape** [comment]
Closed in favour of https://github.com/ethereum-lists/chains/pull/5576

**Pull request closed without merging**
