### PR TITLE
Add Oasys testnet

### PR DESCRIPTION
**Pull request by degiatenish**

### CODE REVIEW

**Review by Atrius83 — COMMENTED** [review]
Nice

**Comment by greatdex** [comment]
@ligi Hi, please merge this

**Comment by degiatenish** [comment]
@ligi Is there anything I need to fix?

**Comment by sickhye** [comment]
@ligi 
it's crucial for our project that this PR gets merged. Please take a look when you can.

**Review by ligi — APPROVED** [review]

**Pull request merged**
