### PR TITLE
Adding XODEX network

### PR DESCRIPTION
**Pull request by xo-dex**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Why do you commit httpsloader/bin/main/org/ethereum/lists/chains/https/Chain.kt
please do not

**Comment by xo-dex** [comment]
Oops, missed that. Removed

**Review by xo-dex — COMMENTED** [review]
Fixed

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by xo-dex** [comment]
I have completed all the above. Please let me know if any more changes are required

**Review by ligi — APPROVED** [review]

**Pull request merged**
