### PR TITLE
Add Magnet Chain

### PR DESCRIPTION
**Pull request by y19818**

### CODE REVIEW

**Comment by y19818** [comment]
Why has there been no action or been checked?

**Comment by y19818** [comment]
@ligi Hi The team is getting ready to deploy and announce the TestNet. Could you please trigger the CI, I think it should pass this time.

**Comment by y19818** [comment]
@ligi Hello, I made the modification using prettier and it should pass.

**Review by alanaladd21 — COMMENTED** [review]
release funds

**Pull request merged**
