### PR TITLE
Registering Odyssey Testnet

### PR DESCRIPTION
**Pull request by dreamdev2427**
I pushed icon information to icon folder again, so as a subsequence operation I am creating this PR.

### CODE REVIEW

**Comment by dreamdev2427** [comment]
I have pushed odyssey.json and odysseyscan.json again, and passed building successfully.
Would you try mergy?

**Comment by dreamdev2427** [comment]
How are you @ligi ?
Would you kindle check this PR again and merge this?

**Comment by dreamdev2427** [comment]
Thank you for your effort.
Would you kindly let me know why this error happens?
"> Task :processor:run FAILED
checking single chain _data/chains/eip155-131313.json
Exception in thread "main" java.lang.IllegalStateException: The Icon oddyseyscan does not exist - was used in eip155-131313.json
	at org.ethereum.lists.chains.MainKt.processIcon(Main.kt:480)
	at org.ethereum.lists.chains.MainKt.checkChain(Main.kt:329)
	at org.ethereum.lists.chains.MainKt.main(Main.kt:40)

FAILURE: Build failed with an exception."

**Comment by dreamdev2427** [comment]
I have removed odysseyscan information form eip155-131313.json and try build and passed it, so I pushed code again.
@ligi  Would you kindly merge my PR again?

**Comment by dreamdev2427** [comment]
@ligi How are you?
Would you kindly check this PR again for merge?

**Comment by dreamdev2427** [comment]
I have checked the building error again, and I have removed unused oddyseyscan.json.
@ligi Thank you for your effort.
Would you kindly try merge again?

**Comment by dreamdev2427** [comment]
@ligi How are you?
Would you kindly merge again?

**Comment by dreamdev2427** [comment]
image
Would you kindly tell me and kndly teach me about fixing the format?

**Comment by dreamdev2427** [comment]
@ligi Would you tell me the way of fix the error with standard format data?

**Comment by dreamdev2427** [comment]
Would you kindly give me the standard format of the chain information?

**Comment by dreamdev2427** [comment]
@ligi How are you?
I think I have updated chain information in the correct format.
Would you kindly try merge again?

**Comment by dreamdev2427** [comment]
@ligi Where do I should fund?
Would you tell me the way of pass the 4th checking?

**Comment by dreamdev2427** [comment]
@ligi Would you let me know how can I pass?

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by dreamdev2427** [comment]
Thank you @ligi
I will sun the prettier and comment again.

**Comment by dreamdev2427** [comment]
I have run the prettier on my end and pushed well formatted json files again.
@ligi Would you try merge it again?

**Review by ligi — CHANGES_REQUESTED** [review]
remove the gitpod file

**Comment by dreamdev2427** [comment]
How are you @ligi ?
Would you merge my code to the main branch?

**Comment by dreamdev2427** [comment]
Ah, yest, I will remove gitpod file.

**Comment by dreamdev2427** [comment]
@ligi
How are you?
I have removed gitpod file.
Would you kindly merge my PR to the main branch?

**Review by ligi — APPROVED** [review]

**Comment by dreamdev2427** [comment]
Thank you for your efforts. @ligi
I have a  more question.
I still can not see our Odyssey testnet on chainlist.org website.
Is there any more work do I have to do?

**Pull request merged**
