### PR TITLE
Deprecate Neon EVM Testnet

### PR DESCRIPTION
**Pull request by mnedelchev-vn**
Deprecating [Neon EVM Testnet](https://chainlist.org/chain/245022940)

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Deleting is not how you deprecate - instead you need to set the deprecated flag

**Comment by mnedelchev-vn** [comment]
> Deleting is not how you deprecate - instead you need to set the deprecated flag

Done, please review my PR again

**Comment by Jeonkook97** [comment]
What is this app for what is this message for

**Comment by mnedelchev-vn** [comment]
Hey @ligi , what else is missing for merging?

**Pull request merged**
