### PR TITLE
add ecrox chain mainnet on chain list

### PR DESCRIPTION
**Pull request by ecroxchain**
add ecrox chain mainnet on chain list

### CODE REVIEW

**Comment by ecroxchain** [comment]
please add ecrox chain mainnet on chain list

**Comment by ecroxchain** [comment]
@ligi please verify the our chain

**Comment by nnnnnnsssss** [comment]
Recheck!

**Comment by ecroxchain** [comment]
@nnnnnnsssss @ligi  not showing

**Comment by ecroxchain** [comment]
Screenshot 2023-10-26 at 20 44 50

**Comment by ecroxchain** [comment]
please check its not showing

**Review by ligi — CHANGES_REQUESTED** [review]
CI still failing - fix this then it can be merged

**Comment by ecroxchain** [comment]
hello @ligi what issue please let me know

**Review by ligi — COMMENTED** [review]
there is a lot wrong with your PR - the json is malformed also not pretty

Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

just click on the CI errors and you see

**Comment by ecroxchain** [comment]
hello @ligi please check it fixed

**Review by ecroxchain — COMMENTED** [review]
please add ecrox chain

**Comment by ecroxchain** [comment]
@ligi  please help me to resolve the issue

**Comment by ecroxchain** [comment]
@shu-unifra @ligi @zapnap @farcaller @nnnnnnsssss  please help me to resolve this issue and live our chain on chainlist

**Comment by ecroxchain** [comment]
@shu-unifra @ligi @zapnap @farcaller @nnnnnnsssss please help me to resolve this issue and live our chain on chainlist

**Comment by farcaller** [comment]
Ok, listen. Submitting a pull request means you will follow some guidelines. In here it means you will at least make sure that your checks pass, and they don't. It's not technically hard to write a valid JSON file, so I'd suggest you to focus on figuring the basics before you try to spam a bunch of unrelated people with mentions. It's just rude.

**Comment by ecroxchain** [comment]
sorry for it

**Comment by ecroxchain** [comment]
@ligi i have done everything but my chain not adding please tell where is the issue so we can reactify those things

**Comment by ligi** [comment]
CI is still red

**Review by ecroxchain — COMMENTED** [review]
final update done please check and update

**Comment by ecroxchain** [comment]
@ligi  everything now we have done please run cli we dont about cli

**Comment by ligi** [comment]
CI is still red
e.g. RPC chainId (988207) does not match chainId from json (81041)

seems like you should not run a chain

**Comment by ecroxchain** [comment]
CI is still red
e.g. RPC chainId (988207) does not match chainId from json (81041)

seems like you should not run a chain

but our chain id 81041 not 988207

**Comment by ecroxchain** [comment]
please update the final changes all done

**Comment by ecroxchain** [comment]
@ligi please check everything fixed

**Comment by ligi** [comment]
I do not know - I do not run that RPC ..

**Comment by ecroxchain** [comment]
but our rpc chain id is 81041

**Comment by ecroxchain** [comment]
not this id 988207

**Comment by ligi** [comment]
your RPC reports something different - and if you do not understand what the problem is then: you should not run a chain

**Comment by ecroxchain** [comment]
can you share the rpc reports

**Comment by ecroxchain** [comment]
https://docs.ecroxscan.com/general-1/network-details

here you can find our network details and verify also

**Pull request closed without merging**
