### PR TITLE
Add OHO explorer logo

### PR DESCRIPTION
**Pull request by ohonetwork**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Where did you pin QmZt75xixnEtFzqHTrJa8kJkV4cTXmUZqeMeHM8BcvomQc ? I canot resolve it

**Comment by ohonetwork** [comment]
> where did you pin QmZt75xixnEtFzqHTrJa8kJkV4cTXmUZqeMeHM8BcvomQc ? I cannot resolve it
I'm sorry for the inconvenience. Kindly check QmZt75xixnEtFzqHTrJa8kJkV4cTXmUZqeMeHM8BcvomQc again. Thank you

**Review by ligi — CHANGES_REQUESTED** [review]
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

**Review by Vitahabtc2 — APPROVED** [review]

**Review by Vitahabtc2 — APPROVED** [review]

**Comment by ohonetwork** [comment]
Thank you so much for the instruction and explanation. The binary icon QmZt75xixnEtFzqHTrJa8kJkV4cTXmUZqeMeHM8BcvomQc has been into iconDownload as suggested. Kindly let me know if I need to do anything else.

**Comment by ohonetwork** [comment]
> tl;dr: it is now required to put the binary icon into iconDownload
> 
> why: it was a PITA to always `ipfs get` in the review process - sometimes it takes _really long_ or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

Thank you so much for the instruction and explanation. The binary icon QmZt75xixnEtFzqHTrJa8kJkV4cTXmUZqeMeHM8BcvomQc has been added into the folder iconDownload as suggested. At the moment, I can't merge branch because merging is blocked. Kindly let me know if I need to do anything else.

**Pull request merged**
