### PR TITLE
add ontology chainid

### PR DESCRIPTION
**Pull request by lucas7788**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Unfortunately it seems that the explorer is not EIP3091 compatible

e.g. https://explorer.ont.io/testnet/block/16089828 does not work

it is: https://explorer.ont.io/block/16089828/testnet - but that violates the EIP

**Comment by noncash15** [comment]
#331

**Review by noncash15 — COMMENTED** [review]
_data/chains/eip155-5851.json

**Comment by lucas7788** [comment]
> https://explorer.ont.io/testnet/block/16089828

we have fix this problem, please merge the pull request as soon as possible. Thank you.

**Pull request merged**
