### PR TITLE
Add GZN mainnet

### PR DESCRIPTION
**Pull request by sinofool**
We are preparing a new chain, not sure if this PR is the only thing we need for the public.
Let me know if there are any other processes we need to follow.

### CODE REVIEW

**Comment by sinofool** [comment]
@ligi Can you please review this?

**Review by ligi — CHANGES_REQUESTED** [review]
https://token.gearzero.ca is not reachable

**Comment by sinofool** [comment]
Updated DNS pointing to our main under-construction site.
I am not sure if complete information is required before adding to the list, let me know and we can prioritize the whitepaper.

**Review by ligi — APPROVED** [review]

**Comment by sinofool** [comment]
Thank you @ligi

**Pull request merged**
