### PR TITLE
Add AlienX Mainnet

### PR DESCRIPTION
**Pull request by jerryjrxie**

### CODE REVIEW

**Comment by jerryjrxie** [comment]
@ligi can we rerun the CI, the error in CI says explorer does not return 200 but may have been a flake.

**Review by ligi — CHANGES_REQUESTED** [review]
rebase to master or let me rebase to master

**Comment by jerryjrxie** [comment]
@ligi rebased

**Comment by ligi** [comment]
your explorer returns 403 status code - this is not good

**Comment by TheAppleTucker** [comment]
> your explorer returns 403 status code - this is not good

@ligi Could you double check? When I check click this link manually, things work fine: [https://explorer.alienxchain.io/](https://explorer.alienxchain.io/)

**Pull request closed without merging**
