### PR TITLE
add DogeWow

### PR DESCRIPTION
**Pull request by FranckStone**

### CODE REVIEW

**Review by 13364174888 — APPROVED** [review]

**Comment by ligi** [comment]
is this chain active?

**Review by 13364174888 — APPROVED** [review]

**Comment by FranckStone** [comment]
This is a new, rpc in preparation

**Review by 13364174888 — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
also add "status": "incubating" when this chain is not yet active

**Review by 13364174888 — APPROVED** [review]

**Comment by Amirmortazavi61** [comment]
Tanks

**Comment by FranckStone** [comment]
I will submit it later, please close this first

**Pull request closed without merging**
