### PR TITLE
Updated PHI Network & Added PHI V2 Smart Chain

### PR DESCRIPTION
**Pull request by Phinetwork**
Updated PHI Network v1 Chain & Added PHI Network v2 Chain

### CODE REVIEW

**Comment by Phinetwork** [comment]
Can We Please Merge This Pull Request @ligi Thanks

**Comment by Phinetwork** [comment]
There are no conflicts this PR is ready to be merged @ligi 🙏

**Comment by Phinetwork** [comment]
? @ligi

**Comment by Phinetwork** [comment]
@kophyo1234 can we get this merged thanks

**Review by ligi — APPROVED** [review]

**Pull request merged**
