### PR TITLE
Add ChainID for GoodData Testnet

### PR DESCRIPTION
**Pull request by goodata-ivan**
GoodData is a machine learning based privacy protection platform.
This patch registers chainId 32 for GoodData Testnet.

### CODE REVIEW

**Comment by ligi** [comment]
Does this replace #330 ?

**Comment by goodata-ivan** [comment]
> Does this replace #330 ?

Yes, the old PR #330 will be closed after this PR is merged. Chain id 68 still keeps for SoterOne.

**Review by ligi — CHANGES_REQUESTED** [review]
The shortnames must be unique - GooD already exists

**Comment by ligi** [comment]
> > Does this replace #330 ?
> 
> Yes, the old PR #330 will be closed after this PR is merged. Chain id 68 still keeps for SoterOne.

great

**Comment by goodata-ivan** [comment]
> The shortnames must be unique - GooD already exists

I have changed shortname GooD to GooDT.

**Pull request merged**
