### PR TITLE
Add esync.network testnet

### PR DESCRIPTION
**Pull request by sieg-i**
The eCredits testnet has been replaced with and rebranded to esync.network testnet.

### CODE REVIEW

**Review by PayamShahmansour — COMMENTED** [review]
Leave a review

**Comment by Srikarrao1** [comment]
@sieg-i Please let me know if I can help you in merging this request

**Review by PayamShahmansour — COMMENTED** [review]
Leave a review

**Comment by sieg-i** [comment]
Switch temporarily to http RPC endpoint.

**Pull request closed without merging**
