### PR TITLE
PooChain

### PR DESCRIPTION
**Pull request by poochaindev**
Add eip155-20202021 (PooChain)

### CODE REVIEW

**Comment by Guarmarketing** [comment]
Can anybody help with this

**Review by Eklavya2023 — APPROVED** [review]

**Review by Eklavya2023 — APPROVED** [review]

**Review by Eklavya2023 — APPROVED** [review]

**Comment by ligi** [comment]
image format is wrong

**Comment by Guarmarketing** [comment]
> image format is wrong



> image format is wrong

[
  {
    "url": "https://n3st3d.mypinata.cloud/ipfs/QmYFKRoJhrb2CHYZ7Me3G1CV4XFWuZZMqyAjhf4kjowdza",
    "width": 500,
    "height": 500,
    "format": "png"
  }
]

Is this correct?

**Comment by ligi** [comment]
no

**Review by alokeutpal — APPROVED** [review]
Y

**Review by rorysan333 — APPROVED** [review]

**Pull request closed without merging**
