### PR TITLE
Add Bullions Smart Chain Mainnet to Chainlists

### PR DESCRIPTION
**Pull request by devspan**
This PR adds support for the Bullions Smart Chain to Chainlists. Bullions Smart Chain is designed to provide efficient and scalable blockchain solutions. Key details include the network's name, native currency (Bullions), and an explorer

### CODE REVIEW

**Comment by Dnormous** [comment]
Tx

**Comment by Dnormous** [comment]
Tx

**Review by ligi — CHANGES_REQUESTED** [review]
explorer does not seem to be EIP3091 compatible

**Comment by devspan** [comment]
@ligi, the EIP-3091 compliant explorer has been successfully deployed, and the URL has been updated accordingly.

**Review by ligi — APPROVED** [review]

**Pull request merged**
