### PR TITLE
eip155-713 correct ipfs added

### PR DESCRIPTION
**Pull request by Osman-Mahmood**

### CODE REVIEW

**Comment by Osman-Mahmood** [comment]
Hi @ligi,
I added correct size of ipfs link now please run the process again.

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by Osman-Mahmood** [comment]
Hi @ligi,
Sorry there was an issue with the explorer.
Please check it again and verify it's perfect now.
https://dxb.vrcscan.com/

**Review by ligi — APPROVED** [review]

**Comment by Osman-Mahmood** [comment]
Screenshot 2024-01-30 at 11 26 49 AM
Hi thanks for adding our chain into evm list
but our logo is not well displayed as you can see in screenshot i added ipfs correct link
[
  {
    "url": "ipfs://QmasMkZJ6m7y77fgY6SooNnrH3Y4a3vVYNDWe9T3KusxeU",
    "width": 512,
    "height": 512,
    "format": "png"
  }
]

**Pull request merged**
