### PR TITLE
support Nativ3 mainnet and testnet

### PR DESCRIPTION
**Pull request by Nativ3DAO**
NATIV3 IS A LAYER3 LEADER ON ARBITRUM.
Nativ3 Mainnet
chainId : 399
rpc: `https://rpc.nativ3.network`

Nativ3 Testnet
chainId : 333333
rpc: `https://rpctest.nativ3.network`

### CODE REVIEW

**Comment by jnut321** [comment]
Jeannette Sauve has sent you an email via Gmail confidential mode:

[image: Gmail logo]Re: [ethereum-lists/chains] support Nativ3 mainnet and testnet (PR #3758) <https://confidential-mail.google.com/msg/AJ05Yhd2SBFz_6p3pScqCHbo-yO4-m6V7aJ7OfXIFPGJpnwMuTokzhw42WxSsnKNFX5uXt48IaIBVgtVcxEOUDzAPbSs7_A5qOWTpJ3YY9tNXWleMp_K8Ie2vEJNudPSwSgh1NKjDZeqr6nuEgW1Ox6CC3ymidH6Ld_cjCAYZQF3VoZ0OAT8fSj0rI6FQVY-gS26eJgOTHs=>

This message was sent on Oct 31, 2023 at 4:58:10 PM PDT
You can open it by clicking the link below. This link will only work for ***@***.***

View the email <https://confidential-mail.google.com/msg/AJ05Yhd2SBFz_6p3pScqCHbo-yO4-m6V7aJ7OfXIFPGJpnwMuTokzhw42WxSsnKNFX5uXt48IaIBVgtVcxEOUDzAPbSs7_A5qOWTpJ3YY9tNXWleMp_K8Ie2vEJNudPSwSgh1NKjDZeqr6nuEgW1Ox6CC3ymidH6Ld_cjCAYZQF3VoZ0OAT8fSj0rI6FQVY-gS26eJgOTHs=>

Gmail confidential mode gives you more control over the messages you send. The sender may have chosen to set an expiration time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]

**Comment by jnut321** [comment]
Your Google verification code is 573737

**Comment by jnut321** [comment]
Your Google verification code is 201725

**Comment by jnut321** [comment]
Tu código de verificación de Google es 358449

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by Nativ3DAO** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

Thank you! 
Done.

**Review by ligi — APPROVED** [review]

**Comment by Goddessnunu22** [comment]
Owner

**Pull request merged**
