### PR TITLE
feat: 🎸 Berachain bArtio 80084

### PR DESCRIPTION
**Pull request by codingwithmanny**
New Berachain V2 Network Released June 9, 2024 at 4:20pm

BREAKING CHANGE: 🧨 N

### CODE REVIEW

**Comment by AZDABERA** [comment]
ooga booga

**Comment by lukecd** [comment]
ooga booga

**Comment by mirionic** [comment]
ooga booga

**Comment by johnyangk** [comment]
ooga booga

**Comment by Metebox** [comment]
Neigh

**Comment by PriestBera** [comment]
WOWOWOW

**Comment by blockhunters-dev** [comment]
ooooga boooga

**Comment by TesodeAll** [comment]
Ooga Booga

**Comment by gregnorth** [comment]
Ooga Booga, Sir.

**Comment by freeflowthought** [comment]
Ooga Booga!!!!!

**Comment by nodersteam** [comment]
OOGA BOOGAAAAA!!!

**Comment by duccas** [comment]
Ooga Booga 💯

**Comment by AlexMoskaleu** [comment]
Ooga Booga!

**Comment by choihocheol** [comment]
ooga booga

**Comment by Brian-provalidator** [comment]
Ooga Booga

**Comment by mindstyle85** [comment]
Ooga Booga

**Comment by techgigs80** [comment]
Ooga Booga

**Comment by darron1217** [comment]
Ooga Booga

**Comment by waldoisabear** [comment]
Ooga Booga

**Comment by JejomStark** [comment]
Ooga Booga

**Comment by devopsJetking** [comment]
ooge booga!

**Comment by MattKetmo** [comment]
🐻 🚀

**Comment by akinsp** [comment]
Ooga Booga! 🐻

**Comment by vaddec-everstake** [comment]
Ooga Booga

**Comment by KangarooFist** [comment]
Ooga Booga

**Comment by TaffForest** [comment]
Ooga Booga!!!

**Comment by nidhi-singh02** [comment]
Ooga boogaa 🐻

**Comment by NktSH** [comment]
Ooga-booga yall 🐻❤️

**Comment by dylanschultzie** [comment]
Ooga Booga

**Comment by dethebera** [comment]
OOOGGAAA BOOOGGGAAAA

**Comment by SynergyNodes** [comment]
Ooga Booga

**Comment by vlddlv** [comment]
go go!

**Comment by blacknodes** [comment]
ooga booga

**Comment by StakeUs** [comment]
OOOGA BoogA

**Comment by gabrielosz** [comment]
Ooga Booga

**Comment by pratiksardar** [comment]
ooga booga

**Comment by lichkingvamvoo** [comment]
Ooga Booga

**Comment by mrspir** [comment]
Ooga Booga

**Comment by dev-minsu** [comment]
ooga booga 🐻

**Comment by ocnc** [comment]
gud chain ooga booga

**Comment by Brendan-Whispernode** [comment]
OOGA BOOGA!

**Comment by adam-infstones** [comment]
hahaha, OOFA BOOGA. Let's go!!!

**Comment by dimiandre** [comment]
Ooga Booga 🤓

**Comment by stakecito** [comment]
ooga boogaaa!!

**Comment by mechul-eth** [comment]
Very excited for this project, Berachain is looking so promising and we are very happy to be part of it 🔥🔥

Ooga Booga 🐻🐻‍❄️🐼🧸

**Comment by YakupAltay** [comment]
ooga booga rum

**Comment by xsubject** [comment]
Ooga booga

**Comment by Brightlystake** [comment]
Ooogaaaa boooga 🐻🐻🐻🐻

**Comment by DAICers** [comment]
ooga booga

**Comment by nullmames** [comment]
Ooga booga!!

**Comment by chuck-bear** [comment]
ooga booga 🐻 ⛓️

**Comment by imperator-co** [comment]
OOGA BOOGA Let's GOOOO !

**Comment by crypto-services** [comment]
Ooga Booga

**Comment by 0xad1onchain** [comment]
ooga booga 🐻 seńor

**Comment by liray-unendlich** [comment]
ooge booga!

**Comment by codingwithmanny** [comment]
Thanks @ligi for your help on this.

**Review by ligi — APPROVED** [review]

**Pull request merged**
