### PR TITLE
Create eip155-75000.json

### PR DESCRIPTION
**Pull request by SsNiPeR1**
add my chain please

### CODE REVIEW

**Comment by SsNiPeR1** [comment]
> the explorer must have a standard field - can be `none`

so, i cannot use my own explorer?

**Comment by SsNiPeR1** [comment]
@ligi done

**Comment by SsNiPeR1** [comment]
@ligi hey??

**Comment by ligi** [comment]
I cannot verify the explorer:

image

**Comment by SsNiPeR1** [comment]
> I cannot verify the explorer:
> 
> image

fixed it, try again please

**Comment by SsNiPeR1** [comment]
@ligi

**Comment by SsNiPeR1** [comment]
@ligi I am really sorry for being annoying, but I need to make ResinCoin appear here faster. Also I have found that my explorer does not have ERC-20 support, there is no /token path.

**Review by ligi — APPROVED** [review]

**Comment by SsNiPeR1** [comment]
i have a problem: i have a redundant / in rpc url and this breaks the whole thing

**Pull request merged**
