### PR TITLE
add# QEasyWeb3 Testnet info

### PR DESCRIPTION
**Pull request by DarkSpaceLaw**
RT

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by DarkSpaceLaw** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

Just updated, please check again

**Comment by ligi** [comment]
please rebase or allow me to push to the branch

**Comment by DarkSpaceLaw** [comment]
> Just updated, please check again

Just updated, please check again, Thanks again

**Comment by DarkSpaceLaw** [comment]
> please rebase or allow me to push to the branch

Just updated, please check again, Thanks again

**Review by ligi — APPROVED** [review]

**Pull request merged**
