### PR TITLE
Treasurenet/1.0

### PR DESCRIPTION
**Pull request by chriszhao1988**
fixed icon

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Comment by tinhbao789** [comment]
Good project

**Comment by tinhbao789** [comment]
Good project

**Comment by tinhbao789** [comment]
Good project

**Comment by tinhbao789** [comment]
Good project

**Comment by tinhbao789** [comment]
Good project

**Comment by tinhbao789** [comment]
Good project

**Comment by tinhbao789** [comment]
Good project

**Comment by tinhbao789** [comment]
Good project

**Pull request merged**
