### PR TITLE
Updated: Coinsec data to fix icon issue and run prettier

### PR DESCRIPTION
**Pull request by sarwar616816**

### CODE REVIEW

**Comment by sarwar616816** [comment]
please merge

**Review by ligi — CHANGES_REQUESTED** [review]
What is the issue with the icon? SVG is better

**Comment by sarwar616816** [comment]
https://chainlist.org/ doesn't show the icon. that's the only reason for the update

**Comment by sarwar616816** [comment]
but other sites like https://chainlist.wtf/ show the icon

**Pull request closed without merging**
