### PR TITLE
Updated PHI & Added Logo json Add Dehvo CHAIN ID 13

### PR DESCRIPTION
**Pull request by Phinetwork**
Updated PHI Smart Chain & Added Logo Json

### CODE REVIEW

**Review by Phinetwork — COMMENTED** [review]
updated ipfs & added " "

**Comment by Phinetwork** [comment]
The Icon Is In this request This is the icon for the chain

**Comment by Phinetwork** [comment]
Can we please update this pull request thank you

**Comment by Phinetwork** [comment]
Hello Its Been over two weeks Can we update this pull request thank you.

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot `ipfs get QmV6z97Cr9t8j7pP1vWfp9ypioig5NcS9RLU5S2cwwMfDM` - did you pin it somewhere public.
Also the other icon you reference here does not exist -also do not use special chars referencing it

**Review by kophyo1234 — COMMENTED** [review]
`o`

**Pull request closed without merging**
