### PR TITLE
Add Chain ID 6565 Testnet

### PR DESCRIPTION
**Pull request by FoxChainLabs**
Validated Please

### CODE REVIEW

**Comment by FoxChainLabs** [comment]
revalidated please approval

**Comment by FoxChainLabs** [comment]
revalidated please

**Comment by Naygyi14** [comment]
Gg

**Comment by FoxChainLabs** [comment]
please validated

**Comment by FoxChainLabs** [comment]
please revvalidated

**Review by ligi — APPROVED** [review]

**Pull request merged**
