### PR TITLE
Added new chain of IOTA EVM Testnet

### PR DESCRIPTION
**Pull request by trungtt198x**
Added new chain of IOTA EVM Testnet

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by trungtt198x** [comment]
> image

@ligi 
The explorer will be up and running soon.
I'd like to register the chainID at first.
Pls accept the PR.
Thanks for your understanding

**Comment by ligi** [comment]
remove the explorer then

**Comment by trungtt198x** [comment]
> remove the explorer then

As the explorer will be available very soon, pls allow me to keep the explorer there or pls put this PR on hold for a while.
I'll inform you once the explorer is up.
Thanks

**Comment by trungtt198x** [comment]
@ligi 
Pls help merge this PR soon. 
I've removed the explorer info as you suggested.
Thanks a lot

**Review by ligi — APPROVED** [review]

**Comment by LizetteO** [comment]
Hello

**Pull request merged**
