### PR TITLE
Add Stenix chain with chain id 425

### PR DESCRIPTION
**Pull request by TetyanaZaliska**
added new chain called Stenix with chain id 425

### CODE REVIEW

**Comment by TetyanaZaliska** [comment]
Do I need make changes or just confirm the changes?

пн, 7 жовт. 2024, 18:34 користувач ligi ***@***.***> пише:

**Comment by TetyanaZaliska** [comment]
Ok, thank you , I will

вт, 8 жовт. 2024, 19:57 користувач ligi ***@***.***> пише:

**Comment by TetyanaZaliska** [comment]
I apply the changes, but don't understand what's wrong now?

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by TetyanaZaliska** [comment]
done

**Review by ligi — APPROVED** [review]

**Pull request merged**
