### PR TITLE
Updates pulsechain testnets

### PR DESCRIPTION
**Pull request by 3commascapital**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot reach https://scan.v4.testnet.pulsechain.com

**Comment by 3commascapital** [comment]
correct. it is being brought up currently. network will be private for a short while until the required modifications are complete

**Comment by 3commascapital** [comment]
in the meantime, do we need to continue providing / pinning our own ipfs link for the icon or is there a group somewhere that is doing this already

**Review by ligi — CHANGES_REQUESTED** [review]
format in json (../_data/icons/pulsechain.json) is svg but actually is in imageDownload png

also fix formatting of json

**Comment by 3commascapital** [comment]
do you want `deprecate` or `deprecated` for the status of deprecated networks

**Comment by deep709** [comment]
Thanks all

**Comment by ligi** [comment]
deprecated - fixing the wording here: #2641

**Comment by 3commascapital** [comment]
thanks! rebased

**Review by ligi — APPROVED** [review]

**Review by jonesk7734 — COMMENTED** [review]
Working

**Pull request merged**
