### PR TITLE
Add FileFileGo Chain

### PR DESCRIPTION
**Pull request by iNDicat0r**
Hi everyone

Adding FileFileGo chain here

### CODE REVIEW

**Comment by iNDicat0r** [comment]
@ligi Could you please approve the workflows so I can verify if the json validation passes

**Review by PeakyBlinders52 — APPROVED** [review]

**Review by PeakyBlinders52 — COMMENTED** [review]
Why is 512 the height

**Review by PeakyBlinders52 — APPROVED** [review]

**Comment by iNDicat0r** [comment]
> Why is 512 the height

If you mean the image height, then the logo is just a perfect square, 512x512. Isnt this allowed?

**Comment by iNDicat0r** [comment]
I also got an example from here:

```
[
  {
    "url": "ipfs://QmQJ21NWyGGDraicVEzS1Uqq1yXahM9NCuNZgnfYvtspdt",
    "width": 512,
    "height": 512,
    "format": "png"
  }
]
```

**Comment by iNDicat0r** [comment]
@PeakyBlinders52 Finally passed CI 🥳

**Comment by PeakyBlinders52** [comment]
YAS!!!

**Review by ligi — APPROVED** [review]

**Comment by PeakyBlinders52** [comment]
I don't feel like doing this if everyone is pretending like they know me

**Pull request merged**
