### PR TITLE
support https

### PR DESCRIPTION
**Pull request by lucas7788**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
maybe we should remove them completely as they do not seem to work on both protocols.

**Comment by lucas7788** [comment]
> maybe we should remove them completely as they do not seem to work on both protocols.

We have fixed the problem that the test network cannot be used. The main network will also be available after we go online.

**Comment by ligi** [comment]
and can you provide the endpoints via https? Providing them via http outside the dappnode vpn is not really good style ..

**Review by OhArthits — APPROVED** [review]

**Comment by lucas7788** [comment]
> and can you provide the endpoints via https? Providing them via http outside the dappnode vpn is not really good style ..

thanks for your advice, wo will support https, but we need to use the new port. please take a look again.

**Comment by lucas7788** [comment]
> and can you provide the endpoints via https? Providing them via http outside the dappnode vpn is not really good style ..

we have support https link,  please have a look again. thanks

**Comment by lucas7788** [comment]
> and can you provide the endpoints via https? Providing them via http outside the dappnode vpn is not really good style ..

we have support https, could you please take a look.

**Pull request merged**
