### PR TITLE
Update BitTorrent Chain Mainnet explorer url

### PR DESCRIPTION
**Pull request by jiro-ono**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Pleas add it as alternative explorer - not replace it

**Comment by jiro-ono** [comment]
@ligi just added commit to add it alternative explorer

**Comment by ligi** [comment]
please add it after the other one - as the other one seems to live on the infoURL domain it IMHO should come first

**Comment by jiro-ono** [comment]
@ligi prob better for the bttcscan one to be the main explorer used tho, since it's the etherscan version and better/preferred explorer of the 2

**Comment by ligi** [comment]
would then be good to have someone from bittorrentchain.io chiming in

**Pull request closed without merging**
