### PR TITLE
add chain configs for pulsechain main and test net

### PR DESCRIPTION
**Pull request by 3commascapital**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
ShortNameMustBeUnique: short name must be unique - but found `pls` more than once

**Comment by 3commascapital** [comment]
ah! thanks for the comment. i'll converse w/ team and update

**Review by pulseoglank — CHANGES_REQUESTED** [review]
You have the wrong Chain ID. The official Chain ID: 940

**Comment by 3commascapital** [comment]
@pulseoglank this is for testnet which is accurate

**Pull request merged**
