### PR TITLE
Added TechPay Chain Network

### PR DESCRIPTION
**Pull request by bitkin**
Added TechPay Chain Network details

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot `ipfs get` the CID - where did you pin it?

**Comment by bitkin** [comment]
Hello @ligi I've updated the CID and verified it. Kindly check now. Thanks

**Review by ligi — CHANGES_REQUESTED** [review]
I am getting different values for the size:

```
✓ ~/tmp identify QmQyTyJUnhD1dca35Vyj96pm3v3Xyw8xbG9m8HXHw3k2zR         08:15:06
QmQyTyJUnhD1dca35Vyj96pm3v3Xyw8xbG9m8HXHw3k2zR SVG 584x707 584x707+0+0 8-bit sRGB 28137B 0.000u 0:00.000
```

**Comment by bitkin** [comment]
@ligi Oops! I've updated the correct size. Sorry for that

**Review by ligi — CHANGES_REQUESTED** [review]
https://tpcscan.com does not seem to be reachable

**Comment by bitkin** [comment]
@ligi I really apologize. May be server had some network issues. Can you check again please, I'm able to access it. Thanks 🙏

**Pull request merged**
