### PR TITLE
Introduce the devETH network to the chain list.

### PR DESCRIPTION
**Pull request by vkoskiv**

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
The filename must match the chainID
currently it is matching the networkID (are they really this way or is thee a typo?)

**Comment by vkoskiv** [comment]
Yeah, I just spotted that. Looks like there's already a 787 on the list there for Acala. Any workaround?

**Comment by vkoskiv** [comment]
No typo, the networkID is 777 and chainID is 787, indeed.

**Comment by ligi** [comment]
Nope - there is no workaround. Duplicate chainIDs are bad - not allowed.

**Comment by vkoskiv** [comment]
Fair enough. Thanks for taking a look anyway!

**Comment by ligi** [comment]
change your chainID now that you are still a fresh project. Will become harder and harder in the future!

**Pull request closed without merging**
