### PR TITLE
Add SIX Network Chain

### PR DESCRIPTION
**Pull request by dDee-D-six**
Add SIX Network Chain (SIX Protocol) to Chainlist
ChainID : 98 (mainnet), 150 (testnet)
Info: https://six.network/

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also: RPC chainId (6665) does not match chainId from json (150)

**Comment by dDee-D-six** [comment]
Yes, 6665 is for testing purpose. And it will update to 150 in this week.

**Comment by ligi** [comment]
I will not merge as long as chainIDs fail

**Comment by dDee-D-six** [comment]
I will close this pull request and re-submit a pull request for our testnet seperately.

**Pull request closed without merging**
