### PR TITLE
add rikeza logo

### PR DESCRIPTION
**Pull request by iamakshaykumar**

### CODE REVIEW

**Review by Peerawat1981 — APPROVED** [review]
```
> 
```

**Comment by iamakshaykumar** [comment]
https://cloudflare-ipfs.com/ipfs/QmfJ1Qxpzi6CSLeFeWY1Bwe435CpT5za5WfrLUE7vNzZfy

it's showing

**Review by iamakshaykumar — COMMENTED** [review]
add rikeza chain logo

**Review by ligi — CHANGES_REQUESTED** [review]
width in json (../_data/icons/rikeza.json) is 382 but actually is in imageDownload 512

**Comment by Peerawat1981** [comment]
Thank

**Pull request merged**
