### PR TITLE
Removed `network` from _data

### PR DESCRIPTION
**Pull request by ashutoshpw**
Following up with [this commit](https://github.com/ethereum-lists/chains/commit/62ad98d60e7fba1ce66514bbb52c430b032eaf33), I have removed `network` key from JSON files located in _data/chains

### CODE REVIEW

**Comment by manny363** [comment]
Whats this mean?

**Comment by ligi** [comment]
nice approach - id you finish it and make it out of draft I will merge

**Comment by ashutoshpw** [comment]
It's ready now.

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
thanks! 
Did you do it by hand or did you use a tool?
There seem to be still some left - seeing in #1506

**Comment by manny363** [comment]
So again what is this

**Comment by ashutoshpw** [comment]
> thanks! Did you do it by hand or did you use a tool? There seem to be still some left - seeing in #1506

There were only few left, so I did this manually this time. 
Although, I could write a script for this if required.

**Comment by ligi** [comment]
can you remove the remaining - so I can merge #1506 ?

**Comment by ashutoshpw** [comment]
Sure, sending PR in few minutes.

**Comment by ligi** [comment]
> Sure, sending PR in few minutes.

:pray:

**Comment by ashutoshpw** [comment]
Here it is with the JS script that I created for removing the "network" param 
#1508

**Comment by manny363** [comment]
And that means what.  ??

**Pull request merged**
