### PR TITLE
Add zkfair mainnet

### PR DESCRIPTION
**Pull request by MortyYi**
Add zkfair mainnet

### CODE REVIEW

**Comment by MortyYi** [comment]
@ligi Hello, Could you help to review this pr. It is quite urgent for us to have our chain on Chainlist.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also If you are in a hurry - please send 420DAI to lists.eth

**Comment by MortyYi** [comment]
Hello, @ligi. I have run the prettier :)

**Comment by goushijie** [comment]
pls Add zkfair mainnet

**Comment by MortyYi** [comment]
> pls Add zkfair mainnet

Hi, I have followed the readme, add the _data/chains/eip155-42766.json file and the icon was added when we add the testnet, what else should I do? Thanks very much :)

**Comment by goushijie** [comment]
image
why i can't search it？

**Comment by MortyYi** [comment]
> Title

pls search zkfair, since it's upcase sensitive.

**Comment by MortyYi** [comment]
> image why i can't search it？

img_v3_026b_695f59fe-9c7b-4978-b3ab-c9608b6a89hu

**Comment by ligi** [comment]
you cannot find it because the PR is not merged - you will need to wait. People that say it is "urgent" - will need to either pay or wait.

**Comment by MortyYi** [comment]
> you cannot find it because the PR is not merged - you will need to wait. People that say it is "urgent" - will need to either pay or wait.

Hello, @ligi , how long will it take if we pay 420U.

**Comment by goushijie** [comment]
> > Title
> 
> pls search zkfair, since it's upcase sensitive.
image

not yet

**Comment by ligi** [comment]
> Hello, @ligi , how long will it take if we pay 420U.

I will directly merge then

**Comment by MortyYi** [comment]
> > Hello, @ligi , how long will it take if we pay 420U.
> 
> I will directly merge then

Hello, @ligi. We have sent the 420 DAI to lists.eth. Please merge ASAP. Thanks very much : )
transaction: https://etherscan.io/tx/0xe0e91582a7ce51d82a4faf687d15d02f38519ff26a79fbcb90cebff155744976

**Comment by MortyYi** [comment]
@ligi, thanks very much, but it seems like our zkfair mainnet still hasn't alive on the https://chainlist.org/ website. How long will it take?

**Comment by goushijie** [comment]
The zkfair mainnet still hasn't alive on the [https://chainlist.wtf/]website

**Comment by ligi** [comment]
It's on our site:

image

also on chainlist.org

image

not sure why chainlist.wtf is hanging - but it is no site I control

**Pull request merged**
