### PR TITLE
Deleting 2 discontinued Filecoin testnets and updating Calibration

### PR DESCRIPTION
**Pull request by eshon**
- The Hyperspace and Wallaby testnets for Filecoin will be discontinued.
- RPC and tooling updates were made to Calibration testnet which will become the main developer-focused testnet going forward.

See https://github.com/filecoin-project/community/discussions/631 for more info.

### CODE REVIEW

**Comment by eshon** [comment]
@ligi - Is it possible to get this Filecoin PR merged soon? We have a big hackathon currently happening ([HackFS](https://ethglobal.com/events/hackfs2023)) and would like to update all current infra and dev tooling providers of Filecoin Calibration testnet and remove the other testnets to reduce confusion.

**Comment by eshon** [comment]
Thank you!

**Review by Heheehd — COMMENTED** [review]
He

**Comment by eshon** [comment]
Note that marking networks as deprecated doesn't update them in the chainlist.org UI, filed an issue here: https://github.com/DefiLlama/chainlist/issues/551

**Comment by eshon** [comment]
@ligi - Okay, but chainid.network doesn't show the list of all current RPC providers for a network and their current latency, etc. Hopefully that'll be added soon!

**Comment by ligi** [comment]
AFAIK @FrederikBolding is working on it - I think https://github.com/FrederikBolding/chainlist/pull/46 is paving the way

**Pull request merged**
