### PR TITLE
Add Social Network

### PR DESCRIPTION
**Pull request by everhusk**
Add Social Network Mainnet & Testnet.

### CODE REVIEW

**Review by Missjones2829 — COMMENTED** [review]
Merge

**Comment by everhusk** [comment]
Hi, please let me know if this is missing anything to be merged in. It's blocking a few infrastructure deployments for us, so would be great to get it approved sooner rather than later. Thank you.

**Comment by ligi** [comment]
CI must not fail to merge

**Comment by Srikarrao1** [comment]
@everhusk Please let me know if I can help you in merging this request

**Comment by everhusk** [comment]
Yeah what seems to be the blocker here? I believe the tests were passing, but let me know what i'm missing @Srikarrao1 .

**Comment by Srikarrao1** [comment]
@everhusk I cannot actually say what is the blocker here other than your commit hash, I can help you merge this PR seperately from my side for small charge after successful commit, please let me know if we can proceed ahead

**Comment by Srikarrao1** [comment]
@everhusk The exception CantReachExplorerException with the message indicating that the explorer at https://testnet.social.network does not return a 2XX status code but 200 suggests a misunderstanding or misconfiguration in your code or environment. 

The formatting is not configured properly with the json files

**Pull request closed without merging**
