### PR TITLE
Create eip155-27082022.json and eip155-27082017.json

### PR DESCRIPTION
**Pull request by excoincial**
create new excoincial chain

### CODE REVIEW

**Review by kophyo1234 — APPROVED** [review]

**Comment by ligi** [comment]
closed/reopened as somehow the CI did not pick this one up - doing it now

**Review by ligi — CHANGES_REQUESTED** [review]
The Icon exl does not exist - was used in eip155-27082022.json

**Comment by PapevisO** [comment]
> The Icon exl does not exist - was used in eip155-27082022.json

@ligi thank you for your review note. We added an icon.
Also we amended 27082022 to specify it as a mainnet
and listed 27082017 our testnet too.

**Comment by excoincial** [comment]
> > The Icon exl does not exist - was used in eip155-27082022.json
> 
> @ligi thank you for your review note. We added an icon. Also we amended 27082022 to specify it as a mainnet and listed 27082017 our testnet too.

changes confirmed

**Comment by excoincial** [comment]
> The Icon exl does not exist - was used in eip155-27082022.json

@ligi please let us know if you consider your remarks resolved

**Comment by zaksta11** [comment]
I dontno why I created
.been doing for 3weeks

**Comment by excoincial** [comment]
@ligi rebased as you instructed

**Comment by PapevisO** [comment]
Thank you so much

вт, 6 сент. 2022 г., 11:21 ligi ***@***.***>:

**Pull request merged**
