### PR TITLE
Revert "Add Japan Open Chain Testnet"

### PR DESCRIPTION
**Pull request by dicv2**
Reverts ethereum-lists/chains#3310

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
why? won't merge without a ood reason

**Review by gsmanwar — APPROVED** [review]

**Comment by jnut321** [comment]
“Yes”-_admin.91.04
Rubiks Ratchette

**Review by dicv2 — COMMENTED** [review]
Good

**Comment by nnnnnnsssss** [comment]
Ree Check_ larning

**Pull request closed without merging**
