### PR TITLE
add Genesis L1 mainnet

### PR DESCRIPTION
**Pull request by alpha-omega-labs**
Genesis L1 mainnet launch Nov 19, 2021

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
name must be unique - but found `GenesisL1` more than once

**Comment by alpha-omega-labs** [comment]
> name must be unique - but found `GenesisL1` more than once

Done!

**Comment by alpha-omega-labs** [comment]
testname changed, please review, thank you

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `L1` more than once

**Comment by alpha-omega-labs** [comment]
Updated: L1 changed to L1test

**Pull request merged**
