### PR TITLE
Add RPC for chain 100010

### PR DESCRIPTION
**Pull request by ifavo**
This PR adds a RPC endpoint for chainid 100010

### CODE REVIEW

**Comment by Srikarrao1** [comment]
@ifavo Please let me know if I can help you in merging this request

**Comment by ifavo** [comment]
> @ifavo Please let me know if I can help you in merging this request

Happy to receive any suggestions, because there is no obvious feedback on whats missing.

**Comment by ifavo** [comment]
> The issue's with the formatting of your json file and remaining three checks are fine, if you check the details beside each check, you would figure it out.

I did and adjusted https://github.com/ethereum-lists/chains/pull/5286 because of it and wanted to see the result first, before doing the same for this PR.

Did the same now here.

It basically requests to put the links into a single line instead of multiple ones.

**Comment by ifavo** [comment]
@Srikarrao1 What now? Was the change as you expect it?

**Comment by ifavo** [comment]
@ligi seen you approve the PR for https://github.com/ethereum-lists/chains/pull/5286 – can you do the same for this one?

thank you 🙏

**Review by ligi — APPROVED** [review]

**Pull request merged**
