### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by konstantinrm**
1. Changed Infura's example link to a working public link with load-balanced endpoints from different providers - Reverted
2. Added Blockscout to Explorers section - Reverted
3. Deleted mirrors of Chainlist.org, where domains were expired
4. Added a new list with load-balanced public endpoints
5. Sorted list alphabetically

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
please remove (1) - I think it is important to have an infura example in the readme
how is blockscout using this repo?

**Comment by konstantinrm** [comment]
> please remove (1) - I think it is important to have an infura example in the readme how is blockscout using this repo?

I can delete #1, but I can't understand why it's Infura, not anyone else like Alchemy, QuickNode, whatever. dRPC aggregates public endpoints links from Chainlist and route to the best possible endpoint for a particular case, it's not "in-house nodes.
But if you insist, I can delete #1, no problem.

**Comment by ligi** [comment]
it's an example for something that needs API keys - so it should stay

**Comment by konstantinrm** [comment]
> it's an example for something that needs API keys - so it should stay

Returned Infura's example

**Comment by ligi** [comment]
thanks! Looks mergeable now - still need to know how blockscout uses this repo.

**Comment by konstantinrm** [comment]
> thanks! Looks mergeable now - still need to know how blockscout uses this repo.

I was not aware that Explorer section was only related to Explorer who use this library.
Added them as wide range Explorer for many EVM chains.
If you think I need to delete it - no problem

**Comment by ligi** [comment]
yea - it's under "usages" - so if it is listed there it should use this repo

**Comment by konstantinrm** [comment]
> yea - it's under "usages" - so if it is listed there it should use this repo

Done

**Pull request merged**
