### PR TITLE
add Globelchain 

### PR DESCRIPTION
**Pull request by ankyjais**

### CODE REVIEW

**Review by nnnnnnsssss — COMMENTED** [review]
Not okay Recheck MR

**Review by nnnnnnsssss — COMMENTED** [review]
Recheck

**Comment by ankyjais** [comment]
Kindly merge the Globel Chain in chainlist

**Comment by ankyjais** [comment]
Kindly merge the chain in your chainlist

**Review by ligi — APPROVED** [review]

**Pull request merged**
