### PR TITLE
Add Loop Mainnet - Updated 19.10.22

### PR DESCRIPTION
**Pull request by kevin070982**
Add Loop Mainnet

### CODE REVIEW

**Review by ponury1990 — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]

**Comment by bossmade806** [comment]
View it on github

**Review by kevin070982 — COMMENTED** [review]
Thanks I didn't see that.

**Comment by kevin070982** [comment]
Do I have to resubmit it or will the prettier repeat automatically?

**Comment by kevin070982** [comment]
@ligi Do I have to do anything else after the change?

**Review by kevin070982 — COMMENTED** [review]
Good Thanks

**Review by kevin070982 — COMMENTED** [review]
Thanks

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Pull request closed without merging**
