### PR TITLE
Add Onchain Points Mainnet

### PR DESCRIPTION
**Pull request by SwaroopH**
🙏

### CODE REVIEW

**Comment by Azizcorolla1z** [comment]
Hi

**Comment by SwaroopH** [comment]
@ligi could you approve the workflows and merge the PR whenever you can please?

Build was successful with `./gradlew run`

**Comment by Azizcorolla1z** [comment]
Pls how does this work?

**Review by Azizcorolla1z — COMMENTED** [review]
Am a builder on metaverse can you please help am new to this

**Comment by SwaroopH** [comment]
@ligi add a png with fixed dimensions and merged changes from master.

**Comment by SwaroopH** [comment]
@ligi fixed prettier - not sure how I missed it! I blame ETHCC 😅

**Review by ligi — APPROVED** [review]

**Comment by SwaroopH** [comment]
Thanks @ligi 🙏

https://etherscan.io/tx/0x8377871e6accae067573ab0e2e92c6e57f714865942f31ad813155d89e9d12ae

**Pull request merged**
