### PR TITLE
Update ShimmerEVM testnet chainId

### PR DESCRIPTION
**Pull request by trungtt198x**
Recently due to certain conditions, the ShimmerEVM testnet chain was reset and resulted in a change in Chain ID.
Chain ID was changed from `1072` to `1073`.

### CODE REVIEW

**Comment by ligi** [comment]
CI status red -> no merge

**Comment by ligi** [comment]
name must be unique - but found `SHIMMEREVMTESTNETDEPRECATED` more than once

**Comment by ligi** [comment]
you cannot delete files!

**Comment by trungtt198x** [comment]
@ligi 
Should be all good this time!

**Review by ligi — APPROVED** [review]

**Pull request merged**
