### PR TITLE
Add BlockExplorer information for kortho

### PR DESCRIPTION
**Pull request by Eric0718**
{
  "name": "Kortho",
  "logo": "",
  "homepage": "https://www.kortho.io/",
  "address": "https://www.kortho.io/Ts?searchVal=${address}",
  "tx": "https://www.kortho.io/Td?searchVal=${txHash}",
  "block": "https://www.kortho.io/Bd?searchVal=${blockNumber}"
}

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Comment by Eric0718** [comment]
Hi @ligi ,I want to know if my chianID is working, because I got an error "Could not get the chain IC, is your RPC URL correct"  when I added the metamask custom RPC with{"RPCURL":"https://www.krotho-test.net","chainID":"8285"} . Could you help me with that? Thanks.

**Comment by ligi** [comment]
sorry no - please consult MetaMask for MetaMask questions

**Comment by Eric0718** [comment]
Ok,thanks.

**Comment by Eric0718** [comment]
Hi @ligi ,I found that my chainId"8285" is not in this configuration file “https://chainid.network/chains.json”. When will you update this configuration file?

**Comment by Eric0718** [comment]
I alread did one,please check "https://github.com/ethereum-lists/chains/pull/213".

**Comment by ligi** [comment]
This PR did not add that chain: https://github.com/ethereum-lists/chains/pull/213/files

**Pull request merged**
