### PR TITLE
Add OpenEX LONG Testnet

### PR DESCRIPTION
**Pull request by agiex**

### CODE REVIEW

**Review by kolin7105 — APPROVED** [review]

**Comment by uleglypiesek** [comment]
0x06aE6e647e79bBc8845019B47cE708a0B193df6F

**Comment by uleglypiesek** [comment]
gh pr checkout 4574
gh pr checkout 4574

**Comment by uleglypiesek** [comment]
gh pr checkout 4574

**Comment by uleglypiesek** [comment]
0xd4Afe9246A16D08aEe0Ba0EBc1c178F12BC500e5

**Comment by uleglypiesek** [comment]
[0x06aE6e647e79bBc8845019B47cE708a0B193df6F0x06aE6e647e79bBc8845019B47cE708a0B193df6F](url)

**Comment by uleglypiesek** [comment]
https://github.com/ethereum-lists/chains/actions/workflows/prettier_write.yml/badge.svg

**Review by agiex — COMMENTED** [review]
reviewed

**Review by agiex — COMMENTED** [review]
reviewed

**Comment by lantanayahaya788** [comment]
I can't add openex to my Metamask wallet

**Comment by OTC15203** [comment]
Approved

**Review by ligi — APPROVED** [review]

**Pull request merged**
