### PR TITLE
Add Alphabet Network EVM

### PR DESCRIPTION
**Pull request by AlphabetNetwork**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `ALT` more than once

**Comment by AlphabetNetwork** [comment]
> short name must be unique - but found `ALT` more than once

I have changed it 👍

**Review by TDG510 — APPROVED** [review]

**Comment by AlphabetNetwork** [comment]
hi @ligi, may i know what's the code issued on validate_formatting, point 4?

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by AlphabetNetwork** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

Sure, let me try

**Comment by AlphabetNetwork** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

its updated, followed the instruction 👍

**Comment by AlphabetNetwork** [comment]
i forgot update prettier on icon file. but its updated now

**Review by ligi — APPROVED** [review]

**Pull request merged**
