### PR TITLE
Added Hazlor 

### PR DESCRIPTION
**Pull request by blockchainreg**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
This diff does not look clean - please clean it before I can review

**Comment by blockchainreg** [comment]
My apologies this my first time. Can you clarify what you mean by clean?

Thank you

**Comment by ligi** [comment]
just look at the diff - there are 55 changed files - pretty sure this is not what you want

**Comment by blockchainreg** [comment]
Thank you for the response.  I need notice that as well.  All I did was create the “eip155-7878.json” file and submitted a pull request.  What I will do is delete this repo and fork ethereum-list/chains and submit directly.

**Comment by ligi** [comment]
replaced by #550

**Pull request closed without merging**
