### PR TITLE
Add chain frenchain

### PR DESCRIPTION
**Pull request by shopglobal**
_Testnet_:
**chainID**: 69420
**networkID**: 69420

_Mainnet_: 
**chainID**: 420
**networkID**: 69420

Mainnet is offline, but launching in some days. Thanks,M

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
the filenames are wrong

**Comment by shopglobal** [comment]
@ligi the filenames have been corrected. Our intention was to avoid collision with other (seemingly defunct) chains containing similar filenames.

**Comment by ligi** [comment]
This is not possible - you have a collision here - and the other chain on 420 is older  - so yours will not be listed

**Comment by shopglobal** [comment]
> This is not possible - you have a collision here - and the other chain on 420 is older - so yours will not be listed

Well I hear you and I see you but my request is that we consider merge anyway since the network ID of this chain is not the same to the other chain ID 420.

**Comment by ligi** [comment]
no chance - having the chainID being the same allows replay attacks - will not merge

**Comment by shopglobal** [comment]
Ok will get them changed. Thanks,M

**Pull request closed without merging**
