### PR TITLE
add manta pacific testnet info

### PR DESCRIPTION
**Pull request by samzkback**

### CODE REVIEW

**Comment by samzkback** [comment]
Hi @ligi and team, we have just launch manta pacific testnet
- https://twitter.com/MantaNetwork/status/1681650870570881025
- https://pacific.manta.network/

Could you please help review this PR for adding the new network to chainlist?
Thanks a lot!

**Review by ligi — CHANGES_REQUESTED** [review]
The Icon manta does not exist - was used in eip155-3441005.json

**Comment by samzkback** [comment]
> The Icon manta does not exist - was used in eip155-3441005.json

Thanks for your review, add the icon file.

**Comment by Ayid7676** [comment]
https://twitter.com/mantanetwork/status/1681650870570881025?s=46&t=k_adti-2ybDQROTb2G7L2g

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by samzkback** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

**Comment by samzkback** [comment]
> > Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

Thanks,  updated.

**Comment by ligi** [comment]
does not look that way - otherwise CI would not fail

**Comment by samzkback** [comment]
> npx prettier --write _data/*/*.json

seems already fixed by your patch
image


the current CI issue looks like caused by icon pic, double checking..

**Comment by samzkback** [comment]
CI show the icon pic is 834*834, 
image

so I correct it here,
image

but seems the fix not applied in latest CI ?

**Comment by ligi** [comment]
icon CI is passing - formatting is not

**Comment by samzkback** [comment]
> icon CI is passing - formatting is not

got it, there is an auto fix, without report error, update now.

**Review by ligi — APPROVED** [review]

**Pull request merged**
