### PR TITLE
Add myOwn Testnet

### PR DESCRIPTION
**Pull request by tonycurises**
Adding myOwn Testnet

### CODE REVIEW

**Comment by ligi** [comment]
can you give more information about this network?

**Comment by tonycurises** [comment]
> can you give more information about this network?

Please give me the needed information. So I can fill on it. Thanks.

**Comment by ligi** [comment]
what is this network used for?

**Comment by tonycurises** [comment]
> what is this network used for?

I will be using it for test, specifically in tokenbridge.

**Comment by ligi** [comment]
I think you should not block chainID 1337 for some test project - it should be a widely used chain - please change your chainID

**Comment by tonycurises** [comment]
I will be back to you once I changed it. Thanks.

**Comment by tonycurises** [comment]
Done for the update, please review.

**Comment by tonycurises** [comment]
Good day. May I request an update on my pull request.

**Pull request merged**
