### PR TITLE
Updates to Tres Leches Blockchain

### PR DESCRIPTION
**Pull request by 3LechesCake**
Update 6065 and 6066 chains, submitting from official repro as well.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Native currency symbol must have less than 7 chars

**Review by 3LechesCake — COMMENTED** [review]
Updated Native to TRESL, we will update explorer , wrapped and other information.

**Comment by 3LechesCake** [comment]
> Native currency symbol must have less than 7 chars

updated to TRESL, please review.

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `TRESLECHES` more than once

**Review by 3LechesCake — COMMENTED** [review]
Updated Shortname

**Comment by 3LechesCake** [comment]
> short name must be unique - but found `TRESLECHES` more than once

Update the short name to match the symbol for simplification, let me know.

**Comment by 3LechesCake** [comment]
> short name must be unique - but found `TRESLECHES` more than once

fixed the problem, duplicated on #1631 , closed that one in favor of this one, and updated the short name to TRESLC and Symbol to match. please review.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`


also: Native currency symbol must have less than 7 chars

**Comment by 3LechesCake** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`
> 
> also: Native currency symbol must have less than 7 chars

thanks updated and ran prettier to confirm format.

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `TRES` more than once

**Comment by 3LechesCake** [comment]
> short name must be unique - but found `TRES` more than once

made testnet and mainet shortname different to avoid conflict thanks

**Comment by 3LechesCake** [comment]
@ligi let me know if there is anything else missing, thanks again for the help.

**Review by ligi — APPROVED** [review]

**Pull request merged**
