### PR TITLE
Add Bitindi Chain Icon

### PR DESCRIPTION
**Pull request by kumarbitindi**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

Also: your json is not valid

**Comment by kumarbitindi** [comment]
sorry kindly check updated

**Comment by ligi** [comment]
there is no icon in iconDownload as requested

**Comment by kumarbitindi** [comment]
kindly check

**Comment by ligi** [comment]
why should I check if you change nothing?

**Comment by kumarbitindi** [comment]
this link open on my system

**Comment by kumarbitindi** [comment]
https://raw.githubusercontent.com/bitindi/bitindi/main/assets/images/bitindi-400.png

**Comment by ligi** [comment]
I could not resolve your CID with ipfs get in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by kumarbitindi** [comment]
bafybeifiuwlwqihihqbai5pshwygtqb2bcwnfhae6kdvinx2sbxq57jzfq

**Comment by kumarbitindi** [comment]
that's the CID i get

**Comment by kumarbitindi** [comment]
https://ipfs.io/ipfs/QmPvLNmhQJTSp6bMF1JGsUWa2ZBBgaWcQsmxziehZBBBXf?filename=bni-chain.png

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Pull request closed without merging**
