### PR TITLE
feat: add new Kakarot Sepolia

### PR DESCRIPTION
**Pull request by bajpai244**
This PR does the following:
- Adds the new Kakarot Sepolia chain
- Depreciates the old as discussed in #4432.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by bajpai244** [comment]
> image

The RPC and explorer are going live soon, we are doing internal QA before making them public.

**Comment by ligi** [comment]
mark your PR as draft then

**Comment by bajpai244** [comment]
done

**Comment by bajpai244** [comment]
closing this and opening another PR for the same.

**Pull request closed without merging**
