### PR TITLE
Add Astra Chain

### PR DESCRIPTION
**Pull request by hoanguyenkh**
Add Astra Chain

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
where did you pin `QmaBtaukPNNUNjdJSUAwuFFQMLbZX1Pc3fvXKTKQcds7Kf` I cannot resolve it anywhere

**Comment by hoanguyenkh** [comment]
> where did you pin `QmaBtaukPNNUNjdJSUAwuFFQMLbZX1Pc3fvXKTKQcds7Kf` I cannot resolve it anywhere

thanks @ligi now it ok

**Comment by hoanguyenkh** [comment]
@ligi please add it

**Comment by ligi** [comment]
image

link is not loading for me

**Comment by hoanguyenkh** [comment]
link load ok, please check again @ligi, sorry for this inconvenience

**Comment by hoanguyenkh** [comment]
it ok @ligi

**Comment by hoanguyenkh** [comment]
it done @ligi

**Review by ligi — APPROVED** [review]

**Pull request merged**
