### PR TITLE
Create eip155-6678.json + Add Babacoin

### PR DESCRIPTION
**Pull request by babacoinbbc**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The Icon bbc does not exist - was used in eip155-6678.json

**Review by ligi — CHANGES_REQUESTED** [review]
the content hash must be an image - not a folder

**Comment by babacoinbbc** [comment]
Hello Ligi, I have checked other icons request, was the same.
Where am i doing wrong?

**Comment by ligi** [comment]
I told you whats wrong - I can fix it for you for 100DAI

**Comment by babacoinbbc** [comment]
Fixed the issue, but https://nft.storage/files/ will be avaible after 48 Hours.
Waiting for the Queuing.
ICON -> https://bafybeidpndmrn4vbtmpl7wjsvyiuwop64r4yjpfcgbwfwjt4ploprspqs4.ipfs.nftstorage.link/BBC-235x235.png
IPFS -> ipfs://bafybeidpndmrn4vbtmpl7wjsvyiuwop64r4yjpfcgbwfwjt4ploprspqs4

**Comment by ligi** [comment]
you did not fix the issue and just costing me time

**Comment by babacoinbbc** [comment]
I have sent you mail, two times.
But can't contact you.

**Pull request closed without merging**
