### PR TITLE
Add superchain testnet and mainnet

### PR DESCRIPTION
**Pull request by superexspace**
Add superchain testnet and mainnet

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
RPC chainId (1969) does not match chainId from json (1970)

**Comment by superexspace** [comment]
> RPC chainId (1969) does not match chainId from json (1970)

Fixed.

**Review by ligi — CHANGES_REQUESTED** [review]
the Icon Super does not exist - was used in eip155-1969.json

**Comment by superexspace** [comment]
> the Icon Super does not exist - was used in eip155-1969.json

Fixed

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also the explorers do not seem to be explorers - at least not  seem to be EIP3091 compliant

**Pull request closed without merging**
