### PR TITLE
Add eip155-21004 (c4ei)

### PR DESCRIPTION
**Pull request by c4ei**
Add eip155-21004 (c4ei)

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
please do not check in the .gradle files

**Comment by ligi** [comment]
where did you pin QmaFnRkMAQKTA9sJmC4pwg91nDBechjY1G34WvcVz9heLM? I cannot resolve it

**Review by c4ei — COMMENTED** [review]
add  21004

**Review by c4ei — COMMENTED** [review]
pinata

**Review by c4ei — COMMENTED** [review]
ipfs change

**Comment by c4ei** [comment]
ipfs change

**Comment by c4ei** [comment]
Change ipfs

2022년 7월 22일 (금) 오후 8:18, ligi ***@***.***>님이 작성:

**Comment by c4ei** [comment]
https://bafybeia6mbmibthxote6kvkkynms4ho3gktmn66lzjyu4h6wkxj3c35jwm.ipfs.infura-ipfs.io/

**Comment by c4ei** [comment]
> QmaFnRkMAQKTA9sJmC4pwg91nDBechjY1G34WvcVz9heLM을 어디에 고정했습니까? 나는 그것을 해결할 수 없다

https://bafybeia6mbmibthxote6kvkkynms4ho3gktmn66lzjyu4h6wkxj3c35jwm.ipfs.infura-ipfs.io/

[
{
"경로": "c4ei_1200t.png",
"해시": "QmQPE9brk9eZRTFYyjRZbtd2wM6jpkZiG5DNrMhDjt4JLS",
"크기": 102040
}
]


i change QmQPE9brk9eZRTFYyjRZbtd2wM6jpkZiG5DNrMhDjt4JLS

**Review by ggbbest — APPROVED** [review]

**Review by Adriana1960 — APPROVED** [review]

**Review by c4ei — COMMENTED** [review]
delete gradle . file

**Review by c4ei — COMMENTED** [review]
. file delete

**Pull request closed without merging**
