### PR TITLE
Add Sorian Chain to Chainlist

### PR DESCRIPTION
**Pull request by sorian-coin**
This pull request adds the Sorian blockchain to Chainlist, making it easier for users to connect to the network. Key details include:

Chain Name: Sorian
Chain ID: [210209
RPC URL(s): https://rpc.sorian.io
Currency Symbol: SOR
Explorer URL: https://scan.sorian.io
Please review the provided information for accuracy before merging.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
resolve conflicts and do not touch kotlin/gradle files

**Comment by ligi** [comment]
do not touch gradle or kotlin files

**Comment by sorian-coin** [comment]
I have solved the conflicts. Please check now. Thank you.

**Review by ligi — CHANGES_REQUESTED** [review]
you are still touching files you should not touch

**Pull request closed without merging**
