### PR TITLE
Create eip155-24.json

### PR DESCRIPTION
**Pull request by solidityx**
Please add Dithereum Mainnet for chain ID 24.

Thank you.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
the explorers section needs a standards field

**Review by ligi — COMMENTED** [review]
So the network is not yet up? How can I verify your explorer does EIP3091?

**Comment by solidityx** [comment]
> So the network is not yet up? How can I verify your explorer does EIP3091?

Yah.. It's not up yet. We are getting Etherscan like explorer, which is certainly EIP3091 compliant. If your requirement is to have fully working explorer, then we can proceed once it will be up :)

**Comment by solidityx** [comment]
I removed explorer details for now. will request addition once it will be up.  Hope to get added now :D

**Review by ligi — CHANGES_REQUESTED** [review]
The Icon dithereum does not exist

**Comment by solidityx** [comment]
Thanks for your response.  And Merry Christmas.

I have put icon for Dithereum testnet. It will be the same for mainnet: 
https://github.com/ethereum-lists/chains/blob/master/_data/icons/dithereum.json

If you need separate icon files for both chains, then I will make another file and update. Please advise. Thank you.

**Comment by ligi** [comment]
Maybe you need to rebase your PR to master then - your Icon is not found by the CI

**Comment by solidityx** [comment]
Anyway.. I added new icon file.. Hope its ok now :)

**Comment by solidityx** [comment]
> Maybe you need to rebase your PR to master then - your Icon is not found by the CI

ok let me try with master.

**Comment by solidityx** [comment]
Closing this and opened  a fresh PR with master rebase. THanks

**Pull request closed without merging**
