### PR TITLE
eip155-4181.json

### PR DESCRIPTION
**Pull request by Phinetwork**
Add PHI Smart Chain

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The Icon Φ does not exist - was used in eip155-4181.json

**Review by kkhuaa — APPROVED** [review]

**Review by Phinetwork — COMMENTED** [review]
updated symbol

**Review by kkhuaa — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
You reference an icon that does not exist

**Comment by Phinetwork** [comment]
its added here https://github.com/ethereum-lists/chains/pull/1165 you can see waiting for logo to be added here

**Comment by Phinetwork** [comment]
add logo phi.json

**Comment by Phinetwork** [comment]
closed already added in other pull request

**Pull request closed without merging**
