### PR TITLE
adding gaura chain mainnet

### PR DESCRIPTION
**Pull request by GauraWebTech**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Fix CI errors

**Comment by GauraWebTech** [comment]
Hey @ligi Can you help us with what exactly has to be fixed ?
We are unable to trace it.

It fails at "Verify The Changed Icons".
Thanks in advance.

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by ligi** [comment]
this is not a valid image you uploaded

**Comment by GauraWebTech** [comment]
Can you please tell what is the issue with the image?

**Review by ligi — CHANGES_REQUESTED** [review]
QmWtKsr5YgrWg2NjdyJWWV2yeqeDfejjcgjXwsrqx1G9MA is not a PNG image

**Comment by GauraWebTech** [comment]
i just verified it is a png image only
GAURA

**Comment by ligi** [comment]
this image has a different content hash

**Pull request closed without merging**
