### PR TITLE
add icplaza chainnet

### PR DESCRIPTION
**Pull request by David0817**
add icplaza chainnet to chainslist

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by ligi** [comment]
also do not check in the kt file

**Comment by David0817** [comment]
Sorry to take too much your time, I downloaded the Icon file

**Comment by ligi** [comment]
your explorer does not seem to be `EIP3091` compatible - change to `none` or make it compatible

**Comment by David0817** [comment]
please let me know, there is anything else that needs to be modified, thanks!

**Pull request merged**
