### PR TITLE
Add my chain

### PR DESCRIPTION
**Pull request by ClearBlocker**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
https://clearblocker.com does not look like a explorer to me

**Comment by ClearBlocker** [comment]
There is an explorer you just need to be signed in to view it, I’ll setup a blockscout explorer though to satisfy the requirements here and then resubmit the request.

**Review by ligi — CHANGES_REQUESTED** [review]
If you need to login it is clearly not EIP3091 compatible

**Comment by ClearBlocker** [comment]
you no longer have to login to view the explorer it is live at https://explorer.clearblocker.com

**Pull request closed without merging**
