### PR TITLE
Update eip155-3666.json

### PR DESCRIPTION
**Pull request by hmisty**
update the chain info

### CODE REVIEW

**Review by ligi — COMMENTED** [review]
is this a new chain?

**Comment by hmisty** [comment]
> is this a new chain?

Nop. Just updated the information. Thanks.

**Comment by hmisty** [comment]
Pinging j.blockcoach.com and rpc.jnsdao.com will resolve to the same IP 81.68.203.120 so the RPCs are pointing to the same chain.

**Comment by cnukaus** [comment]
Hi, will you please approve the workflow so this update can be merge/PR closed? Thanks.

(I previously created the chainid https://github.com/ethereum-lists/chains/pull/1852, all good)

**Comment by hmisty** [comment]
> Hi, will you please approve the workflow so this update can be merge/PR closed? Thanks.
> 
> (I previously created the chainid #1852, all good)

dear @ligi , the original committer @cnukaus has also confirmed the update. could you kindly help to proceed? thanks a lot!

**Review by ligi — APPROVED** [review]

**Pull request merged**
