### PR TITLE
Add eip-8387: Dracones mainnet

### PR DESCRIPTION
**Pull request by farcaller**
(Sorry for a dup, #2432 was closed).

I've removed all the joke mentions and any (potential?) service advertisements. Given this repo is the authoritative network source I'd love to get this merged in.

If this PR is deemed incorrect, I'd also appreciate the concrete reason as to what is deemed unfit. I followed the guidelines to the best of my knowledge: ran the gradle tests and followed the [maintainer checklist](https://github.com/ethereum-lists/chains/blob/master/maintainer_checklist.md).

### CODE REVIEW

**Comment by ligi** [comment]
what is this chain used for? Who else other than you will be using it?

**Comment by farcaller** [comment]
This chain is primarily used for an in-game currency token (and otherwise – only for the related MUCK activities). We promote the participants to perform any transactions they want outside of the controlled flow (by using metamask directly) to simulate the real finances flow in a miniature, promoting a better education about cryptocurrencies operation.

The game has about a hundred daily active users that will be using it. While the chain is functionally public, we don't plan on distributing the primary token outside of the game so as not to promote any real money trading.

**Comment by farcaller** [comment]
Verified the icon is properly pullable via the cloudflare proxy: https://cloudflare-ipfs.com/ipfs/bafybeif3scsh5w5iniecyjvsbkvje5zrfbp3l6yuz7wcf4jqzydbm2riee

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by farcaller** [comment]
> Please run the prettier to format your json according to the style [defined here](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)

Done. I'll go and add a PR check on that, too.

**Review by ligi — APPROVED** [review]

**Pull request merged**
