### PR TITLE
Chains Merge

### PR DESCRIPTION
**Pull request by navdeepgarg1**

### CODE REVIEW

**Comment by navdeepgarg1** [comment]
Hi @ligi can you please check this MR.

**Comment by navdeepgarg1** [comment]
can you please explain - RPC chainId (719) does not match chainId from json (109)

**Comment by navdeepgarg1** [comment]
Hi @ligi can you please check this MR

**Comment by navdeepgarg1** [comment]
Hi @ligi can you please check this MR

**Review by gabygroove11 — APPROVED** [review]

**Pull request closed without merging**
