### PR TITLE
add Gamverse Mainnet

### PR DESCRIPTION
**Pull request by ario-eth**
Adding a new VerseLayer network under the Oasys L1 chain.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
the explorers are not reachable

**Comment by sangmin-kim** [comment]
After launching the explorers, we will update here again.

**Review by atlslscsrv-app — APPROVED** [review]

**Comment by D-nice92** [comment]
ario-eth:master

**Review by D-nice92 — APPROVED** [review]
0x6076fF041b090F78a7411C9fb3A1afBd3FFdE541

**Pull request closed without merging**
