### PR TITLE
Add lambda mainnet info

### PR DESCRIPTION
**Pull request by steveliupai**
- Add lambda mainnet info
- format with prettier

pls merge @ligi

### CODE REVIEW

**Comment by steveliupai** [comment]
Hi @ligi I have run prettier locally and it was fine. I dont know why i cant past auto check by prettier. I found other PR are failed with the same reason. Could u please tell me how to fix this. Thank you very much!

**Comment by steveliupai** [comment]
Seems like nobody can merge after prettier updated @ligi

**Comment by amory1997** [comment]
We share the same problem, so did someone else ,need @ligi to merge

**Comment by steveliupai** [comment]
> We share the same [problem](https://github.com/ethereum-lists/chains/issues/1609), so did someone else ,need @ligi to merge

**Comment by steveliupai** [comment]
> > We share the same [problem](https://github.com/ethereum-lists/chains/issues/1609), so did someone else ,need @ligi to merge

Yes, I noticed lots of people encounter the same issue. I guess its need to get merged manually

**Comment by FrederikBolding** [comment]
Rebasing your PR should fix the Prettier issue now! 😄

**Pull request closed without merging**
