### PR TITLE
Create eip155-48795.json

### PR DESCRIPTION
**Pull request by nstamm10**

### CODE REVIEW

**Comment by nstamm10** [comment]
@ligi Could you please review and merge?

**Comment by nstamm10** [comment]
Hi @ligi Could you please merge?

**Review by ligi — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `SPACE` more than once

**Comment by nstamm10** [comment]
@ligi Thanks for the review! Just updated with a new short name.

**Review by ligi — APPROVED** [review]

**Pull request merged**
