### PR TITLE
Add iChain Mainnet

### PR DESCRIPTION
**Pull request by iChainBlock**

### CODE REVIEW

**Comment by iChainBlock** [comment]
@ligi Trust you are having a good day. Please let us know what is wrong with our logo json file ichain.json, we are following all the rules, and we checked successful merged requests to make sure we are following all the checks right. The check is always refusing our logo even we tried different formats and we are exporting these formats from our Canva account, please advise.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by iChainBlock** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

Thank you,  I did that now.

**Comment by iChainBlock** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

@ligi Please let me know what is the issue now, we still have one check failing.

Thank you

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by iChainBlock** [comment]
> I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

@ligi We value your time and appreciate your support, we are sorry to cost you that much time, now we added the file to iconsDownload, hope this works, we changed the file extension to binary as the other files in that directory.

Thank you so much for your continues follow up and support.

Regards

**Comment by iChainBlock** [comment]
@ligi  Hope you are doing well, I removed the icon for now, I will add it later when I get the correct icon from our designer. Thank you so much for you cooperation and support.

**Comment by iChainBlock** [comment]
@ligi Hope you are doing well, Please note that we removed the logo for now in order to bypass the issue, we need your action please. Thank you so much

**Comment by jnut321** [comment]
***@***.***
?relay-protocol=irn&symKey=45b8087743beec438aba9568e503db2543de49fbb79300286e73316aed1c11cb

Rubiks Ratchette

**Comment by iChainBlock** [comment]
@ligi Hope you are doing well, I saw that all workflows passed, but when I updated the branch it required approval again, thank you so much. Best Regards

**Review by ligi — APPROVED** [review]

**Pull request merged**
