### PR TITLE
Add nal testnet

### PR DESCRIPTION
**Pull request by luleigreat**

### CODE REVIEW

**Comment by luleigreat** [comment]
Hi, chain list team, can you speed up the merge, please

**Comment by luleigreat** [comment]
@ligi Please help to review it, we urgently need promotion

**Comment by ligi** [comment]
why?

**Comment by luleigreat** [comment]
> why?

Our project will be open to the public soon，thanks for review, I will fix the errors and submit again.

**Comment by luleigreat** [comment]
Fixed validate errors ,please check again,thanks very much.

**Comment by luleigreat** [comment]
Fixed some format errors, I think no problem this time, thanks.

**Comment by luleigreat** [comment]
We have fixed the certification problem ,please check again,thanks.

**Review by ligi — APPROVED** [review]

**Pull request merged**
