### PR TITLE
add a new chain

### PR DESCRIPTION
**Pull request by huosanghuakai**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The chainIDs in the json does not match the filename

**Review by ligi — CHANGES_REQUESTED** [review]
the RPC does not seem to work - when I try:
`✓ ~ curl -X POST -H  "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' http://avastar.cc/ext/bc/C/rpc`
it gives no output

**Comment by huosanghuakai** [comment]
> the RPC does not seem to work - when I try:
> `✓ ~ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' http://avastar.cc/ext/bc/C/rpc`
> it gives no output

Truly sorry, I made a mistake to give a wrong rpc url, and I have changed 'http' to 'https'.

**Comment by huosanghuakai** [comment]
add a chain

**Comment by huosanghuakai** [comment]
Dear developers, can you please help merge this pull requests.

**Pull request merged**
