### PR TITLE
Add Bitharvest info

### PR DESCRIPTION
**Pull request by toppsl**
Adds chain info for Bitharvest TestNet

### CODE REVIEW

**Comment by toppsl** [comment]
add the TestNet info.  but still awaiting. it make me confuse

**Comment by toppsl** [comment]
@ligi

**Comment by toppsl** [comment]
@ligi  hi. there, I wonder how long will be approval this PR? or maybe somethings what I need fix it?

**Comment by toppsl** [comment]
@ligi  All checks have passed, but still awaiting. sir. plz.

**Review by ligi — APPROVED** [review]

**Pull request merged**
