### PR TITLE
add DTBC to the master

### PR DESCRIPTION
**Pull request by deviantmyk**
please add DTBC to the master

### CODE REVIEW

**Comment by deviantmyk** [comment]
changed files from Windows to Linux (so no carraige return errors)

**Comment by deviantmyk** [comment]
Just used notepad++ to change the EOL to Unix (LF). Hopefully that's it now!

**Review by ligi — CHANGES_REQUESTED** [review]
explorer does not work:

Screenshot from 2024-10-09 23-10-31

**Comment by deviantmyk** [comment]
Explorer is offline at this point. It will be working in about a week. We are just trying to secure the chain details on the list at this point.

**Review by ligi — CHANGES_REQUESTED** [review]
you need to remove the explorer then in order to merge - I cannot verify the explorer adheres to EIP3091
Also if the chain is not yet active add status incubating

**Comment by deviantmyk** [comment]
I will get both live by the end of tomorrow.

Thanks

**Comment by deviantmyk** [comment]
I've removed the explorer reference, and added incubating to the topic line. The rpc and explorer will be done in a couple of days, but this would be great to get merged. Thanks

**Review by ligi — CHANGES_REQUESTED** [review]
this file is in the wrong folder with the wrong filename

**Comment by deviantmyk** [comment]
Hopefully this is all correct now. I renamed and moved the file. It is now in _data/chains. It is called eip155-52027071.
Thanks

**Review by ligi — APPROVED** [review]

**Pull request merged**
