### PR TITLE
Adding Xterio Chain

### PR DESCRIPTION
**Pull request by XterioTech**
Adding Xterio Chain.

Note that due to the chain ID collision, we are replacing the chain Metachain One, which is with the same chain ID.

Metachain One has stopped producing new blocks, and the explorer cannot be visited anymore:
https://explorer.metachain.one/

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
How did you determine the chain produces no blocks anymore? I see it producing blocks ..

**Comment by ligi** [comment]
but yeah - the explorer is not working anymore - cc @miguerom

**Comment by ligi** [comment]
I can - so I will not merge this
```
curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' https://rpc.metachain.one
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : {
    "number" : "0x7e1a68",
    "hash" : "0x5acc102947e0bbd957e2006ae774d69d72c21614c8d80ba654bda4abaa2cd0a0",
    "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "parentHash" : "0x42e18e3fdc8d3427f0a5385c8a284dcdc1c57198b7a3e31a5af38a236ef7306a",
    "nonce" : "0x0000000000000000",
    "sha3Uncles" : "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "logsBloom" : "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "transactionsRoot" : "0xa7afea6f60e8fd54c4c2b7df995bab22f737b76bafd483bfff62d9cefcb49065",
    "stateRoot" : "0xde544e1e0d6a68a1207e05eeaf88faa4e5f59c7c7ff75b77ca011ff520e5c424",
    "receiptsRoot" : "0xea704513821165c98185f89b6778c6e98ebdeb14b84e0b71507ba9309a05f305",
    "miner" : "0xa776bf2e3e966395c702ec445ec3e0373b8739e2",
    "difficulty" : "0x1",
    "totalDifficulty" : "0x7e1a69",
    "extraData" : "0xf9023fa00000000000000000000000000000000000000000000000000000000000000000c0c080f90218b841383a4e4c688a687beaf56e86a5d209d69a0df92af71b7d7c5f8d5d254fcaab565485845d55477725bf38cbfab5862926ca0a962e660876e2be4d68e559be718301b84176c4457d25d9b99ad52bf29a0e8e315a50f913bb25951f5fc8fa340d64b0f8681d764b474d5e823b7093ec6cb7fd03945a0a92956da9a7aba2652c47c333474e01b841bf7441c4c974ae8b3327a63b10e5c6f734251ff6ccd20ea6cd92d587097c788c565b5701d20fce1f3be66af39665b8ed91d0f1d4c6a06f80d96ba532f84d28dc00b841a4dab8ba7bacb1266ddadcac3e412cd06b5f8f4043fb18b3be799370fbba2e5a49f0dc2fa74e9055ed1e759d20d9060b919f303716c89ca794d56c6c8081046401b841cffc9bd356882327747d8d1f99d620e20696cb61d24417d45da21c4891c0adaf0494247416f1fc55952523df03195d734f3ad466fd6dd667fb621aa3cfb675a100b841cd6f84dfdb2e71b8afc639aa491eb427d17086b0d7422f09ed44969f27f573266b8f65c8d742bf1b4f155b3ea0dc2c6fa6165e27998b1d83634db6081d20866901b841e1364754ce2d8882bf208270f97f6083b5dd017e4b129ad74f4d069c160a449225918b6f1288a2c4f8e6d99c6175c9c9a777190fbdd874c608aee1dbeb5dd8c801b841c64dee687a33d4ee4f763d177fa4b227bdba1e065ca8c8761c18229650f1df90014c2e9c1271aaa25c858d41016c3c6b4490422f51cd7d8ccd30ea41a142b2ec01",
    "size" : "0x4f4",
    "gasLimit" : "0x1c9c380",
    "gasUsed" : "0x799f",
    "timestamp" : "0x66263fea",
    "uncles" : [ ],
    "transactions" : [ "0x6641bb740216b2b43451d8f175df2e2ccf2d76d40a1d7c0f19a6f8c5f934dcad" ]
  }
}
```

**Comment by XterioTech** [comment]
> I can - so I will not merge this
> 
> ```
> curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' https://rpc.metachain.one
> {
>   "jsonrpc" : "2.0",
>   "id" : 1,
>   "result" : {
>     "number" : "0x7e1a68",
>     "hash" : "0x5acc102947e0bbd957e2006ae774d69d72c21614c8d80ba654bda4abaa2cd0a0",
>     "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
>     "parentHash" : "0x42e18e3fdc8d3427f0a5385c8a284dcdc1c57198b7a3e31a5af38a236ef7306a",
>     "nonce" : "0x0000000000000000",
>     "sha3Uncles" : "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
>     "logsBloom" : "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>     "transactionsRoot" : "0xa7afea6f60e8fd54c4c2b7df995bab22f737b76bafd483bfff62d9cefcb49065",
>     "stateRoot" : "0xde544e1e0d6a68a1207e05eeaf88faa4e5f59c7c7ff75b77ca011ff520e5c424",
>     "receiptsRoot" : "0xea704513821165c98185f89b6778c6e98ebdeb14b84e0b71507ba9309a05f305",
>     "miner" : "0xa776bf2e3e966395c702ec445ec3e0373b8739e2",
>     "difficulty" : "0x1",
>     "totalDifficulty" : "0x7e1a69",
>     "extraData" : "0xf9023fa00000000000000000000000000000000000000000000000000000000000000000c0c080f90218b841383a4e4c688a687beaf56e86a5d209d69a0df92af71b7d7c5f8d5d254fcaab565485845d55477725bf38cbfab5862926ca0a962e660876e2be4d68e559be718301b84176c4457d25d9b99ad52bf29a0e8e315a50f913bb25951f5fc8fa340d64b0f8681d764b474d5e823b7093ec6cb7fd03945a0a92956da9a7aba2652c47c333474e01b841bf7441c4c974ae8b3327a63b10e5c6f734251ff6ccd20ea6cd92d587097c788c565b5701d20fce1f3be66af39665b8ed91d0f1d4c6a06f80d96ba532f84d28dc00b841a4dab8ba7bacb1266ddadcac3e412cd06b5f8f4043fb18b3be799370fbba2e5a49f0dc2fa74e9055ed1e759d20d9060b919f303716c89ca794d56c6c8081046401b841cffc9bd356882327747d8d1f99d620e20696cb61d24417d45da21c4891c0adaf0494247416f1fc55952523df03195d734f3ad466fd6dd667fb621aa3cfb675a100b841cd6f84dfdb2e71b8afc639aa491eb427d17086b0d7422f09ed44969f27f573266b8f65c8d742bf1b4f155b3ea0dc2c6fa6165e27998b1d83634db6081d20866901b841e1364754ce2d8882bf208270f97f6083b5dd017e4b129ad74f4d069c160a449225918b6f1288a2c4f8e6d99c6175c9c9a777190fbdd874c608aee1dbeb5dd8c801b841c64dee687a33d4ee4f763d177fa4b227bdba1e065ca8c8761c18229650f1df90014c2e9c1271aaa25c858d41016c3c6b4490422f51cd7d8ccd30ea41a142b2ec01",
>     "size" : "0x4f4",
>     "gasLimit" : "0x1c9c380",
>     "gasUsed" : "0x799f",
>     "timestamp" : "0x66263fea",
>     "uncles" : [ ],
>     "transactions" : [ "0x6641bb740216b2b43451d8f175df2e2ccf2d76d40a1d7c0f19a6f8c5f934dcad" ]
>   }
> }
> ```

Got ya. Maybe it's a regional issue I encountered
image

**Comment by LizetteO** [comment]
Hello

Please could i have assistance how to reply & solve the problem

Kind Regards,
Lizette
+27 61 352 3874

**Pull request closed without merging**
