### PR TITLE
Update Avalanche C Chain values

### PR DESCRIPTION
**Pull request by FrederikBolding**
Updated Avalanche values to make it clear that the chain is the Avalanche C Chain.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Thanks! But the chainID in the filename must match the field

**Comment by FrederikBolding** [comment]
@ligi Not sure if you also want `chain` to be corrected to `AVAXC` or something like that? 

There has been some confusion from our side on the paths and as such we had added the wrong `slip44` value for the C-Chain.

**Comment by FrederikBolding** [comment]
> Thanks! But the chainID in the filename must match the field

ChainID does match! The only thing changed other than the name is the `slip44` value, which is currently wrong for the C-Chain!

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
Sorry - you are right - was looking at it between 2 other things and thought the number change is the chainID

**Pull request merged**
