### PR TITLE
New Chains 78430, 78431, 78432

### PR DESCRIPTION
**Pull request by dfenstermaker**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
why do you remove the beam icon?

**Comment by dfenstermaker** [comment]
@ligi there isnt an icon there and this is the fastest way to get schema tests to pass

**Comment by ligi** [comment]
your schema tests pass.
but there was an icon and you removed it ..

**Comment by dfenstermaker** [comment]
@ligi ok can we merge it? or want me to put the icon back?

**Comment by ligi** [comment]
so far I think removing the icon is a regression - so I would not merge it

**Comment by dfenstermaker** [comment]
@ligi fixed

**Review by ligi — APPROVED** [review]

**Pull request merged**
