### PR TITLE
changes for Autonity Piccadilly testnet

### PR DESCRIPTION
**Pull request by flofrie**
Deprecates Autonity Piccadilly (Sumida) Testnet; adds entry for Autonity Piccadilly (Yamuna) Testnet.

Will be turned into actual PR after re-Genesis, to ensure RPC endpoints are reachable and report the correct ChainID.

### CODE REVIEW

**Comment by Rorrote** [comment]
#Gooddollar

**Comment by flofrie** [comment]
@ligi and team, this is ready for review.

**Comment by flofrie** [comment]
> #Gooddollar

@Rorrote , I am sorry, I don´t understand what you mean?

**Comment by Rorrote** [comment]
What has to be done for this

**Review by Rorrote — COMMENTED** [review]
Could you help me with more information?

**Comment by flofrie** [comment]
> Could you help me with more information?

@Rorrote , I am not sure I understand. This is a PR that has passed all checks, so it needs merging to `master` by someone with write access to the repo.

**Comment by Rorrote** [comment]
OK understand

**Comment by Rorrote** [comment]
Ok

**Comment by flofrie** [comment]
@ligi , is there anything we can do to help this along? It passes all checks, and @Rorrote also didn't seem to raise any objections, but it needs merging by someone with write access. Or is there something we're missing about the process?

(Same applies for our other PR, #5300 )

**Review by ligi — APPROVED** [review]

**Pull request merged**
