### PR TITLE
Realchain Details

### PR DESCRIPTION
**Pull request by RCLNetwork**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
icon seems to be a png

identify QmXLLqsG5wKyYRffxfTrV2AxY1xXRE4gVfZmg6mVKS2vUZ         14:34:48
QmXLLqsG5wKyYRffxfTrV2AxY1xXRE4gVfZmg6mVKS2vUZ PNG 200x90 200x90+0+0 8-bit sRGB 11823B 0.000u 0:00.010

**Comment by RCLNetwork** [comment]
@ligi icon file type updated

**Review by ligi — CHANGES_REQUESTED** [review]
connecting to https://dataseed1.rclscan.com/
Client:Geth/v1.1.18-cb9e50bd/linux-amd64/go1.17.13
BlockNumber:31527
Exception in thread "main" java.lang.IllegalStateException: RPC chainId (117) does not match chainId from json (118)

**Review by 13364174888 — APPROVED** [review]

**Comment by RCLNetwork** [comment]
deleted the testnet details.

**Comment by RCLNetwork** [comment]
> connecting to https://dataseed1.rclscan.com/ Client:Geth/v1.1.18-cb9e50bd/linux-amd64/go1.17.13 BlockNumber:31527 Exception in thread "main" java.lang.IllegalStateException: RPC chainId (117) does not match chainId from json (118)

Testnet json is removed

**Comment by RCLNetwork** [comment]
@ligi Updated the changes.

**Review by ligi — APPROVED** [review]

**Pull request merged**
