### PR TITLE
Added DeepL testnet and mainnet

### PR DESCRIPTION
**Pull request by billalxcode**

### CODE REVIEW

**Comment by billalxcode** [comment]
Excuse me, can you check this pull request? @ligi

**Comment by billalxcode** [comment]
Hello @ligi, can you help me to solve this problem?

**Comment by billalxcode** [comment]
Hi @ligi, can you check and fix the problem when running github action?

**Comment by billalxcode** [comment]
Whyyyyyyy???????

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by billalxcode** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

I already ran the command but I didn't find any problems.

**Pull request closed without merging**
