### PR TITLE
Update Scroll Alpha testnet

### PR DESCRIPTION
**Pull request by Thegaram**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot reach https://blockscout.scroll.io

**Comment by Thegaram** [comment]
> I cannot reach https://blockscout.scroll.io

Yes, this testnet will launch in a few weeks, but we hoped we could update the values here before that.

**Comment by ligi** [comment]
I cannot validate EIP3091 compatibility
So the chain is not yet active? Then pleas add status incubating

**Comment by Thegaram** [comment]
> I cannot validate EIP3091 compatibility So the chain is not yet active? Then pleas add status incubating

Added. Appreciate your help with this.

**Review by ligi — APPROVED** [review]

**Pull request merged**
