### PR TITLE
Create eip155-1229.json, Create exzo,json - Add support for Exzo Network Mainnet

### PR DESCRIPTION
**Pull request by Exzo-Network**
Add support for Exzo Network mainnet and add the logo for the network.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

**Comment by Exzo-Network** [comment]
Sorry about that I overlooked that and just updated it to xzo. Thank you for all of your time as well!

**Comment by ligi** [comment]
please remove the filename extension in iconDownload

**Comment by Exzo-Network** [comment]
Removed the .png extension on the iconDownload file QmeYpc2JfEsHa2Bh11SKRx3sgDtMeg6T8KpXNLepBEKnbJ. Thank you.

**Pull request merged**
