### PR TITLE
Add custom network GBGC Mainnet

### PR DESCRIPTION
**Pull request by Rafi6556**
Please Add custom network GBGC Mainnet on chainlist
Block explorer - https://www.gbgccoin.com/

Thank you

### CODE REVIEW

**Comment by Srikarrao1** [comment]
@Rafi6556 Please let me know if I can help you in adding your chain in Chainlist.

**Comment by Rafi6556** [comment]
Yes, please help me

**Comment by Rafi6556** [comment]
> @Rafi6556 Please let me know if I can help you in adding your chain in Chainlist.

Yes , Please Help me

**Comment by Srikarrao1** [comment]
@Rafi6556 You have not included the recent build according to the updated icons and format. You might have to consider following the format mentioned below. If you want me to do everything I might charge you a little for successful chain addition.

{
  "name": "GTCSCAN",
  "chain": "GTC",
  "icon": "gtc",
  "rpc": ["https://gtc-dataseed.gtcscan.io/"],
  "faucets": [],
  "nativeCurrency": {
    "name": "GTC",
    "symbol": "GTC",
    "decimals": 18
  },
  "infoURL": "https://gtcscan.io/",
  "shortName": "gtc",
  "chainId": 3490,
  "networkId": 3490,
  "slip44": 1,
  "explorers": [
    {
      "name": "GTCScan Explorer",
      "url": "https://gtcscan.io",
      "standard": "none",
      "icon": "gtc"
    }
  ]
}

**Comment by Rafi6556** [comment]
Yes, please help me to chain add ,

**Pull request closed without merging**
