### PR TITLE
Add Nollie Skatechain Testnet

### PR DESCRIPTION
**Pull request by JusSkate**
Hi there, requesting to add Nollie Testnet for Skatechain

### CODE REVIEW

**Comment by JusSkate** [comment]
Fixed `build` and `validate_json` failing build

**Comment by JusSkate** [comment]
Could I check what does the error mean? @ligi

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by JusSkate** [comment]
Thanks for pointing me in the right direction! Fixed in [1f61520](https://github.com/ethereum-lists/chains/pull/4715/commits/1f61520da54e874144696261c654d11fa4a354d3)

**Pull request merged**
