### PR TITLE
Add Echos Mainnet

### PR DESCRIPTION
**Pull request by shellvish**
Adds chain info for echos mainnet

### CODE REVIEW

**Review by immense055 — COMMENTED** [review]
f789e23f8ceb560fe5447db04bee7d9ece4e676d

**Comment by immense055** [comment]
f789e23f8ceb560fe5447db04bee7d9ece4e676d

**Comment by dbseotjd** [comment]
> Adds chain info for echos mainnet

**Comment by shellvish** [comment]
Hi folks, thanks a lot for your quick response. I believe this should now pass CI, would someone from the team be able to initiate the CI pipeline?

Thank you so much for your help!

**Review by ligi — APPROVED** [review]

**Comment by dbseotjd** [comment]
> PR merged - please consider contributing some funds to lists.eth

**Comment by dbseotjd** [comment]
> PR merged - please consider contributing some funds to lists.eth
fa8a7a3a0b9587cd39dbf125429b705e4b3c4d8d

**Comment by dbseotjd** [comment]
> > Adds chain info for echos mainnet
> 
> 

fa8a7a3a0b9587cd39dbf125429b705e4b3c4d8d

**Pull request merged**
