### PR TITLE
Fix Icon

### PR DESCRIPTION
**Pull request by TEAMDAOPSI2**
- [x] ./gradlew run
- [x] npx prettier --write _data/*/*.json

### CODE REVIEW

**Comment by TEAMDAOPSI2** [comment]
btw why icon is not visible on Production build...?

**Comment by Oluwarichee** [comment]
Let fix all

**Comment by Omermohemmed74** [comment]
I'm programs for only place

**Comment by Deptrai7777** [comment]
Have a meet ?

**Review by Hasona1991 — APPROVED** [review]

**Comment by ligi** [comment]
This makes no sense

**Review by BazyliszeK27Krk — COMMENTED** [review]
@Omermohemmed74

**Pull request closed without merging**
