### PR TITLE
add routescan explorers and fix etherscan one

### PR DESCRIPTION
**Pull request by IperGiove**
This PR is promoted by Routescan with the aim of improving the quality of the data as much as possible in an open-source manner.

The PR just adds the links to Routescan's explorer in the json chains data.

### CODE REVIEW

**Comment by IperGiove** [comment]
I received the notification just now. In the next few days I'll do a rebase and I'll update the urls

**Comment by IperGiove** [comment]
@ligi now the check should be pass

**Comment by IperGiove** [comment]
thanks

**Comment by IperGiove** [comment]
@ligi sorry, can you reopen the commit? I'll fix all conflicts in the same day

**Comment by IperGiove** [comment]
@ligi all checks passed, can you merge in master?

**Review by ligi — CHANGES_REQUESTED** [review]
Please do not put the routescan explorers before blockscout and otterscan ones - please add them behind them.

**Review by Missjones2 — COMMENTED** [review]
Merge

**Comment by Alkhatri77** [comment]
Hello

في الأحد، ٢٤ نوفمبر ٢٠٢٤, ٦:٥١ م Joyce Jones ***@***.***> كتب:

**Comment by IperGiove** [comment]
@ligi I moved Routescan to the bottom

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Review by ligi — APPROVED** [review]

**Pull request merged**
