### PR TITLE
Fixed Maxxchain format error 

### PR DESCRIPTION
**Pull request by bigchiano**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
https://explorer.maxxchain.org is not reachable

**Comment by bigchiano** [comment]
> https://explorer.maxxchain.org is not reachable

Oh yea, It is back up now. thanks for spotting that.

**Comment by ligi** [comment]
Still a 502 for me
image

**Comment by bigchiano** [comment]
Hi. So we just moved to a more robust server please confirm the links now work fine.

**Pull request closed without merging**
