### PR TITLE
dev: modifications to kakarot sepolia

### PR DESCRIPTION
**Pull request by bajpai244**
This PR does the following:
- We have decided to use another chain id, the network is yet to go live, so it is safe to change it
- This adds the RPC and Block explorer URLs that we will be using.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
No - you need to deprecate the old chain and create a new one. I need to protect users from replay attacks

**Comment by ligi** [comment]
it was not in incubating state - so I have to treat it as there could have been tx.

**Comment by bajpai244** [comment]
Okay, so I am fine making another PR and deprecating this.

Just to get this right, we can still keep the name "Kakarot Sepolia" on the new file, right?

i.e, can I
- change the name of this network in the file to "Kakarot Sepolia Deprecated"
- deprecated this
- and then create a new chain file and give it the name "Kakarot Sepolia" instead?

**Comment by ligi** [comment]
yes

**Review by Jess25051980 — APPROVED** [review]

**Comment by bajpai244** [comment]
@ligi closing this and as discussed I have created another PR #4530

**Pull request closed without merging**
