### PR TITLE
change okexchain's name

### PR DESCRIPTION
**Pull request by 0xngmi**
okexchain contacted us at defillama because they rebranded, submitting a pr on their behalf

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
do you have a  link to an announcement or such?

**Comment by 0xngmi** [comment]
i asked them for it but their main domain became https://www.okx.com/

**Comment by 0xngmi** [comment]
https://www.okx.com/academy/en/okex-rebrands-to-okx/ i found this by googling

**Comment by 0xngmi** [comment]
https://www.okx.com/academy/en/okex-ranked-worlds-largest-crypto-derivatives-exchange-according-to-coindesk-research/ too

**Review by ligi — APPROVED** [review]

**Pull request merged**
