### PR TITLE
add Thinkium Network

### PR DESCRIPTION
**Pull request by ThinkiumChain**
add Thinkium Network

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The shortNames must be unique
Also the explorers cannot fulfill EIP3091 as they are the same URLs for different networks

**Comment by ligi** [comment]
@matejcik can chains with different chainID have the same slip44?

**Comment by matejcik** [comment]
multiple chains of the same network, yes.

but this is reusing SLIP44 ID for Matic, which it should not be doing

**Comment by ilovechain** [comment]
hi, I‘v changed already according to rules. is it correct now ?

**Comment by ThinkiumChain** [comment]
hi, I‘v changed already according to the rules. is it correct now ?

**Comment by ThinkiumChain** [comment]
hi, I‘v changed already according to the rules. is it correct now ?  @matejcik @ligi

**Review by ligi — APPROVED** [review]

**Pull request merged**
