### PR TITLE
Add Blockscout links hosted by Blockscout team

### PR DESCRIPTION
**Pull request by vbaranov**
Blockscout explorer links are added for the next chains:
- ETH Mainnet/Goerli
- Optimism Mainnet/Goerli
- Gnosis Chain / Chiado Testnet
- Neon Devnet
- Astar Networks Astar/Shiden
- ZetaChain Athens 3 testnet

Blockscout explorer follows EIP3091 standard (it has been added, where standard was missing)

Logo is changed in order to follow the new one indicated in [the official media kit](https://docs.blockscout.com/resources/media-kit).

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
thanks for the PR - you need to remove bafybeifu5tpui7dk5cjoo54kde7pmuthvnl7sdykobuarsxgu7t2izurnq in ../_data/iconsDownload
as it is now not referenced anymore

**Comment by vbaranov** [comment]
Thank you @ligi for a tip. An old image removed. Should I undertake an extra step in order to fix `validate_icons` workflow?

**Comment by ligi** [comment]
seems the icons cannot be fetched - the easiest way to workaround is to put them into iconDownload so they do not need to be fetched from ipfs

**Comment by vbaranov** [comment]
Thank you, I added icon into `_data/iconsDownload` folder

**Pull request merged**
