### PR TITLE
Adding ORB3 Mainnet

### PR DESCRIPTION
**Pull request by AthDevETH**
We would like to add ORB3 Mainnet Chain Id to Chainslist.

### CODE REVIEW

**Review by sumit12108 — APPROVED** [review]

**Comment by AthDevETH** [comment]
Hello

Can we get a Update? We ar eMainnet ready.

Thank you

**Review by ligi — CHANGES_REQUESTED** [review]
red CI -> no merge

**Comment by AthDevETH** [comment]
> red CI -> no merge

Icon the Issue? If so we can remove?

**Review by sumit12108 — COMMENTED** [review]
Ok

**Pull request closed without merging**
