### PR TITLE
update 211.json

### PR DESCRIPTION
**Pull request by sambacha**
changed token symbol, updating here. thanks <3

### CODE REVIEW

**Comment by sambacha** [comment]
https://freighttrust.com/edi-token/

**Comment by ligi** [comment]
somehow in this site I see no mention of moving from ftn -> 0xf

**Comment by sambacha** [comment]
I will post an update reflecting that, apologies for delay in response

**Comment by sambacha** [comment]
https://freighttrust.com/edi-token/

**Comment by ligi** [comment]
I do not see the update - and you might also want to fix this:
 
image

**Comment by sambacha** [comment]
updated, thanks again Ligi 

and we are getting rid of Wordpress anyways, appreciate it!

**Comment by ligi** [comment]
:tada: 
thanks for the patience - I needed to make sure that this is a valid change

**Comment by sambacha** [comment]
No problem 🚀👍🔥

**Pull request merged**
