### PR TITLE
Please Approval ChainID 6565

### PR DESCRIPTION
**Pull request by FoxChainLabs**
Please Reupdate Chain ID 6565 Testnet

### CODE REVIEW

**Comment by FoxChainLabs** [comment]
please approval chainID 6565 not Merge LaChain.json my file fox.json for icon

**Comment by ligi** [comment]
> please approval chainID 6565 not Merge LaChain.json my file fox.json for icon

I cannot partially merge a PR

**Comment by FoxChainLabs** [comment]
Add RPC Please Validating

**Comment by FoxChainLabs** [comment]
update syntax

**Comment by FoxChainLabs** [comment]
reupdate syntax

**Comment by FoxChainLabs** [comment]
syntax update please revalidated

**Pull request closed without merging**
