### PR TITLE
update quarkchain eth rpc and add explorers

### PR DESCRIPTION
**Pull request by ping-ke**
add explorers

update eth rpc API

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The explorers do not load for me

**Comment by ping-ke** [comment]
the devnet explorers have updated and are ready to use, you can have a try, for the mainnet explorers will deploy later.

**Comment by ligi** [comment]
great - ping me when they load. If you want it merged before you need to split the PR

**Comment by ping-ke** [comment]
mainnet and devnent explorers have been deployed and related feature is about to release. would you help to approve it?

**Review by ligi — COMMENTED** [review]
somehow the explorers do not work as expected - e.g. https://mainnet.quarkchain.io/2/block/42 fails

**Comment by ping-ke** [comment]
Do you have a checklist for the explorers' verification? we can verify our explorers before connect to you again.

**Comment by ping-ke** [comment]
explorers have been deployed now, would you help to check? https://mainnet.quarkchain.io/2/block/42 is working.

**Pull request closed without merging**
