### PR TITLE
Remove Autobahn

### PR DESCRIPTION
**Pull request by defido**
The chain RPC URL and other factors will likely change, suggest it being added later. Have removed for now.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Please only add a deprecated field - we do not remove chains to protect against replay attacks

**Comment by defido** [comment]
Ok, people will find out sooner or later that the RPC has changed.

**Comment by ligi** [comment]
why don't just change the RPC to the new one then?

**Comment by defido** [comment]
I won't be the maintainer. Someone else will need to do that.

**Pull request closed without merging**
