### PR TITLE
Update Cronos zkEVM Testnet Chain-ID

### PR DESCRIPTION
**Pull request by aw126**
Hello @ligi, as official `chain-id` for Cronos zkEVM Testnet has changed from `282` to `240`, this PR is to make this update on Chainlist.

### CODE REVIEW

**Review by Eikyarkway — COMMENTED** [review]
Open

**Review by ligi — CHANGES_REQUESTED** [review]
you cannot remove chains - only mark them deprecated

**Comment by aw126** [comment]
> you cannot remove chains - only mark them deprecated

Thanks for the reply @ligi. `ReadMe` mentions adding a `status` field to deprecate a chain, but it’s unclear where exactly to add it. Could you clarify where exactly the `status` field should go and how to properly deprecate a chain with an outdated chain ID? After that, we will re-add the chain details with the new `chain-id`.

**Review by HandyPicklesStudioz — COMMENTED** [review]
HpKz

**Comment by ElvisKrop** [comment]
Hey @aw126 :wave: 
Here is an example of chain deprecation pr: https://github.com/ethereum-lists/chains/pull/5485

**Comment by aw126** [comment]
> Hey @aw126 👋 Here is an example of chain deprecation pr: #5485

Hey @ElvisKrop, thanks for sharing it 👍

**Pull request closed without merging**
