### PR TITLE
Update SNT Logo

### PR DESCRIPTION
**Pull request by nova-network-inc**
The logo is also not showing on https://chainlist.org/ can you please advise?

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I can't `ipfs get` both of these hashes - where are they pinned?

**Comment by nova-network-inc** [comment]
> 

I've just uploaded both to Pinata.cloud and I'm being able to retrieve both files using Cloudflare's free gateway.

https://cloudflare-ipfs.com/ipfs/QmbQ9qCsHv9dqtSxqDvnAjChzirpk8pKB3a22HPumKxk7o
https://cloudflare-ipfs.com/ipfs/QmNtr72zqg3eKGNyVVNgTNLddPm3nUCqggXYyE9vQxZDW2

I will reupload them and update it with the new hashes.

**Comment by ligi** [comment]
> https://cloudflare-ipfs.com/ipfs/QmbQ9qCsHv9dqtSxqDvnAjChzirpk8pKB3a22HPumKxk7o
https://cloudflare-ipfs.com/ipfs/QmNtr72zqg3eKGNyVVNgTNLddPm3nUCqggXYyE9vQxZDW2

I can `ipfs get` these easily - also the old one before the change - but not the one you want to change it to.

**Comment by ligi** [comment]
> https://cloudflare-ipfs.com/ipfs/QmbQ9qCsHv9dqtSxqDvnAjChzirpk8pKB3a22HPumKxk7o
https://cloudflare-ipfs.com/ipfs/QmNtr72zqg3eKGNyVVNgTNLddPm3nUCqggXYyE9vQxZDW2

I can `ipfs get` these easily - also the old one before the change - but not the one you want to change it to.

**Review by nova-network-inc — COMMENTED** [review]
Changed the IPFS address.

**Comment by nova-network-inc** [comment]
> > https://cloudflare-ipfs.com/ipfs/QmbQ9qCsHv9dqtSxqDvnAjChzirpk8pKB3a22HPumKxk7o
> > https://cloudflare-ipfs.com/ipfs/QmNtr72zqg3eKGNyVVNgTNLddPm3nUCqggXYyE9vQxZDW2
> 
> I can `ipfs get` these easily - also the old one before the change - but not the one you want to change it to.

I've changed it again. I don't really know what the problem is, but if you can fetch the ones above, so let's just use them.

**Review by nova-network-inc — COMMENTED** [review]
Can this please be merged? That's with the IPFS address you said it was working for you.

**Comment by ligi** [comment]
ah sorry it slipped - but the size is wrong:

```
✓ ~ identify QmbQ9qCsHv9dqtSxqDvnAjChzirpk8pKB3a22HPumKxk7o             13:02:05
QmbQ9qCsHv9dqtSxqDvnAjChzirpk8pKB3a22HPumKxk7o PNG 512x512 512x512+0+0 8-bit sRGB 33509B 0.000u 0:00.000

```

**Comment by nova-network-inc** [comment]
> ah sorry it slipped - but the size is wrong:
> 
> ```
> ✓ ~ identify QmbQ9qCsHv9dqtSxqDvnAjChzirpk8pKB3a22HPumKxk7o             13:02:05
> QmbQ9qCsHv9dqtSxqDvnAjChzirpk8pKB3a22HPumKxk7o PNG 512x512 512x512+0+0 8-bit sRGB 33509B 0.000u 0:00.000
> ```

Hey @ligi , could you please merge this one? Think the logo's all good and working just fine now.

**Pull request closed without merging**
