### PR TITLE
Add Info for Hela Chain

### PR DESCRIPTION
**Pull request by wdwd5wd**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Fix all CI errors like RPC chainId (818) does not match chainId from json (666888)

**Comment by surgarshorts** [comment]
Unable to merge

**Review by surgarshorts — CHANGES_REQUESTED** [review]
Unable to merge for approval

**Comment by surgarshorts** [comment]
Get changed file

**Comment by surgarshorts** [comment]
Run PR checks

**Comment by surgarshorts** [comment]
Verify code 1 according to info

**Comment by wdwd5wd** [comment]
> Fix all CI errors like RPC chainId (818) does not match chainId from json (666888)

I think already fixed now

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by wdwd5wd** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
> e.g. run `npx prettier --write _data/*/*.json`

Updated using prettier, but seems the format has no changes.

**Review by ligi — CHANGES_REQUESTED** [review]
when I run the prettier I see changes

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by wdwd5wd** [comment]
> image

Fixed

**Review by ligi — APPROVED** [review]

**Pull request merged**
