### PR TITLE
Add Cascadia Testnet

### PR DESCRIPTION
**Pull request by ryssroad**

### CODE REVIEW

**Comment by ryssroad** [comment]
god bless you )) 🙏

**Review by julioAk47 — APPROVED** [review]

**Comment by msvstj** [comment]
Hello,
The changes were approved. What additional steps should be taken to merge this Pull Request?

Thank you for your time!

**Comment by msvstj** [comment]
Hello @ligi  !
The PR for Cascadia was approved on June 17th. Is it possible to merge this branch?

Thank you for your time.

**Comment by ryssroad** [comment]
Hi, how this PR can be merged since all of the changes were approved?

**Comment by ligi** [comment]
no merge when CI is failing

**Pull request closed without merging**
