### PR TITLE
register μNode Testnet

### PR DESCRIPTION
**Pull request by yeti-detective**
Hi, I'm just wanting to register this testnet. There are not faucets at this time (though one or more will be added in the near future), and I'm not ready to expose the RPC, but I'd like to reserve the chain id because I have already put too much thought into it.
Let me know if any further work is needed on the PR

### CODE REVIEW

**Comment by samuelmonday6** [comment]
I Need it now

**Comment by yeti-detective** [comment]
> I Need it now

@samuelmonday6 was there something I can provide?

**Comment by ligi** [comment]
The problem is the name - would be the first chain using this char and this not in the regex - ideally do a rename or make a very good point to extend the charset allowance

**Comment by yeti-detective** [comment]
Ah yeah, I thought it was probably 50/50 whether that char would already be supported. No problem at all with renaming it.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also rebase to master

**Comment by yeti-detective** [comment]
@ligi rebased & prettier-ized

**Pull request merged**
