### PR TITLE
Change chain and network id for Firechain Main & Rinia Testnet

### PR DESCRIPTION
**Pull request by 7bp**
Previously, I requested this add (https://github.com/ethereum-lists/chains/pull/1844) and now I kindly ask to make this change.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
You cannot delete chains (replay attack problem) - only deprecate and add

**Comment by 7bp** [comment]
> You cannot delete chains (replay attack problem) - only deprecate and add

Thanks, I added back the old configs and added a status field.

**Comment by ligi** [comment]
names can be changed to e.g. _old - no replay attack here

**Comment by 7bp** [comment]
I updated the names and short names to reflect the deprecate status.

**Pull request merged**
