### PR TITLE
Add GRVT testnet (eip155-326) and mainnet chains (eip155-325)

### PR DESCRIPTION
**Pull request by minhbsq**
Adding GRVT Mainnet (ID:325) and GRVT Sepolia testnet (ID:326).
Bridge URL will be added after mainnet and testnet deployment

Please refers to this issue for more context https://github.com/ethereum-lists/chains/issues/5191

### CODE REVIEW

**Comment by Srikarrao1** [comment]
@minhbsq Please let me know if I can help you in adding your chain in Chainlist.

**Comment by minhbsq** [comment]
hi @Srikarrao1 thanks for the help. Can you help me to review this PR. First time registering the chain so pls bear with me

**Comment by minhbsq** [comment]
@ligi please help take a look at this PR? Appreciate your time.

**Review by ligi — APPROVED** [review]

**Review by Pandapsy — COMMENTED** [review]
Good jobs

**Comment by Romek-cloud** [comment]
Path

**Review by Romek-cloud — COMMENTED** [review]
Okprzeglad

**Comment by Romek-cloud** [comment]
Okoprzemko

**Pull request merged**
