### PR TITLE
Add Darwin devnet

### PR DESCRIPTION
**Pull request by Gavin-darwin-ai**

### CODE REVIEW

**Comment by Srikarrao1** [comment]
@Gavin-darwin-ai Please let me know if I can help you in passing these checks.

**Comment by Gavin-darwin-ai** [comment]
add icon

**Comment by Gavin-darwin-ai** [comment]
It's ready. thanks   @Srikarrao1

**Comment by Gavin-darwin-ai** [comment]
What do I need to do to get approved？

**Comment by Gavin-darwin-ai** [comment]
@ligi @Srikarrao1  Thanks for set approved

**Comment by Gavin-darwin-ai** [comment]
@ligi @Srikarrao1  what do I need to do?

**Comment by Srikarrao1** [comment]
@Gavin-darwin-ai I can help you with the validate icon formatting, let me know if I can.

**Comment by Gavin-darwin-ai** [comment]
@Srikarrao1 you can,thanks!

**Comment by Srikarrao1** [comment]
Please contact me on Discord or telegram where I will suggest you the steps in detail
Discord Id: Srikarrao1
Telegram: Srikarrao1

**Pull request closed without merging**
