### PR TITLE
updated Vanguard currency symbol

### PR DESCRIPTION
**Pull request by hussamBim**
I am updated Currency symbol for our testnet from VG to VANRY. for official change you can follow this link:
 https://faucet.vanarchain.com/

### CODE REVIEW

**Comment by Cripdalocc** [comment]
Get tf off my data

**Review by Queenkaz — APPROVED** [review]

**Comment by hussamBim** [comment]
@Queenkaz change not reflecting on chainlist, is it approved or in pending state?

**Comment by hussamBim** [comment]
@Queenkaz @Cripdalocc 
can you please tell the status for symbol change?

image

**Review by PizzaShift — APPROVED** [review]

**Comment by PizzaShift** [comment]
> @Queenkaz @Cripdalocc 
> can you please tell the status for symbol change?
> 
> image
> 

lol

**Comment by hussamBim** [comment]
@Queenkaz please have a look at this, because still not updated the currency symbol.

**Pull request closed without merging**
