### PR TITLE
Updated: Add BinaryChain fixed, build issues

### PR DESCRIPTION
**Pull request by binary-chain**

### CODE REVIEW

**Comment by binary-chain** [comment]
The rpc main net is online now. It was directed to the other at the moment, but now is directed correctly.

**Comment by binary-chain** [comment]
Do i need to make a new pull request now, or just wait for this one to be restarted?

**Comment by vladevelops** [comment]
All the necessary changes was done, in local all tests are ok. 
Screenshot from 2024-06-19 09-42-07

**Comment by binary-chain** [comment]
@ligi can you please run the ci again?

**Review by ligi — APPROVED** [review]

**Pull request merged**
