### PR TITLE
Add Eclipse Subnet (17172)

### PR DESCRIPTION
**Pull request by connorch**

### CODE REVIEW

**Comment by connorch** [comment]
@ligi When you have a sec can you please take a look at this?  It should be all set now.  Sorry about the failed tests before; the chain ID I was originally provided was apparently wrong, but it is resolved now.

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by connorch** [comment]
Ugh, sorry about that.  Not sure why but their chain was removed from the Glacier Indexer (it was working [here](https://glacier-api.avax.network/v1/chains?network=testnet)), which is resulting in that error.

I'll discuss with the team and either close this PR or let you know when I'm sure we're ready.

**Comment by connorch** [comment]
Closing this PR for now so we can hand it off to another team that is more in-the-know on the chain's status.

**Comment by connorch** [comment]
Okay @ligi, this chain is now ready to be added.  Sorry about the mixup before!

**Review by ligi — APPROVED** [review]

**Pull request merged**
