### PR TITLE
Add Zebro Smart Chain (ZSC)

### PR DESCRIPTION
**Pull request by ZebroTech**
Adding of Zebro Smart Chain (ZSC), The Ethereum fork chain.

### CODE REVIEW

**Comment by ZebroTech** [comment]
it's been at least a dozen times i tried but format validation check failes!
Even tried validate formatting online before PR but no luck
eip155-786786.json is as following.

```
{
  "name": "Zebro Smart Chain",
  "chain": "ZEBRO",
  "rpc": ["https://rpc.zebrocoin.app", "https://rpc1.zebrocoin.app"],
  "faucets": [],
  "nativeCurrency": {
    "name": "Zebrocoin",
    "symbol": "ZEBRO",
    "decimals": 18
  },
  "infoURL": "https://zebrocoin.app",
  "shortName": "zebro",
  "chainId": 786786,
  "networkId": 786786,
  "icon": "zebrocoin",
  "explorers": [
    {
      "name": "Zebrocoin Explorer",
      "url": "https://explorer.zebrocoin.app",
      "standard": "EIP3091"
    },
    {
      "name": "Zebrocoin Explorer1",
      "url": "https://explorer1.zebrocoin.app",
      "standard": "EIP3091"
    }
  ]
}

```

Any help will be appreciated.

Thanks.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by ZebroTech** [comment]
@ligi 
```
root@vmi292469:~# node -v
v8.10.0
root@vmi292469:~# npm -v
3.5.2
root@vmi292469:~# npx -v

Command 'npx' not found, did you mean:

  command 'npm' from deb npm
  command 'nex' from deb nvi
  command 'gpx' from deb gpx
  command 'nyx' from deb nyx
  command 'np' from deb mosquitto-auth-plugin

Try: apt install <deb name>
```

Isn't npx suppose to run with node?
Do I have to install npx separately?
Node v8.10.0 supports npx?

Thanks in advance.

**Comment by ZebroTech** [comment]
@ligi 
```
root@vmi292469:~# npx prettier --write eip155-786786.json
eip155-786786.json 95ms
```
hope it passes now.
Thanks

**Review by ligi — APPROVED** [review]

**Comment by ZebroTech** [comment]
address please

**Pull request merged**
