### PR TITLE
Add CMDAO BBQ Chain

### PR DESCRIPTION
**Pull request by coshi190**

### CODE REVIEW

**Comment by coshi190** [comment]
@ligi i had changed chain icon cid, please run again sir.

**Comment by coshi190** [comment]
@ligi Help me please sir, Why [](https://cloudflare-ipfs.com/ipfs/QmeRUnXcTjwPwkYMr3gfTZZYDZg8of4Ey4hkY198WL12tU ) can not download on PR check.

**Review by coshi190 — COMMENTED** [review]
removed icon that couldn't pass PR check

**Comment by coshi190** [comment]
@ligi pls run check again sir.

**Review by ligi — APPROVED** [review]

**Pull request merged**
