### PR TITLE
update default explorer for eip155-534352.json

### PR DESCRIPTION
**Pull request by HAOYUatHZ**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Can u elaborate on the change? Both explorers are up and valid - why remove 1?

**Comment by HAOYUatHZ** [comment]
> Can u elaborate on the change? Both explorers are up and valid - why remove 1?

(To clarify: I am from the scroll team, see https://github.com/scroll-tech/scroll/graphs/contributors)

we have both https://blockscout.scroll.io (using blockscout) and https://scrollscan.com/ (built by the etherscan team)
however, blockscout sometimes suffers from performance issues and consumes a lot of CPU resources.

if both https://blockscout.scroll.io and  https://scrollscan.com/ are in `_data/chains/eip155-534352.json`
and if users add scroll network via https://chainlist.org/
the default explorer will be https://blockscout.scroll.io
deleting the first entry, https://blockscout.scroll.io, can let the users use https://scrollscan.com/ by default

sorry for not clarifying it before

**Comment by ligi** [comment]
can't you just switch the explorer positions instead of deleting one?

**Comment by HAOYUatHZ** [comment]
> can't you just switch the explorer positions instead of deleting one?

that's also doable, updated, thx!

**Comment by HAOYUatHZ** [comment]
@ligi can you take a look again? thx!

**Review by ligi — APPROVED** [review]

**Review by ligi — APPROVED** [review]

**Pull request merged**
