### PR TITLE
Create eip155-15555.json

### PR DESCRIPTION
**Pull request by stebansaa**
This PR adds Trust EVM testnet. Thank you.

### CODE REVIEW

**Review by BISHOy2580 — CHANGES_REQUESTED** [review]
can you send for me in trust wallet bnb smart China  0xc805f3D4b190Ca2C6Add8cDAC3f309C142Bad622

**Comment by stebansaa** [comment]
an update would be appreciated.

**Comment by stebansaa** [comment]
still waiting for an approval

**Comment by najmahmd** [comment]
{
    "name": "Memolabs Abbas Mainnet",
    "chain": "ABBAS",
    "icon": "abbas",
    "rpc": [
      "https://chain.metamemo.one:8501"
    ],
    "faucets": [
  ],
    "nativeCurrency": {
      "name": " Abbas",
      "symbol": "ABBAS",
      "decimals": 18
    },
    "infoURL": "www.metamemo.one",
    "shortName": "abbaschain",
    "chainId": 985,
    "networkId": 985,
      "explorers": [{
      "name": "Mainnet explorer",
      "url": "https://scan.metamemo.one:8080/",
      "standard": "EIP3091"
    }]
}

**Review by ligi — APPROVED** [review]

**Pull request merged**
