### PR TITLE
add classzz network

### PR DESCRIPTION
**Pull request by FranckStone**
add classzz network

### CODE REVIEW

**Review by ligi — COMMENTED** [review]
Where did you pin the IPFS CID?

**Comment by FranckStone** [comment]
I don't quite understand your question, the picture is on ipfs, it won't change

**Comment by ligi** [comment]
yea - but it needs to be pinned somewhere so I can resolve it ..-)

**Comment by ligi** [comment]
also please undo the last commit - just pin the CID somewhere

**Comment by FranckStone** [comment]
Is that right?

**Pull request closed without merging**
