### PR TITLE
Update Tenet network icon

### PR DESCRIPTION
**Pull request by bulbazavr1024**
Update Tenet network icon

### CODE REVIEW

**Comment by bulbazavr1024** [comment]
@ligi Hey! Thanks for your work! Can you check it please ?

**Comment by ligi** [comment]
SVG is better than PNG

**Comment by bulbazavr1024** [comment]
@ligi https://chainlist.org/chain/1559 if we use svg, the logo isn't displayed

**Comment by ligi** [comment]
that should be fixed in the frontend then

**Review by alokeutpal — APPROVED** [review]

**Pull request closed without merging**
