### PR TITLE
Add Auroria Testnet

### PR DESCRIPTION
**Pull request by SergeevDmitry**

### CODE REVIEW

**Comment by SergeevDmitry** [comment]
@ligi could you approve checks again please? I've restarted my IPFS node to share the icon

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by SergeevDmitry** [comment]
It seems that the problem with my local IPFS node. I'm sorry for inconvenience. Thank you for you help

**Comment by SergeevDmitry** [comment]
@ligi I'm sorry to bother you again, but I don't understand why formatting is invalid. I've ran `tools/schemaCheck.js` script locally and it was ok

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by SergeevDmitry** [comment]
Thank you

**Pull request merged**
