### PR TITLE
Rebranding: eCredits to eSync Network

### PR DESCRIPTION
**Pull request by sieg-i**
- eCredits was rebranded to eSync Network. Previously it was only done for testnet, now also mainnet.

- added additional RPC endpoint with new esync.network domain

### CODE REVIEW

**Comment by sieg-i** [comment]
- eCredits was rebranded to eSync Network. Previously it was only done for testnet, now also mainnet.
- added additional RPC endpoint with new esync.network domain

**Review by ligi — CHANGES_REQUESTED** [review]
https://ecredits.com still exists

**Comment by sieg-i** [comment]
> https://ecredits.com still exists

Not decided yet whether to redirect to https://esync.network or site will be rebuilt.

However block explorer is already set to redirect: https://explorer.ecredits.com to esync.network domain.

**Review by ligi — CHANGES_REQUESTED** [review]
The beacon explorer is not EIP3091 compatible - don't even think it can be

**Comment by sieg-i** [comment]
> The beacon explorer is not EIP3091 compatible - don't even think it can be

Should I remove the "standard" field from json then? Or drop the entire entry from explorers collection?

**Review by ligi — APPROVED** [review]

**Pull request merged**
