### PR TITLE
Add Zora Network

### PR DESCRIPTION
**Pull request by tbtstl**
This PR adds network information for Zora's network, an optimistic rollup chain for zora.co. 

More information is available at [zora.energy](https://zora.energy).

### CODE REVIEW

**Comment by iainnash** [comment]
➕

**Review by moriowanibe — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by iainnash** [comment]
It looks like that prettier style is what is in this JSON: 
```
> npx prettier --check '_data/*/*.json'
Checking formatting...
All matched files use Prettier code style!
```

**Comment by ligi** [comment]
this is the last report I got from the action - but also somehow the workflows for your PR are not running currently - maybe because of the many force pushes 
Maybe open as another PR - nothing I can do here

**Comment by tbtstl** [comment]
> this is the last report I got from the action - but also somehow the workflows for your PR are not running currently - maybe because of the many force pushes 
> 
> Maybe open as another PR - nothing I can do here

Understood, will close this PR in favor of a new one.

**Pull request closed without merging**
