### PR TITLE
Add posichain mainnet & testnet

### PR DESCRIPTION
**Pull request by dannyposi**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
Where did you pin `QmXqprM1TPafQFLirQ7dMPMgou1hoUGuCvHYSWU9g8ocv8` I cannot resolve it

**Comment by dannyposi** [comment]
> Where did you pin `QmXqprM1TPafQFLirQ7dMPMgou1hoUGuCvHYSWU9g8ocv8` I cannot resolve it

I've pinned it on my local node, do you have any suggestion?

**Comment by dannyposi** [comment]
> Where did you pin `QmXqprM1TPafQFLirQ7dMPMgou1hoUGuCvHYSWU9g8ocv8` I cannot resolve it
@ligi I've pinned it on pinata https://gateway.pinata.cloud/ipfs/QmXqprM1TPafQFLirQ7dMPMgou1hoUGuCvHYSWU9g8ocv8

**Comment by dannyposi** [comment]
@ligi please help to review

**Comment by dannyposi** [comment]
@ligi do I have to do anything else?

**Comment by dannyposi** [comment]
@ligi could you help to review again. thanks

**Comment by dannyposi** [comment]
Close this MR, i want to add more devnet.

New MR: https://github.com/ethereum-lists/chains/pull/1451

**Pull request closed without merging**
