### PR TITLE
Add SIX protocol Explorer (eip155-98, eip155-150)

### PR DESCRIPTION
**Pull request by dDeedev**
Add SIX protocol Explorer (eip155-98, eip155-150)

### CODE REVIEW

**Comment by deep709** [comment]
Thanks

**Review by abtinking — APPROVED** [review]

**Review by alexsio27444 — APPROVED** [review]

**Comment by dDeeScrap** [comment]
Hi, is there any action that I have to done before pull request? To prevent build error

```
Exception in thread "main" org.ethereum.lists.chains.model.ExplorerCannotEndInSlash: Explorer cannot have a slash on the end

	at org.ethereum.lists.chains.MainKt.checkChain(Main.kt:338)
> Task :processor:run FAILED
checking single chain _data/chains/eip155-150.json
processing ../_data/chains/eip155-150.json
	at org.ethereum.lists.chains.MainKt.main(Main.kt:[40](https://github.com/ethereum-lists/chains/actions/runs/5064495580/jobs/9092137813?pr=2865#step:4:41))

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processor:run'.
> Process 'command '/usr/lib/jvm/temurin-11-jdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 1m 30s
9 actionable tasks: 6 executed, 3 up-to-date
```

**Comment by alokeutpal** [comment]
All are disturbence

**Review by alokeutpal — APPROVED** [review]
Lawra

**Review by alokeutpal — APPROVED** [review]
Yaa

**Pull request closed without merging**
