### PR TITLE
Update VinuChain & VinuChain Testnet

### PR DESCRIPTION
**Pull request by ElemontCapital**
Update VinuChain & VinuChain Testnet

### CODE REVIEW

**Comment by ElemontCapital** [comment]
Hi, made some changes please try again. @ligi

**Comment by ElemontCapital** [comment]
Hi, made another change, please try again. @ligi

**Review by LKS121 — COMMENTED** [review]
Correct

**Comment by ElemontCapital** [comment]
Hi, made another change for formatting, please try again. @ligi

**Comment by ElemontCapital** [comment]
Hi, made changes, please try again. @ligi

**Comment by ElemontCapital** [comment]
Hi, made changes, please try again. @ligi

**Pull request closed without merging**
