### PR TITLE
Added Unit Zero Mainnet

### PR DESCRIPTION
**Pull request by phearnot**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
explorer does not seem to work

**Comment by phearnot** [comment]
@ligi we haven't launched the mainnet yet, although we're planning to do so soon. what would be the right way to handle this: should I remove the explorer URL from the list, or should we launch an empty explorer instance for now, so that it's populated with the actual data when the network is launched?

**Review by BabarSaim — COMMENTED** [review]
@BabarSaimi

**Review by ligi — CHANGES_REQUESTED** [review]
yes - please remove the explorer then

**Review by ligi — APPROVED** [review]

**Pull request merged**
