### PR TITLE
Update chain info for Astar zkEVM mainnet and testnet

### PR DESCRIPTION
**Pull request by shaunxw**
- Updated Astar zkEVM mainnet chain id.
- Added new testnet info.

Will update when launched.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
you cannot change a chainID - you can only mark one deprecated and add a new one

**Comment by shaunxw** [comment]
@ligi please kindly have a look. Our mainnet is in `incubating` state and has never been deployed with the previous chainID. There is no tx that can be replayed. https://github.com/ethereum-lists/chains/blob/ca6b7c07040a9d8db745ebd1f73b35c91dd23965/_data/chains/eip155-12611.json#L23

**Comment by shaunxw** [comment]
Hi @ligi, could you please have a look? We're on a tight schedule to launch our zkEVM mainnet.

**Comment by fiexer** [comment]
Hi @ligi, let us know how to proceed to make this PR being merged.
I really hope this can be resolved soon 🙏

**Comment by ligi** [comment]
if you are in a hurry please pay some funds to lists.eth

**Comment by shaunxw** [comment]
Hey @ligi , just paid 0.05 ETH. Please kindly help to proceed. https://etherscan.io/tx/0x28a51e25b3493a5094f707fdae4a588567d06ff42670556056adc1b1cbe89379

**Review by ligi — APPROVED** [review]

**Pull request merged**
