### PR TITLE
Add Treasure Mainnet and Update Treasure Topaz and Ruby Testnets

### PR DESCRIPTION
**Pull request by karelvuong**
# Changelog
- Remove Treasure Ruby (no longer running/supported)
- Update Treasure Topaz details
- Add Treasure Mainnet
# Passes Checks
✅ `./gradlew run`
image

✅ `npx prettier --write _data/*/*.json`

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
you cannot delete chains - only mark them deprecated. This is important to prevent replay attacks

**Comment by karelvuong** [comment]
Thanks @ligi, re-added and marked deprecated.

**Comment by karelvuong** [comment]
Hi @ligi thanks for your help earlier. Just bumping in case you're able to take a quick look as have a few things blocked by this. 🙏

**Review by Aholaone360 — COMMENTED** [review]
Gnote

**Review by karelvuong — COMMENTED** [review]
Resolved in latest

**Review by ligi — APPROVED** [review]

**Pull request merged**
