### PR TITLE
Clarify that "Ethereum Classic Testnet" is Morden.

### PR DESCRIPTION
**Pull request by bobsummerwill**

### CODE REVIEW

**Comment by ligi** [comment]
Does ETC has 2 testnets? Otherwise I rather not merge as it might lead to confusion with the original ETH testnet Morden

**Comment by bobsummerwill** [comment]
It has multiple testnets, yes.

- Classic Morden
- Kotti (equivalent to Gorli)
- Mordor (new POW testnet, to replace Classic Morden, which has weird nonce thing only supported in Classic Geth, not Parity, not MultiGeth, not Besu)

@soc1c is the expert :-)

**Comment by bobsummerwill** [comment]
The confusion with Morden is because it *is* the same testnet, which split at the time of the DAO fork.

**Comment by bobsummerwill** [comment]
See https://ecips.ethereumclassic.org/ECIPs/ecip-1056 for the Meta ECIP for the pending Agharta HF, which includes block numbers for Morden, Mordor, Kotti and ETC mainnet.

**Comment by ligi** [comment]
OK then - if there are multiple it makes sense

**Comment by soc1c** [comment]
> Does ETC has 2 testnets? Otherwise I rather not merge as it might lead to confusion with the original ETH testnet Morden

It's the same network. ETH Morden = ETC Morden after ETH moved to Ropsten.

**Pull request merged**
