### PR TITLE
Add OHO network logo

### PR DESCRIPTION
**Pull request by ohonetwork**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
where did you pin QmZt75xixnEtFzqHTrJa8kJkV4cTXmUZqeMeHM8BcvomQc ? I cannot resolve it

**Comment by ohonetwork** [comment]
> where did you pin QmZt75xixnEtFzqHTrJa8kJkV4cTXmUZqeMeHM8BcvomQc ? I cannot resolve it
I'm sorry for the inconvenience. Kindly check QmZt75xixnEtFzqHTrJa8kJkV4cTXmUZqeMeHM8BcvomQc again. Thank you

**Review by ligi — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by ohonetwork** [comment]
Thank you so much for the style reference and sample command line for prettier. I have run prettier to format my json file and updated it.

**Review by ligi — APPROVED** [review]

**Pull request merged**
