### PR TITLE
new chain added 138 &&  2138

### PR DESCRIPTION
**Pull request by Mukulhosen**

### CODE REVIEW

**Review by defi-oracle — APPROVED** [review]

**Review by defi-oracle — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
chainId must match the filename

**Comment by defi-oracle** [comment]
> chainId must match the filename

fixed

**Review by defi-oracle — APPROVED** [review]

**Review by defi-oracle — APPROVED** [review]

**Review by defi-oracle — APPROVED** [review]

**Review by defi-oracle — COMMENTED** [review]
All addressed

**Review by defi-oracle — APPROVED** [review]

**Review by NaughtyUnicorn24 — APPROVED** [review]

**Comment by Mukulhosen** [comment]
Please merge

**Review by ligi — APPROVED** [review]

**Pull request merged**
