### PR TITLE
Create eip155-1003.json

### PR DESCRIPTION
**Pull request by Farid116**

### CODE REVIEW

**Comment by Farid116** [comment]
hello
how do I pass the check if there is no icon?
I will add an icon later.

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by Farid116** [comment]
I executed
npx prettier locally --write _data/*/*.json
and fixed the file
eip155-1003.json

please check

**Review by ligi — APPROVED** [review]

**Comment by Farid116** [comment]
Wonderful!
All checks have been passed!

How long to wait for the appearance on
https://chainlist.org ?

**Comment by Farid116** [comment]
Please tell
us what needs to be done so
that when you click on the 'ADD METAMASK' button
Metamask opened and offered to add a network .
Right now, when
you click on the 'ADD METAMASK'
button, nothing happens...

**Pull request merged**
