### PR TITLE
add plian

### PR DESCRIPTION
**Pull request by terry108**
Add Plian mainnet and testnet

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot open the explorer URLs - please remove when they are not active yet or make this PR a draft when I should wait until they are active.
Also "subchain" maybe we want to use the parent field here? Are these subchains L2's to the main-chains?

**Comment by terry108** [comment]
> I cannot open the explorer URLs - please remove when they are not active yet or make this PR a draft when I should wait until they are active.
> Also "subchain" maybe we want to use the parent field here? Are these subchains L2's to the main-chains?

The explorer URLs is working now.  Please check it again.
Yes, subchains are L2's to the main-chains.

**Comment by daishiydmaguchi** [comment]
null

**Review by ligi — CHANGES_REQUESTED** [review]
can you please add a parent field like so:
```json
 "parent": {
    "chain": "eip155-XXX",
    "type": "L2"
  }
```

where eip155-XXX is the parent chain?

**Comment by ligi** [comment]
we just need to make the CI happy to merge - and CI complains about the short name not being unique

**Comment by terry108** [comment]
> we just need to make the CI happy to merge - and CI complains about the short name not being unique

Done, please have a try again. Txs~

**Comment by ligi** [comment]
hm - I do not really understand your change - but the shortname must be unique - means each chain has a different shortName - currently they all have the same ..

**Pull request closed without merging**
