### PR TITLE
Change SoterOne Mainnet to GoodData Testnet.

### PR DESCRIPTION
**Pull request by TheStarBoys**
This patch changes SoterOne Mainnet to GoodData Testnet.

### CODE REVIEW

**Comment by ligi** [comment]
Can you provide some insight? Was there a rename?

**Comment by TheStarBoys** [comment]
> Can you provide some insight? Was there a rename?

There's not any file rename. Just change SoterOne Mainnet information to GoodData Testnet information in `_data/chains/eip155-68.json`.

git diff --stat  --name-only c8477c7 005875b0
_data/chains/eip155-68.json

**Comment by ligi** [comment]
Yea I see - but I need to know why to know this is a friendly and not a hostile takeover. Is SoterOne discontinued?

**Comment by TheStarBoys** [comment]
> Yea I see - but I need to know why to know this is a friendly and not a hostile takeover. Is SoterOne discontinued?

Could I confirm from the person who created this #154 that this PR is friendly？
The old chain ( SoterOne ) is still running, but it needs to be renamed as GoodData Testnet.

**Comment by ligi** [comment]
why does it need to be renamed?

**Comment by ligi** [comment]
replaced by #332

**Pull request closed without merging**
