### PR TITLE
add rangers protocol network

### PR DESCRIPTION
**Pull request by FlyingLittleBear**
please add rangers protocol network

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
The explorer section needs a standard field

**Comment by FlyingLittleBear** [comment]
i add the standard field in  explorer section, please approve again,thank you~

**Comment by FlyingLittleBear** [comment]
@ligi

**Comment by FlyingLittleBear** [comment]
hello~~~

**Comment by FlyingLittleBear** [comment]
@ligi  hello~~

**Pull request closed without merging**
