### PR TITLE
Add chainID to KorthoTest

### PR DESCRIPTION
**Pull request by Eric0718**
{
"name": "KorthoTest",
"chain": "Kortho",
"network": "Test",
"rpc": [
"https://www.krotho-test.net"
],
"faucets": [
],
"nativeCurrency": {
"name": "Kortho Test",
"symbol": "Kto",
"decimals": 11
},
"infoURL": "https://www.kortho.io/",
"shortName": "Kortho",
"chainId": 8285,
"networkId": 8285
}

### CODE REVIEW

**Comment by ligi** [comment]
I see these are blockexplorers in the infoURL - please consider adding them to the new explorers field as seen in #59

**Review by ha842 — COMMENTED** [review]
Nice

**Review by ha842 — APPROVED** [review]

**Comment by Eric0718** [comment]
Hi, @ligi

**Comment by Eric0718** [comment]
Hi @ligi ，I just submitted the information about BlockExplorer, please check it，thanks.

**Review by HyperDragonIm — APPROVED** [review]

**Pull request merged**
