### PR TITLE
ADD New Chain For PHI Network

### PR DESCRIPTION
**Pull request by Phinetwork**
Added New Chain ID & Explorer For PHI Network v2 Upgrade.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
short name must be unique - but found `PHI` more than once

**Comment by Phinetwork** [comment]
Thanks for information didnt realize couldnt be same short name Changes Made @ligi

**Comment by Phinetwork** [comment]
> short name must be unique - but found `PHI` more than once

Has successfully built can we go ahead and merge this PR thanks

**Comment by Phinetwork** [comment]
@ligi can we get this update merged thank you

**Pull request closed without merging**
