### PR TITLE
add mmt icon and change name from Mammoth to Mammoth Mainnet

### PR DESCRIPTION
**Pull request by mmtchain1**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I cannot `ipfs get QmaF5gi2CbDKsJ2UchNkjBqmWjv8JEDP3vePBmxeUHiaK4`

**Comment by mmtchain1** [comment]
> I cannot `ipfs get QmaF5gi2CbDKsJ2UchNkjBqmWjv8JEDP3vePBmxeUHiaK4`

Hello, I uploaded the icon file using ipfs desktop 0.20.5 macos version serval days ago. And I can get the icon file from my laptop, the details are as follows. Are there any other steps I haven't done?
pg@pgdeMacBook-Pro ~ % ipfs get QmaF5gi2CbDKsJ2UchNkjBqmWjv8JEDP3vePBmxeUHiaK4
Saving file(s) to QmaF5gi2CbDKsJ2UchNkjBqmWjv8JEDP3vePBmxeUHiaK4
 37.24 KiB / 37.24 KiB [========================================================================================================================================================================] 100.00% 0s
pg@pgdeMacBook-Pro ~ %

**Comment by ligi** [comment]
you need to pin it on a public node - alternatively you can also put the file here: https://github.com/ethereum-lists/chains/tree/master/_data/iconsDownload

**Comment by mmtchain1** [comment]
> you need to pin it on a public node - alternatively you can also put the file here: https://github.com/ethereum-lists/chains/tree/master/_data/iconsDownload

Thanks for you help, I have put the file on https://github.com/ethereum-lists/chains/tree/master/_data/iconsDownload, Please review them.

**Review by ligi — APPROVED** [review]

**Pull request merged**
