### PR TITLE
Create eip155-973.json

### PR DESCRIPTION
**Pull request by plunyach**
add new palm

### CODE REVIEW

**Review by plunyach — COMMENTED** [review]
update file name

**Review by plunyach — COMMENTED** [review]
update icon name

**Review by plunyach — COMMENTED** [review]
update file

**Review by plunyach — COMMENTED** [review]
update short name

**Review by plunyach — COMMENTED** [review]
update short name

**Review by plunyach — COMMENTED** [review]
update short name

**Comment by plunyach** [comment]
add palm

**Review by ligi — APPROVED** [review]

**Pull request merged**
