### PR TITLE
Add guru network testnet

### PR DESCRIPTION
**Pull request by shestakoven**
https://scan.gurunetwork.ai

### CODE REVIEW

**Comment by Srikarrao1** [comment]
@shestakoven Please let me know if I can help you in adding your chain in Chainlist.

**Comment by shestakoven** [comment]
@Srikarrao1 thank you! We added all the needed metadata and checks passed locally. Should we do something else from our side?

**Comment by Srikarrao1** [comment]
@shestakoven    You have not included the build by running ./gradlew run and formatting of icon and ipfs url is not set properly. All test cases are failing

Please let me know if I can help for some smaller compensation.

**Comment by shestakoven** [comment]
@Srikarrao1 

image

**Comment by Srikarrao1** [comment]
@shestakoven The formatting of these checks locally might not be same as github scripts here, let me know how to connect on any other channels as you wish.

**Comment by shestakoven** [comment]
@ligi please, re-run workflows. Thanks

**Pull request closed without merging**
