### PR TITLE
Updated Kaia changes

### PR DESCRIPTION
**Pull request by praveen-kaia**
* Updated Kaia Testnet Kairos changes for Klaytn network.
* Reference https://klaytn.foundation/kaia-testnet-kairos-launch/

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
This looks wrong to me - seems you want to replace one chain with another

**Comment by ligi** [comment]
do the chains share the same genesis?

**Comment by praveen-klaytn** [comment]
Yes @ligi . Kaia is a hardfork of Klaytn network and will continue to operate under Kaia as part of rebranding.
Here is the website https://kaia.io continue roadmap and faqs.

**Comment by praveen-kaia** [comment]
Hi @ligi , can you please let me know if you need more info about this ?

**Review by ligi — APPROVED** [review]

**Pull request merged**
