### PR TITLE
Add DeFiMetaChain Testnet ("Changi")

### PR DESCRIPTION
**Pull request by johnny-random**
Kindly add the provided chain. It is the upcoming EVM extension of [DeFiChain](https://defichain.com/).

### CODE REVIEW

**Comment by johnny-random** [comment]
Could someone kindly help me out? It looks as if the checks all pass, but still, the result is interpreted as an error... :/

Looking at the failed check, I see `BAD=0` at line 4, and `Error: Process completed with exit code 1.` at line 64. This seems contradictory to me, and indicates that the automated check for success is being wrongly executed.

@ethereum-lists

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by johnny-random** [comment]
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

Thanks a lot for replying & helping me out here, much appreciated! :)

I did as you instructed, and when uploading the prettified files over the old ones, I noticed there were no changes. I then deleted the files and re-uploaded, but the trailing newline at the end of the file still doesn't get uploaded.

I see that other projects' data is in the same format, so I hope this should be ok now.

**Review by ligi — APPROVED** [review]

**Comment by johnny-random** [comment]
Thanks again, both for the help and adding the chain to your repository so quickly!

When navigating to https://chainlist.org/chain/1133, the chain shows the default ["no icon"](https://chainlist.org/unknown-logo.png) instead of the one I am providing through ipfs. Is there something wrong with my data, or does it just take some time to update?

**Comment by jnut321** [comment]
Affiliate ID:
6495_72635_36456_4408_57_213_25-subidENTX690523|35989|51283_15232...

Rubiks Ratchette

**Pull request merged**
