### PR TITLE
Update evmos icon

### PR DESCRIPTION
**Pull request by jolube**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
the hash is a directory not a file

**Comment by jolube** [comment]
@ligi thanks for pointing that out. Made the change.

**Review by ligi — APPROVED** [review]

**Comment by jolube** [comment]
Anything additional left so we can merge?

**Comment by ligi** [comment]
needed to wait for the CI

**Comment by jolube** [comment]
@ligi would you happen to know how long these updates take before they're reflected on chain list?

**Comment by ligi** [comment]
no

**Pull request merged**
