### PR TITLE
Add XR Sepolia

### PR DESCRIPTION
**Pull request by quinnwoods-swg**
XR Sepolia is an Arbitrum Orbit L3 on Arbitrum Sepolia.

### CODE REVIEW

**Comment by quinnwoods-swg** [comment]
Re-requesting review @ligi :)

**Comment by quinnwoods-swg** [comment]
I don't understand why this is failing :(

**Comment by quinnwoods-swg** [comment]
Re-requesting review @ligi :)

I re-added icon sizing

**Comment by quinnwoods-swg** [comment]
IPFS url updated.

Re-requesting review @ligi :)

**Comment by quinnwoods-swg** [comment]
Not yet ready to re-request review

**Comment by RealWooblay** [comment]
Re-requesting review @ligi :)
Thank you

**Comment by 0x2me** [comment]
@ligi requesting review

**Review by ligi — APPROVED** [review]

**Pull request merged**
