### PR TITLE
Add GM Network Testnet

### PR DESCRIPTION
**Pull request by revotu**
Add GM Network Testnet

Website: https://gmnetwork.ai/

Docs: https://docs.gmnetwork.ai/docs/gm-networks-innovations/gm-network-introduction/gm-network/testnet

### CODE REVIEW

**Comment by revotu** [comment]
@ligi  Dear developer, please review our GM Network Testnet pull request, Thank you very very much

**Comment by revotu** [comment]
@ligi Could you please review and merge?

**Comment by revotu** [comment]
@ligi Please help to review and merge it, we urgently need promotion. Thanks very much.

**Comment by revotu** [comment]
@ligi Sorry to bother you. Could you please help merge this pull request? We're in a bit of a hurry with our promotion.

**Comment by ligi** [comment]
If you are in a hurry please send funds to lists.eth

**Review by ligi — APPROVED** [review]

**Pull request merged**
