### PR TITLE
Make sure the path is correct

### PR DESCRIPTION
**Pull request by ylmin**
Make sure the path is correct

### CODE REVIEW

**Comment by ligi** [comment]
can you elaborate on the intent of the change?

**Comment by ahmaadfawdii** [comment]
كيف أضيف عنوان البلوكشين لكل الشبكات بشكل عام والتوكينات الجديده والقديمة المدفوعه والغير مدفوعه

**Comment by ylmin** [comment]
> can you elaborate on the intent of the change?

The path is used to normalize the given path. Normalization resolves the (.) and (..) segments of the path to their correct form

**Review by ligi — APPROVED** [review]

**Comment by Festusonen1** [comment]
The path is used to normalize the given path. Normalization resolves the (.) and (..) segments of the path to their correct form

**Comment by Festusonen1** [comment]
2xy9kDLaEFdcbRkYJYbbj3LlPD1

**Pull request merged**
