### PR TITLE
Create mochain.json

### PR DESCRIPTION
**Pull request by mochainapp**
MO Chain Icon

### CODE REVIEW

**Comment by SsNiPeR1** [comment]
is this chain there?
you should add the icon name to the eip-<chainId>.json file.

**Comment by mochainapp** [comment]
already added on https://github.com/ethereum-lists/chains/pull/1669. sorry for the confusion.

**Review by ligi — CHANGES_REQUESTED** [review]
I get different sizes:

```
identify QmYLUfx1rsmzKT2YMPCNaz8B7N78JSNT3fvTQmgcVpMS4G         11:45:20
QmYLUfx1rsmzKT2YMPCNaz8B7N78JSNT3fvTQmgcVpMS4G SVG 206x162 206x162+0+0 8-bit sRGB 24135B 0.000u 0:00.000
```

**Review by tazimamatovzeka — APPROVED** [review]

**Comment by mochainapp** [comment]
> I get different sizes:
> 
> ```
> identify QmYLUfx1rsmzKT2YMPCNaz8B7N78JSNT3fvTQmgcVpMS4G         11:45:20
> QmYLUfx1rsmzKT2YMPCNaz8B7N78JSNT3fvTQmgcVpMS4G SVG 206x162 206x162+0+0 8-bit sRGB 24135B 0.000u 0:00.000
> ```

no worries, its a svg file that is flexible. depending on the size request it enlarges.

**Comment by SsNiPeR1** [comment]
@ligi please do something with #1617

**Comment by ligi** [comment]
> no worries, its a svg file that is flexible. depending on the size request it enlarges.

the size should still be correct - please change

**Pull request closed without merging**
