### PR TITLE
Add MIND smart Chain mainnet 

### PR DESCRIPTION
**Pull request by nnlgsakib**

### CODE REVIEW

**Comment by nnlgsakib** [comment]
Thanks for reviewing!

I have made the necessary changes ☺️

**Review by nnlgsakib — COMMENTED** [review]
Done 👍

**Comment by nnlgsakib** [comment]
Please chack

**Comment by nnlgsakib** [comment]
@ligi please approve the changes

**Review by ligi — APPROVED** [review]

**Pull request merged**
