### PR TITLE
Feat/connext network eip155

### PR DESCRIPTION
**Pull request by DenSmolonski**
This pull request introduces the configuration settings necessary for integrating Connext Sepolia Network into the project.

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Review by ligi — CHANGES_REQUESTED** [review]
please fix CI errors

**Comment by DenSmolonski** [comment]
@ligi Fixed, thank you!

**Comment by DenSmolonski** [comment]
@ligi Hey there! I was wondering if you had any updates? I would be really grateful for any help you could give me!

**Comment by DenSmolonski** [comment]
@ligi Hi, do you have any updates regarding the merging of this PR?

**Comment by Friedheilm** [comment]
Hi, @ligi, hope you're doing well!
Can you please review this, cause it's a true blocker for us

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
If this was a blocker for you - you should really think about contributing to the project ^^

**Pull request merged**
