### PR TITLE
added resincoin icon

### PR DESCRIPTION
**Pull request by SsNiPeR1**

### CODE REVIEW

**Comment by SsNiPeR1** [comment]
@ligi i have added an icon, may you approve?

**Comment by SsNiPeR1** [comment]
@ligi now that's a delay 😅

**Comment by MoGenius5420** [comment]
`gh pr checkout 1617`

**Review by MoGenius5420 — APPROVED** [review]

**Comment by SsNiPeR1** [comment]
ok but merge now please, or you can't?

**Comment by SsNiPeR1** [comment]
@ligi there's a scammer around here i think, also im waiting for so long 😅

**Comment by MoGenius5420** [comment]
`gh pr checkout 1617`

**Comment by SsNiPeR1** [comment]
yo @ligi why don't you do anything with these many prs

**Comment by SsNiPeR1** [comment]
@ligi approve pls

**Comment by SsNiPeR1** [comment]
@ligi pleeeease

**Review by ligi — CHANGES_REQUESTED** [review]
The size is wrong
```
identify QmTBszPzBeWPhjozf4TxpL2ws1NkG9yJvisx9h6MFii1zb   12:00:15
QmTBszPzBeWPhjozf4TxpL2ws1NkG9yJvisx9h6MFii1zb PNG 460x460 460x460+0+0 8-bit sRGB 2460B 0.000u 0:00.000

```

**Comment by SsNiPeR1** [comment]
fixed

**Review by ligi — APPROVED** [review]

**Comment by SsNiPeR1** [comment]
image
does not show up for some reason

**Comment by SsNiPeR1** [comment]
@ligi i still do not see the icon, i wonder what the problem is?

**Pull request merged**
