### PR TITLE
add fncy chain

### PR DESCRIPTION
**Pull request by MetaverseWorldInc**
FNCY Mainnet
RPC: https://fncy-seed1.fncy.world
Network ID: 62
Chain ID: 62

### CODE REVIEW

**Comment by MoGenius5420** [comment]
`gh pr checkout 1655`

**Review by ligi — CHANGES_REQUESTED** [review]
Is your chain older?

**Comment by MetaverseWorldInc** [comment]
Sorry, I thought there was no chain ID 62.

**Comment by MetaverseWorldInc** [comment]
I will delete the commit and request it again.

**Pull request closed without merging**
