### PR TITLE
change .ml TLD to .dev

### PR DESCRIPTION
**Pull request by SsNiPeR1**
the old .ml is legacy and is not working already. i need to change it to dev

### CODE REVIEW

**Comment by 5050prop** [comment]
oh yeeees

**Comment by amory1997** [comment]
I got exactly the same error when making PR in the last few days.
[](https://github.com/ethereum-lists/chains/issues/1609
)

**Comment by SsNiPeR1** [comment]
> I got exactly the same error when making PR in the last few days. And I opened a [issue](https://github.com/ethereum-lists/chains/issues/1609).

i see. the pr is still open and can be merged though.

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
Sorry for the delay - was busy with ETHBerlin and the week around it

**Comment by amory1997** [comment]
> > I got exactly the same error when making PR in the last few days. And I opened a [issue](https://github.com/ethereum-lists/chains/issues/1609).
> 
> i see. the pr is still open and can be merged though.

oh that 's a good news

**Comment by SsNiPeR1** [comment]
> Sorry for the delay - was busy with ETHBerlin and the week around it

one day is not a delay, thank you

**Comment by MoGenius5420** [comment]
Wow. You call yourself DEVs?

**Comment by SsNiPeR1edu** [comment]
> Wow. You call yourself DEVs?

what do you mean?

**Comment by MoGenius5420** [comment]
It's a joke my broda. Much love fellow DEV

**Comment by MoGenius5420** [comment]
Lol, texting totally misinterprets, but the future is lit homie WHOOOP!

**Comment by MoGenius5420** [comment]
Yo sniper. U want some tokens?

**Comment by MoGenius5420** [comment]
Platinum =5MATIC
Diamond = 4MATIC
Gold =2MATIC
Bronze ≠ 1MATIC
Copper lol =FREE If You're a REAL G! Questionnaire yo' Azs

**Comment by SsNiPeR1** [comment]
> Platinum =5MATIC Diamond = 4MATIC Gold =2MATIC Bronze ≠ 1MATIC Copper lol =FREE If You're a REAL G! Questionnaire yo' Azs

the fuck

**Comment by MoGenius5420** [comment]
YUP

**Comment by MoGenius5420** [comment]
ITS REAL OUT HERE IN AFRICA NIGGA

**Pull request merged**
