### PR TITLE
Add Avalanche Subnets

### PR DESCRIPTION
**Pull request by connorch**
Hi there 👋!  I'm a dev with the Ava Labs team.  This PR adds a few Avalanche Subnet chains, and also updates some existing ones with proper branding and explorer/rpc URLs.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
If these are subnets please consider using the parent field

**Comment by ligi** [comment]
also please resolve the conflict

**Comment by connorch** [comment]
@ligi - The merge conflicts are now resolved!

How would you recommend we use the `parent` field for subnets?  It seems that the `parent` field is used to declare a parent "chain" for L2s and shards, but this doesn't exactly align with subnet architecture since subnets don't have a parent chain.  Subnets _do_ have a parent validator network though (i.e. Blockchains on subnets are validated by a _subset_ of validators on the Avalanche Primary Network).

If we had to pick a specific blockchain to list as each subnets' parent, it would have to be the [P-Chain](https://docs.avax.network/overview/getting-started/avalanche-platform#platform-chain-p-chain), however the P-Chain isn't an EVM so adding that chain to this repo probably wouldn't make sense.

I would appreciate your guidance with this, and I'd be happy to discuss subnet architecture a bit more with you if it will help come to a resolution.  Thanks!

**Comment by connorch** [comment]
@ligi Please let me know if there's anything else I can do here.  I don't think the `parent` field will apply to subnets, as each subnet is an independent L1.

**Comment by k-822** [comment]
@ligi  We're at the AvaLabs team and trying to merge this to enable some features on our new explorer [here](https://subnets.avax.network/). Could you please review and merge. Happy to discuss if you have any questions.

**Comment by connorch** [comment]
@ligi sorry for the ping again, but as @k-822 mentioned, this PR is blocking some features from functioning in our [explorer](https://subnets.avax.network/).  Is there something that can be done to help move this along?  Thank you!

Also, again regarding your comment on the `parent` field, given that these subnets are standalone blockchains and not shards or L2s, it doesn't seem that adding the `parent` field makes sense here.

**Comment by connorch** [comment]
@ligi Bumping this - if you have a chance to review again sometime soon it would be very much appreciated 🙏 .  This is blocking us on some important new features in our new subnet explorer since our external contract verification service (Sourcify) requires that the chain is added here.

**Comment by zaksta11** [comment]
How can I help.dontno WHT I did..learning

**Comment by connorch** [comment]
@ligi Is there anything at all I can do to help push this along?  Or is there someone else that can help us if you're unavailable?  We've been struggling to catch your eye (we even tried [tweating you](https://twitter.com/cgcardona/status/1559536972963758084)) but it really is important to us that we get this pushed through.

We're borderline considering building out our entire own contract verification service because ethereum-lists is a Sourcify dependency and it's been such a challenge to get this PR pushed through.

**Comment by zaksta11** [comment]
How can I help..I need a job

**Comment by connorch** [comment]
Closing this since we're not making progress here.  Going to resubmit this PR with smaller changes.

**Comment by APrimaveraV** [comment]
Hi again from the Dominican Republic Sr.👋

**Comment by zaksta11** [comment]
OK alguds

**Pull request closed without merging**
