### PR TITLE
Add BOMB Mainnet + Testnet: ChainID 2300 and 2399

### PR DESCRIPTION
**Pull request by cryptoaaron**
Included are spec files for both BOMB Chain id 2300 and BOMB Chain Testnet id 2399.  Also correct file specifying image has been included.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

**Comment by cryptoaaron** [comment]
I have added the file exactly as you requested.  Let me know if anything else requires changing 👍

**Comment by cryptoaaron** [comment]
I see the problem causing build to fail and just pushed another commit with fix

**Comment by cryptoaaron** [comment]
Sorry I closed the PR by accident while submitting prior comment, I just re-opened

**Review by ligi — APPROVED** [review]

**Pull request merged**
