### PR TITLE
Update Optimistic Ethereum chain info

### PR DESCRIPTION
**Pull request by K-Ho**
Minor updates to Optimistic Ethereum chain info :)

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
I am OK with the name change but do not really like the renaming of the symbol. IMHO it is good that the symbols are distinct

**Review by l2ichshop2 — APPROVED** [review]

**Review by 8214246823 — CHANGES_REQUESTED** [review]
[K-Ho:master]()

**Comment by K-Ho** [comment]
Hey @ligi, appreciate the review. RE:native currency symbols, ETH that has been deposited into Optimistic Ethereum is referred to everywhere as ETH (in wallets, dapps, explorers, etc). Having the symbol listed as OETH in the ethereum-lists right now means that either 
1. Users get an unsavory error message whenever adding the network in their metamask (see below) or 
2. We start setting the symbol for new users as OETH which would cause a ton of confusion between users that are shown as having OETH and the users that are shown as having ETH. 

If we can't change the symbol in this repo, then maybe we can instead work together with Metamask to not check that the symbol being added for the network is the same as what is listed in this repo. One thing I noticed is that Kovan ETH is listed as having a symbol of KOR in this repo, but Metamask displays Kovan ETH with a symbol of ETH, so there does seem to be a precedent with Metamask diverging from this list. Would love to hear your thoughts on this issue!

**Comment by ligi** [comment]
sorry for the delay - missed the notification about this.
IMHO it really should not be ETH - and I am not the only one thinking so - made a poll about this once: https://twitter.com/mr_ligi/status/1393135790948036610
and it is just a different thing with different trust assumptions - so it should be called differently.
Really think this should be fixed on Metamasks side and not here.
Also in the future wallets will need to go away from a network switcher and display assets across networks - what do you do then - so you may have X ETH and Y ETH - really confusing - better you have X ETH and Y OETH

**Comment by bdresser** [comment]
Hello @ligi!

As @K-Ho mentioned, applications and wallets have adopted a uniform treatment here in calling the asset ETH regardless of chain (shown below). MetaMask is trying to keep folks safe by making sure network details match; I think updating chain info here is better for users than asking MM to remove a safeguard. Consistency across L2 is key in making Ethereum accessible, clear, and affordable! 

Lmk what you think or if you'd like to chat live. 

<br>

Uniswap:
Screen Shot 2022-02-04 at 6 20 33 PM

Lyra: 
Screen Shot 2022-02-04 at 6 19 59 PM

Rainbow:


Coinbase Wallet:

**Comment by ligi** [comment]
> MetaMask is trying to keep folks safe by making sure network details match; I think updating chain info here is better for users than asking MM to remove a safeguard.

no they should not remove the safeguard - they should change the Symbol ..-)
I really think it is a mistake - but seems all wallets do this mistake - so maybe we really need to merge that mistake. But for this the branch must be rebased.

**Comment by bdresser** [comment]
Thanks @ligi! I opened a clean PR here: https://github.com/ethereum-lists/chains/pull/843

**Review by alirezaayande — APPROVED** [review]
_data/chains/eip155-10.json

**Review by alirezaayande — APPROVED** [review]
gh pr checkout 203

**Comment by alirezaayande** [comment]
> gh pro تسویه حساب 203

**Comment by ligi** [comment]
replaced by #843

**Pull request closed without merging**
