### PR TITLE
adding gaura chain mainnet

### PR DESCRIPTION
**Pull request by GauraWebTech**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
fix CI errors - e.g. short name must be unique - but found `TKM-TEST103` more than once

**Review by Karol-Madnet — APPROVED** [review]

**Comment by GauraWebTech** [comment]
Please Review

**Review by ligi — CHANGES_REQUESTED** [review]
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

**Comment by GauraWebTech** [comment]
added iconDownloaded

**Comment by GauraWebTech** [comment]
please review now  icon updated

**Review by alokeutpal — APPROVED** [review]
Y

**Pull request closed without merging**
