### PR TITLE
add Smart Layer Network

### PR DESCRIPTION
**Pull request by bobjiang**
Add Smart Layer Network

Mainnet - 5169
Testnet - 82459

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
explorer is not reachable

image

**Comment by bobjiang** [comment]
> explorer is not reachable
> 

The explorer is coming, (under construction)

so could you help to merge it and then we would publish explorer later?

**Comment by ligi** [comment]
I cannot verify EIP3091 compatibility then - so will not merge

**Comment by bobjiang** [comment]
> I cannot verify EIP3091 compatibility then - so will not merge

Thank you for your explanation.
By the way, if no EIP3091 compatibility, should I have the explorer live now?
which means could we merge this PR if I removed the EIP3091.

**Comment by bobjiang** [comment]
> I cannot verify EIP3091 compatibility then - so will not merge

Hi @ligi please verify the explorer link, thanks a lot!

**Comment by bobjiang** [comment]
Hi @ligi 
I have updated the configurations for the explorer, sorry for the wrong conf.

**Comment by bobjiang** [comment]
Hi @ligi 
would you please trigger the next build? We have fixed all the existing problems.

**Comment by bobjiang** [comment]
> Hi @ligi would you please trigger the next build? We have fixed all the existing problems.

@ligi 
it is still blocked, would you help us to merge if no further issues.

**Pull request merged**
