### PR TITLE
Add Bobascan explorer

### PR DESCRIPTION
**Pull request by matthewlilley**
Add Bobascan explorer

### CODE REVIEW

**Review by SsNiPeR1 — APPROVED** [review]
ok.

**Comment by SsNiPeR1** [comment]
wait, I need to check the compliance with eip

**Comment by matthewlilley** [comment]
> oh, this is made by etherscan, no questions then

Yeah, regular Etherscan.

**Review by ligi — CHANGES_REQUESTED** [review]
The explorer seems to be not EIP3091 compatible - just tried block an it 404s - either fix it or change to `none`

**Comment by matthewlilley** [comment]
> none

Ah, I assumed all Etherscan clones are EIP3091. I'll share this with the team.

**Comment by matthewlilley** [comment]
@ligi set to none for now. I'll open a follow up PR if they add the compatibility routes.

**Comment by matthewlilley** [comment]
@ligi quick follow up on this one:

I double checked with other L2 explorers like optimism which is listed as EIP-3091 also, but being an L2 the block route is not present whereas batch route is. So it would also 404 for block routes.

https://github.com/ethereum-lists/chains/blob/313b649b2c4ecbc5500284db49d74175559833bd/_data/chains/eip155-10.json#L20

Most dApps don't make use of the block route, so it doesn't affect our app. 

Maybe a new EIP is needed which covers L2s use of batch which seems to replace block in these cases.

**Comment by SsNiPeR1** [comment]
> Most dApps don't make use of the block route, so it doesn't affect our app.

it does: when you specify the standard, you must follow it.
you can edit standard parameter to "none" if it does not comply, or modify this explorer, or use some other explorer like [mine](https://github.com/SsNiPeR1/explorer).

**Comment by SsNiPeR1** [comment]
> > none
> 
> Ah, I assumed all Etherscan clones are EIP3091. I'll share this with the team.

yes, i thought the same

**Review by SsNiPeR1 — APPROVED** [review]
now everything is ok

**Review by ligi — APPROVED** [review]

**Comment by SsNiPeR1** [comment]
@ligi approve my pr now pleeeeeease

**Comment by matthewlilley** [comment]
> which



> > Most dApps don't make use of the block route, so it doesn't affect our app.
> 
> it does: when you specify the standard, you must follow it. you can edit standard parameter to "none" if it does not comply, or modify this explorer, or use some other explorer like [mine](https://github.com/SsNiPeR1/explorer). upd: my explorer is not so stable and it has some bugs. i am just too lazy to fix it.

Yeah. I agree, I think this is a problem with lack of a sister standard for L2 Etherscan-like explorers which all seem to use the batch route instead of block. As pointed out in previous message, Optimism Etherscan has a type of EIP-3091 but actually isn't compliant. If this were to change now, it would break our application tx links etc..

**Pull request merged**
