### PR TITLE
Add BearNetwork Chain

### PR DESCRIPTION
**Pull request by BearNetwork-BRNKC**

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
remove httpsloader/bin/main/org/ethereum/lists/chains/https/Chain.kt from your PR

**Review by Morhef — APPROVED** [review]

**Comment by BearNetwork-BRNKC** [comment]
Chain.kt remove

**Comment by BearNetwork-BRNKC** [comment]
> remove httpsloader/bin/main/org/ethereum/lists/chains/https/Chain.kt from your PR

Chain.kt remove OK

**Comment by BearNetwork-BRNKC** [comment]
Thank you for your effort.

**Comment by BearNetwork-BRNKC** [comment]
@ligi @Morhef Thank you for your effort.

**Review by BearNetwork-BRNKC — COMMENTED** [review]
request inspection

**Comment by BearNetwork-BRNKC** [comment]
Ok

ligi ***@***.***> 於 2023年1月12日 週四 22:28 寫道：

**Review by ligi — CHANGES_REQUESTED** [review]
image

**Comment by BearNetwork-BRNKC** [comment]
> image

At present, load balancing has been added, but it does not affect the use of MetaMask. After the brnkcscan debugging is completed, go online again.

**Review by ligi — CHANGES_REQUESTED** [review]
As I cannot verify EIP3091 compatibility I will not merge

**Comment by BearNetwork-BRNKC** [comment]
> As I cannot verify EIP3091 compatibility I will not merge

I asked about the team's progress

Our team is still unable to determine the completion date. In addition to optimizing the network, other functions need to be added while ensuring the integrity of the functions. Therefore, the blockchain browser is temporarily removed for now. After subsequent community users confirm that the functions are complete, we will add another Submit an application to update the blockchain browser part.

At present, submit the modified data of "eip155-641230.json" first. Blockchain explorers will be added in the future with an update method.

Thank you for your effort.

**Comment by BearNetwork-BRNKC** [comment]
OMG ..........  i pressed it again ..........................................

**Review by ligi — APPROVED** [review]

**Pull request merged**
