### PR TITLE
Update Wanchain Mainnet and Testnet icon and explorer info.

### PR DESCRIPTION
**Pull request by lolieatapple**
Update Wanchain Mainnet and Testnet icon and explorer info.

### CODE REVIEW

**Comment by lolieatapple** [comment]
Update Wanchain Mainnet and Testnet icon and explorer info.

**Comment by lolieatapple** [comment]
please merge. too long ago.  waited for 1 month.

**Comment by lolieatapple** [comment]
please merge. too long ago. waited for 1 month.

**Comment by lolieatapple** [comment]
@ligi  Please review the PR and merge it.

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
it's been 2 weeks - and it's a free service - so some patience please

**Pull request merged**
