### PR TITLE
Add Public RPC Endpoints

### LINKED ISSUE #12: Add RPC endpoints
wonder if we should add a list of RPC endpoints (can also be an empty list - so the field is optional) for the chains.
Inspired by https://github.com/ethereum-lists/chains/pull/10#issuecomment-454411114

This would also allow a ci-script to make checks for the chain_id (also inspired by the very same PR)

Disadvantage might be that it is widening the scope too much - what does the rest of the team think?

### PR DESCRIPTION
**Pull request by pedrouid**
Fix #12

### CODE REVIEW

**Comment by pedrouid** [comment]
Done, should we change the name then?

**Comment by ligi** [comment]
yea - perhaps just "rpc": {...}

**Comment by pedrouid** [comment]
Done! Good to merge

**Comment by ligi** [comment]
:+1:

**Comment by bmann** [comment]
Ideally all data fields are displayed on at least the /chains page which has enough room to include all information about the chain and can be human browseable.

**Review by minimayki6232 — APPROVED** [review]

**Pull request merged**
