### PR TITLE
add bitnet

### PR DESCRIPTION
**Pull request by masayoshikob**

### CODE REVIEW

**Comment by masayoshikob** [comment]
hi @ligi i've fixed the links and removed the end slashes, but couldn't figure out the problem with the `validate_formatting` would you be able to point out what am i missing?

**Review by ligi — CHANGES_REQUESTED** [review]
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

**Comment by masayoshikob** [comment]
all done

**Comment by ligi** [comment]
does not look this way

**Comment by masayoshikob** [comment]
well, i've ran prettier, but now it's asking for the faucet link

**Comment by masayoshikob** [comment]
i'll open another pr, this became too messy

**Pull request closed without merging**
